-- Preview database anonymization rules.
--
-- Applied via `psql --file` to Neon preview branches after migrations
-- and the dummy_safe_text() helper setup. See
-- .github/workflows/ci.yml "Apply preview database anonymization".
--
-- This file is HAND-MAINTAINED. Most UPDATEs mask one column. Constrained
-- tables may use one atomic UPDATE to preserve their checks.
--
-- Wrapped in BEGIN/COMMIT so partial failures roll back.
--
-- Adding a new masked column: add an UPDATE here, copy-paste a
-- sibling row. Read apps/optimitron/scripts/verify-preview-masking.mjs
-- to see what shapes the row-level invariant check expects.
--
-- Must not be converted into a Prisma migration without explicit
-- human approval.

BEGIN;

-- Keep the synthetic managed demo account usable on preview. The demo email,
-- password, referral code, handle, and display name are public fixtures used by
-- ?login=demo, the Try Demo button, and deployed preview smoke.
UPDATE public."Person" SET "handle" = pg_catalog.concat('person-', md5("id"::text)) WHERE "handle" IS NOT NULL AND "email" IS DISTINCT FROM 'demo@thinkbynumbers.org';
UPDATE public."Person" SET "displayName" = pg_catalog.concat(anon.fake_first_name(), ' ', anon.fake_last_name()) WHERE "displayName" IS NOT NULL AND "email" IS DISTINCT FROM 'demo@thinkbynumbers.org';
UPDATE public."Person" SET "firstName" = anon.fake_first_name() WHERE "firstName" IS NOT NULL;
UPDATE public."Person" SET "middleName" = NULL WHERE "middleName" IS NOT NULL;
UPDATE public."Person" SET "lastName" = anon.fake_last_name() WHERE "lastName" IS NOT NULL;
UPDATE public."Person" SET "email" = pg_catalog.concat('person-', md5("id"::text), '@preview.invalid') WHERE "email" IS NOT NULL AND "email" <> 'demo@thinkbynumbers.org';
UPDATE public."Person" SET "image" = NULL WHERE "image" IS NOT NULL;
UPDATE public."Person" SET "bio" = public.dummy_safe_text() WHERE "bio" IS NOT NULL;
UPDATE public."Person" SET "birthDate" = NULL WHERE "birthDate" IS NOT NULL;
UPDATE public."Person" SET "deathDate" = NULL WHERE "deathDate" IS NOT NULL;
UPDATE public."Person" SET "links" = pg_catalog.jsonb_build_object() WHERE "links" IS NOT NULL;
UPDATE public."Person" SET "currentAffiliation" = anon.fake_company() WHERE "currentAffiliation" IS NOT NULL;
UPDATE public."Person" SET "countryCode" = anon.dummy_country_code() WHERE "countryCode" IS NOT NULL;
UPDATE public."Person" SET "headline" = public.dummy_safe_text() WHERE "headline" IS NOT NULL;
UPDATE public."Person" SET "coverImage" = NULL WHERE "coverImage" IS NOT NULL;
UPDATE public."Person" SET "website" = NULL WHERE "website" IS NOT NULL;
UPDATE public."Person" SET "sourceUrl" = NULL WHERE "sourceUrl" IS NOT NULL;
UPDATE public."Person" SET "sourceRef" = pg_catalog.concat('person-source-', md5("id"::text)) WHERE "sourceRef" IS NOT NULL;
UPDATE public."PersonRelationship" SET "relationshipType" = public.dummy_safe_text() WHERE "relationshipType" IS NOT NULL;
UPDATE public."PersonCondition" SET "conditionName" = public.dummy_safe_text() WHERE "conditionName" IS NOT NULL;
UPDATE public."PersonCondition" SET "conditionCodeSystem" = NULL WHERE "conditionCodeSystem" IS NOT NULL;
UPDATE public."PersonCondition" SET "conditionCode" = NULL WHERE "conditionCode" IS NOT NULL;
UPDATE public."PersonCondition" SET "status" = 'UNKNOWN' WHERE "status" IS NOT NULL;
UPDATE public."PersonCondition" SET "sourceUrl" = NULL WHERE "sourceUrl" IS NOT NULL;
UPDATE public."PersonMemorial" SET "causeCategory" = 'UNKNOWN' WHERE "causeCategory" IS NOT NULL;
UPDATE public."PersonMemorial" SET "deathCountryCode" = NULL WHERE "deathCountryCode" IS NOT NULL;
UPDATE public."PersonMemorial" SET "deathLocation" = public.dummy_safe_text() WHERE "deathLocation" IS NOT NULL;
UPDATE public."PersonMemorial" SET "civilianStatus" = 'UNKNOWN' WHERE "civilianStatus" IS NOT NULL;
UPDATE public."PersonMemorial" SET "wasChild" = NULL WHERE "wasChild" IS NOT NULL;
UPDATE public."PersonMemorial" SET "circumstances" = public.dummy_safe_text() WHERE "circumstances" IS NOT NULL;
UPDATE public."PersonMemorialSubmission" SET "memorialMessage" = public.dummy_safe_text() WHERE "memorialMessage" IS NOT NULL;
UPDATE public."PersonMemorialSubmission" SET "consentPublicDisplayAt" = NULL WHERE "consentPublicDisplayAt" IS NOT NULL;
UPDATE public."PersonMemorialSubmission" SET "consentCourtEvidenceAt" = NULL WHERE "consentCourtEvidenceAt" IS NOT NULL;
UPDATE public."PersonMemorialResponsibleParty" SET "name" = public.dummy_safe_text() WHERE "name" IS NOT NULL;
UPDATE public."PersonMemorialResponsibleParty" SET "sourceUrl" = NULL WHERE "sourceUrl" IS NOT NULL;
UPDATE public."PersonMemorialResponsibleParty" SET "privateNotes" = public.dummy_safe_text() WHERE "privateNotes" IS NOT NULL;
UPDATE public."PersonMemorialEvidence" SET "title" = public.dummy_safe_text() WHERE "title" IS NOT NULL;
UPDATE public."PersonMemorialEvidence" SET "description" = public.dummy_safe_text() WHERE "description" IS NOT NULL;
UPDATE public."PersonMemorialEvidence" SET "sourceUrl" = NULL WHERE "sourceUrl" IS NOT NULL;
UPDATE public."PersonEfficacyLagEvidence" SET "explanation" = public.dummy_safe_text() WHERE "explanation" IS NOT NULL;
UPDATE public."User" SET "email" = pg_catalog.concat('user-', md5("id"::text), '@preview.invalid') WHERE "email" IS NOT NULL AND "email" <> 'demo@thinkbynumbers.org';
UPDATE public."User" SET "password" = NULL WHERE "password" IS NOT NULL AND "email" <> 'demo@thinkbynumbers.org';
UPDATE public."User" SET "referralCode" = pg_catalog.concat('ref-', md5("id"::text)) WHERE "referralCode" IS NOT NULL AND "email" <> 'demo@thinkbynumbers.org';
UPDATE public."User" SET "signupLandingUrl" = NULL WHERE "signupLandingUrl" IS NOT NULL;
UPDATE public."User" SET "unsubscribedScopes" = ARRAY[]::text[] WHERE "unsubscribedScopes" IS NOT NULL;
UPDATE public."User" SET "timeZone" = anon.dummy_timezone() WHERE "timeZone" IS NOT NULL;
UPDATE public."User" SET "countryCode" = anon.dummy_country_code() WHERE "countryCode" IS NOT NULL;
UPDATE public."User" SET "regionCode" = anon.dummy_state_abbr() WHERE "regionCode" IS NOT NULL;
UPDATE public."User" SET "city" = anon.fake_city() WHERE "city" IS NOT NULL;
UPDATE public."User" SET "postalCode" = anon.fake_postcode() WHERE "postalCode" IS NOT NULL;
UPDATE public."User" SET "latitude" = NULL WHERE "latitude" IS NOT NULL;
UPDATE public."User" SET "longitude" = NULL WHERE "longitude" IS NOT NULL;
UPDATE public."User" SET "annualHouseholdIncomeUsd" = NULL WHERE "annualHouseholdIncomeUsd" IS NOT NULL;
UPDATE public."User" SET "annualPersonalIncomeUsd" = NULL WHERE "annualPersonalIncomeUsd" IS NOT NULL;
UPDATE public."User" SET "householdSize" = NULL WHERE "householdSize" IS NOT NULL;
UPDATE public."User" SET "birthYear" = NULL WHERE "birthYear" IS NOT NULL;
UPDATE public."User" SET "educationLevel" = NULL WHERE "educationLevel" IS NOT NULL;
UPDATE public."User" SET "employmentStatus" = NULL WHERE "employmentStatus" IS NOT NULL;
UPDATE public."User" SET "genderIdentity" = NULL WHERE "genderIdentity" IS NOT NULL;
UPDATE public."User" SET "censusNotes" = public.dummy_safe_text() WHERE "censusNotes" IS NOT NULL;
UPDATE public."User" SET "biologicalSex" = NULL WHERE "biologicalSex" IS NOT NULL;
UPDATE public."User" SET "ethnicityOrRace" = NULL WHERE "ethnicityOrRace" IS NOT NULL;
UPDATE public."User" SET "maritalStatus" = NULL WHERE "maritalStatus" IS NOT NULL;
UPDATE public."User" SET "numberOfDependents" = NULL WHERE "numberOfDependents" IS NOT NULL;
UPDATE public."User" SET "primaryLanguage" = NULL WHERE "primaryLanguage" IS NOT NULL;
UPDATE public."User" SET "healthInsuranceType" = NULL WHERE "healthInsuranceType" IS NOT NULL;
UPDATE public."User" SET "chronicConditionCount" = NULL WHERE "chronicConditionCount" IS NOT NULL;
UPDATE public."User" SET "disabilityStatus" = NULL WHERE "disabilityStatus" IS NOT NULL;
UPDATE public."User" SET "smokingStatus" = NULL WHERE "smokingStatus" IS NOT NULL;
UPDATE public."User" SET "alcoholFrequency" = NULL WHERE "alcoholFrequency" IS NOT NULL;
UPDATE public."User" SET "heightCm" = NULL WHERE "heightCm" IS NOT NULL;
UPDATE public."User" SET "annualTaxesPaidUsd" = NULL WHERE "annualTaxesPaidUsd" IS NOT NULL;
UPDATE public."User" SET "monthlyHousingCostUsd" = NULL WHERE "monthlyHousingCostUsd" IS NOT NULL;
UPDATE public."User" SET "housingStatus" = NULL WHERE "housingStatus" IS NOT NULL;
UPDATE public."User" SET "hoursWorkedPerWeek" = NULL WHERE "hoursWorkedPerWeek" IS NOT NULL;
UPDATE public."User" SET "industryOrSector" = NULL WHERE "industryOrSector" IS NOT NULL;
UPDATE public."User" SET "citizenshipStatus" = NULL WHERE "citizenshipStatus" IS NOT NULL;
UPDATE public."User" SET "internetAccessType" = NULL WHERE "internetAccessType" IS NOT NULL;
UPDATE public."User" SET "skillTags" = ARRAY[]::text[] WHERE "skillTags" IS NOT NULL;
UPDATE public."User" SET "interestTags" = ARRAY[]::text[] WHERE "interestTags" IS NOT NULL;
UPDATE public."User" SET "availableHoursPerWeek" = NULL WHERE "availableHoursPerWeek" IS NOT NULL;
UPDATE public."User" SET "phoneNumber" = anon.dummy_cell_number() WHERE "phoneNumber" IS NOT NULL;
UPDATE public."Account" SET "providerAccountId" = md5("providerAccountId"::text) WHERE "providerAccountId" IS NOT NULL;
UPDATE public."Account" SET "refresh_token" = NULL WHERE "refresh_token" IS NOT NULL;
UPDATE public."Account" SET "access_token" = NULL WHERE "access_token" IS NOT NULL;
UPDATE public."Account" SET "scope" = NULL WHERE "scope" IS NOT NULL;
UPDATE public."Account" SET "id_token" = NULL WHERE "id_token" IS NOT NULL;
UPDATE public."Account" SET "session_state" = NULL WHERE "session_state" IS NOT NULL;
UPDATE public."Account" SET "oauth_token_secret" = NULL WHERE "oauth_token_secret" IS NOT NULL;
UPDATE public."Account" SET "oauth_token" = NULL WHERE "oauth_token" IS NOT NULL;
UPDATE public."Session" SET "sessionToken" = pg_catalog.concat('session-', md5("id"::text)) WHERE "sessionToken" IS NOT NULL;
UPDATE public."VerificationToken" SET "identifier" = pg_catalog.concat('verify-', md5("identifier"::text), '@preview.invalid') WHERE "identifier" IS NOT NULL;
UPDATE public."VerificationToken" SET "token" = pg_catalog.concat('verification-token-', md5("token"::text)) WHERE "token" IS NOT NULL;
UPDATE public."PersonhoodVerification" SET "externalId" = pg_catalog.concat('personhood-', md5("externalId"::text)) WHERE "externalId" IS NOT NULL;
UPDATE public."PersonhoodVerification" SET "action" = NULL WHERE "action" IS NOT NULL;
UPDATE public."PersonhoodVerification" SET "verificationLevel" = NULL WHERE "verificationLevel" IS NOT NULL;
UPDATE public."PersonhoodVerification" SET "signalHash" = NULL WHERE "signalHash" IS NOT NULL;
UPDATE public."PersonhoodVerification" SET "providerMetadata" = public.dummy_safe_text() WHERE "providerMetadata" IS NOT NULL;
UPDATE public."Subject" SET "externalId" = pg_catalog.concat('subject-', md5("id"::text)) WHERE "externalId" IS NOT NULL;
UPDATE public."Subject" SET "displayName" = public.dummy_safe_text() WHERE "displayName" IS NOT NULL;
UPDATE public."NOf1Variable" SET "fillingValue" = NULL WHERE "fillingValue" IS NOT NULL;
UPDATE public."NOf1Variable" SET "minimumAllowedValue" = NULL WHERE "minimumAllowedValue" IS NOT NULL;
UPDATE public."NOf1Variable" SET "maximumAllowedValue" = NULL WHERE "maximumAllowedValue" IS NOT NULL;
UPDATE public."NOf1Variable" SET "numberOfMeasurements" = 0 WHERE "numberOfMeasurements" IS NOT NULL;
UPDATE public."NOf1Variable" SET "latestMeasurementStartAt" = NULL WHERE "latestMeasurementStartAt" IS NOT NULL;
UPDATE public."NOf1Variable" SET "earliestMeasurementStartAt" = NULL WHERE "earliestMeasurementStartAt" IS NOT NULL;
UPDATE public."NOf1Variable" SET "mean" = NULL WHERE "mean" IS NOT NULL;
UPDATE public."NOf1Variable" SET "median" = NULL WHERE "median" IS NOT NULL;
UPDATE public."NOf1Variable" SET "standardDeviation" = NULL WHERE "standardDeviation" IS NOT NULL;
UPDATE public."NOf1Variable" SET "variance" = NULL WHERE "variance" IS NOT NULL;
UPDATE public."NOf1Variable" SET "kurtosis" = NULL WHERE "kurtosis" IS NOT NULL;
UPDATE public."NOf1Variable" SET "skewness" = NULL WHERE "skewness" IS NOT NULL;
UPDATE public."NOf1Variable" SET "minimumRecordedValue" = NULL WHERE "minimumRecordedValue" IS NOT NULL;
UPDATE public."NOf1Variable" SET "maximumRecordedValue" = NULL WHERE "maximumRecordedValue" IS NOT NULL;
UPDATE public."Measurement" SET "value" = 0 WHERE "value" IS NOT NULL;
UPDATE public."Measurement" SET "originalValue" = 0 WHERE "originalValue" IS NOT NULL;
UPDATE public."Measurement" SET "duration" = NULL WHERE "duration" IS NOT NULL;
UPDATE public."Measurement" SET "note" = public.dummy_safe_text() WHERE "note" IS NOT NULL;
UPDATE public."Measurement" SET "sourceName" = public.dummy_safe_text() WHERE "sourceName" IS NOT NULL;
UPDATE public."Measurement" SET "latitude" = NULL WHERE "latitude" IS NOT NULL;
UPDATE public."Measurement" SET "longitude" = NULL WHERE "longitude" IS NOT NULL;
UPDATE public."InterventionExperience" SET "status" = 'UNKNOWN' WHERE "status" IS NOT NULL;
UPDATE public."InterventionExperience" SET "startedAt" = NULL WHERE "startedAt" IS NOT NULL;
UPDATE public."InterventionExperience" SET "endedAt" = NULL WHERE "endedAt" IS NOT NULL;
UPDATE public."InterventionExperience" SET "doseValue" = NULL WHERE "doseValue" IS NOT NULL;
UPDATE public."InterventionExperience" SET "frequencyText" = public.dummy_safe_text() WHERE "frequencyText" IS NOT NULL;
UPDATE public."InterventionExperience" SET "notes" = public.dummy_safe_text() WHERE "notes" IS NOT NULL;
UPDATE public."InterventionExperienceOutcome" SET "rating" = 'UNKNOWN' WHERE "rating" IS NOT NULL;
UPDATE public."InterventionExperienceOutcome" SET "value" = NULL WHERE "value" IS NOT NULL;
UPDATE public."InterventionExperienceOutcome" SET "publicComment" = public.dummy_safe_text() WHERE "publicComment" IS NOT NULL;
UPDATE public."InterventionExperienceSideEffect" SET "severity" = 'UNKNOWN' WHERE "severity" IS NOT NULL;
UPDATE public."InterventionExperienceSideEffect" SET "onsetAt" = NULL WHERE "onsetAt" IS NOT NULL;
UPDATE public."InterventionExperienceSideEffect" SET "resolvedAt" = NULL WHERE "resolvedAt" IS NOT NULL;
UPDATE public."InterventionExperienceSideEffect" SET "isSerious" = NULL WHERE "isSerious" IS NOT NULL;
UPDATE public."InterventionExperienceSideEffect" SET "actionTaken" = public.dummy_safe_text() WHERE "actionTaken" IS NOT NULL;
UPDATE public."InterventionExperienceSideEffect" SET "publicComment" = public.dummy_safe_text() WHERE "publicComment" IS NOT NULL;
UPDATE public."TrackingReminder" SET "defaultValue" = NULL WHERE "defaultValue" IS NOT NULL;
UPDATE public."TrackingReminder" SET "reminderEndTime" = NULL WHERE "reminderEndTime" IS NOT NULL;
UPDATE public."TrackingReminder" SET "instructions" = public.dummy_safe_text() WHERE "instructions" IS NOT NULL;
UPDATE public."TrackingReminder" SET "lastTracked" = NULL WHERE "lastTracked" IS NOT NULL;
UPDATE public."TrackingReminder" SET "startTrackingDate" = NULL WHERE "startTrackingDate" IS NOT NULL;
UPDATE public."TrackingReminder" SET "stopTrackingDate" = NULL WHERE "stopTrackingDate" IS NOT NULL;
UPDATE public."TrackingReminderNotification" SET "notifyAt" = '2025-01-01 09:00:00+00' WHERE "notifyAt" IS NOT NULL;
UPDATE public."TrackingReminderNotification" SET "notifiedAt" = NULL WHERE "notifiedAt" IS NOT NULL;
UPDATE public."TrackingReminderNotification" SET "receivedAt" = NULL WHERE "receivedAt" IS NOT NULL;
UPDATE public."TrackingReminderNotification" SET "trackedValue" = NULL WHERE "trackedValue" IS NOT NULL;
UPDATE public."TrackingReminderNotification" SET "status" = 'PENDING' WHERE "status" IS NOT NULL;
UPDATE public."IntegrationConnection" SET "accessToken" = NULL WHERE "accessToken" IS NOT NULL;
UPDATE public."IntegrationConnection" SET "refreshToken" = NULL WHERE "refreshToken" IS NOT NULL;
UPDATE public."IntegrationConnection" SET "tokenExpiresAt" = NULL WHERE "tokenExpiresAt" IS NOT NULL;
UPDATE public."IntegrationConnection" SET "lastSyncAt" = NULL WHERE "lastSyncAt" IS NOT NULL;
UPDATE public."IntegrationConnection" SET "nextSyncAt" = NULL WHERE "nextSyncAt" IS NOT NULL;
UPDATE public."IntegrationConnection" SET "lastSyncError" = public.dummy_safe_text() WHERE "lastSyncError" IS NOT NULL;
UPDATE public."IntegrationSyncLog" SET "errorMessage" = public.dummy_safe_text() WHERE "errorMessage" IS NOT NULL;
UPDATE public."ReferralClick" SET "code" = pg_catalog.concat('ref-click-', md5("id"::text)) WHERE "code" IS NOT NULL;
UPDATE public."ReferralClick" SET "refererUrl" = NULL WHERE "refererUrl" IS NOT NULL;
UPDATE public."ReferralClick" SET "userAgent" = anon.dummy_user_agent() WHERE "userAgent" IS NOT NULL;
UPDATE public."ReferralClick" SET "countryCode" = anon.dummy_country_code() WHERE "countryCode" IS NOT NULL;
UPDATE public."ReferralInvitation" SET "inviteToken" = pg_catalog.concat('invite-', md5("id"::text)) WHERE "inviteToken" IS NOT NULL;
UPDATE public."ReferralInvitation" SET "recipientName" = pg_catalog.concat(anon.fake_first_name(), ' ', anon.fake_last_name()) WHERE "recipientName" IS NOT NULL;
UPDATE public."ReferralInvitation" SET "recipientEmail" = anon.fake_email() WHERE "recipientEmail" IS NOT NULL;
UPDATE public."ReferralInvitation" SET "messageText" = public.dummy_safe_text() WHERE "messageText" IS NOT NULL;
UPDATE public."ReferralInvitation" SET "originUrl" = NULL WHERE "originUrl" IS NOT NULL;
UPDATE public."EmailLog" SET "toAddress" = anon.fake_email() WHERE "toAddress" IS NOT NULL;
UPDATE public."EmailLog" SET "subject" = public.dummy_safe_text() WHERE "subject" IS NOT NULL;
UPDATE public."EmailLog" SET "providerMessageId" = pg_catalog.concat('email-provider-', md5("id"::text)) WHERE "providerMessageId" IS NOT NULL;
UPDATE public."EmailLog" SET "subjectTemplate" = public.dummy_safe_text() WHERE "subjectTemplate" IS NOT NULL;
UPDATE public."EmailLog" SET "sendContext" = pg_catalog.jsonb_build_object() WHERE "sendContext" IS NOT NULL;
UPDATE public."EmailLog" SET "errorMessage" = public.dummy_safe_text() WHERE "errorMessage" IS NOT NULL;
UPDATE public."EmailLog" SET "dedupeKey" = pg_catalog.concat('email-dedupe-', md5("id"::text)) WHERE "dedupeKey" IS NOT NULL;
UPDATE public."ShareAttempt" SET "templateHash" = NULL WHERE "templateHash" IS NOT NULL;
UPDATE public."ShareAttempt" SET "templateBody" = public.dummy_safe_text() WHERE "templateBody" IS NOT NULL;
UPDATE public."ShareAttempt" SET "renderedMessage" = public.dummy_safe_text() WHERE "renderedMessage" IS NOT NULL;
UPDATE public."ShareAttempt" SET "renderedHash" = NULL WHERE "renderedHash" IS NOT NULL;
UPDATE public."ShareAttempt" SET "context" = pg_catalog.jsonb_build_object() WHERE "context" IS NOT NULL;
UPDATE public."CitizenBillVote" SET "reasoning" = public.dummy_safe_text() WHERE "reasoning" IS NOT NULL;
UPDATE public."CitizenBillVote" SET "shareIdentifier" = pg_catalog.concat('citizen-vote-', md5("id"::text)) WHERE "shareIdentifier" IS NOT NULL;
UPDATE public."CitizenBillVote" SET "cbaSnapshot" = public.dummy_safe_text() WHERE "cbaSnapshot" IS NOT NULL;
UPDATE public."ReferendumVote" SET "publicComment" = public.dummy_safe_text() WHERE "publicComment" IS NOT NULL;
UPDATE public."ReferendumVote" SET "originUrl" = NULL WHERE "originUrl" IS NOT NULL;
UPDATE public."WebPushSubscription" SET "endpoint" = pg_catalog.concat('push-', md5("id"::text)) WHERE "endpoint" IS NOT NULL;
UPDATE public."WebPushSubscription" SET "p256dh" = pg_catalog.concat('p256dh-', md5("id"::text)) WHERE "p256dh" IS NOT NULL;
UPDATE public."WebPushSubscription" SET "auth" = pg_catalog.concat('push-auth-', md5("id"::text)) WHERE "auth" IS NOT NULL;
UPDATE public."WebPushSubscription" SET "userAgent" = anon.dummy_user_agent() WHERE "userAgent" IS NOT NULL;
UPDATE public."UserPreference" SET "reminderStartTime" = '09:00' WHERE "reminderStartTime" IS NOT NULL;
UPDATE public."UserPreference" SET "quietHoursStart" = '21:00' WHERE "quietHoursStart" IS NOT NULL;
UPDATE public."UserPreference" SET "lastPushSentAt" = NULL WHERE "lastPushSentAt" IS NOT NULL;
UPDATE public."UserPreference" SET "lastCheckInAt" = NULL WHERE "lastCheckInAt" IS NOT NULL;
UPDATE public."WishocraticEncryptedAllocation" SET "ciphertext" = pg_catalog.concat('encrypted-allocation-', md5("id"::text)) WHERE "ciphertext" IS NOT NULL;
UPDATE public."WishocraticEncryptedAllocation" SET "iv" = pg_catalog.concat('iv-', md5("id"::text)) WHERE "iv" IS NOT NULL;
UPDATE public."SocialAccount" SET "accountId" = pg_catalog.concat('social-account-', md5("id"::text)) WHERE "accountId" IS NOT NULL;
UPDATE public."SocialAccount" SET "username" = anon.dummy_username() WHERE "username" IS NOT NULL;
UPDATE public."SocialAccount" SET "walletAddress" = pg_catalog.concat('wallet-', md5("id"::text)) WHERE "walletAddress" IS NOT NULL;
UPDATE public."PointMint" SET "nullifierHash" = pg_catalog.concat('nullifier-', md5("id"::text)) WHERE "nullifierHash" IS NOT NULL;
UPDATE public."PointMint" SET "walletAddress" = pg_catalog.concat('wallet-', md5("id"::text)) WHERE "walletAddress" IS NOT NULL;
UPDATE public."PointMint" SET "txHash" = pg_catalog.concat('tx-', md5("id"::text)) WHERE "txHash" IS NOT NULL;
UPDATE public."PrizeTreasuryDeposit" SET "depositorAddress" = pg_catalog.concat('wallet-', md5("id"::text)) WHERE "depositorAddress" IS NOT NULL;
UPDATE public."PrizeTreasuryDeposit" SET "txHash" = pg_catalog.concat('tx-', md5("id"::text)) WHERE "txHash" IS NOT NULL;
UPDATE public."PublicGoodsRecipient" SET "walletAddress" = pg_catalog.concat('wallet-', md5("id"::text)) WHERE "walletAddress" IS NOT NULL;
UPDATE public."Activity" SET "description" = public.dummy_safe_text() WHERE "description" IS NOT NULL;
UPDATE public."Activity" SET "metadata" = public.dummy_safe_text() WHERE "metadata" IS NOT NULL;
UPDATE public."Notification" SET "title" = public.dummy_safe_text() WHERE "title" IS NOT NULL;
UPDATE public."Notification" SET "message" = public.dummy_safe_text() WHERE "message" IS NOT NULL;
UPDATE public."Notification" SET "link" = NULL WHERE "link" IS NOT NULL;
UPDATE public."Badge" SET "metadata" = public.dummy_safe_text() WHERE "metadata" IS NOT NULL;
UPDATE public."WishPoint" SET "metadata" = public.dummy_safe_text() WHERE "metadata" IS NOT NULL;
UPDATE public."Organization" SET "description" = public.dummy_safe_text() WHERE "description" IS NOT NULL;
UPDATE public."Organization" SET "website" = NULL WHERE "website" IS NOT NULL;
UPDATE public."Organization" SET "squareLogoUrl" = NULL WHERE "squareLogoUrl" IS NOT NULL;
UPDATE public."Organization" SET "wordmarkLogoUrl" = NULL WHERE "wordmarkLogoUrl" IS NOT NULL;
UPDATE public."Organization" SET "donationUrl" = NULL WHERE "donationUrl" IS NOT NULL;
UPDATE public."Organization" SET "sourceUrl" = NULL WHERE "sourceUrl" IS NOT NULL;
UPDATE public."Organization" SET "sourceRef" = pg_catalog.concat('org-source-', md5("id"::text)) WHERE "sourceRef" IS NOT NULL;
UPDATE public."Organization" SET "contactEmail" = anon.fake_email() WHERE "contactEmail" IS NOT NULL;
UPDATE public."OrganizationReferendumPosition" SET "statement" = public.dummy_safe_text() WHERE "statement" IS NOT NULL;
UPDATE public."CourtCase" SET "title" = public.dummy_safe_text() WHERE "title" IS NOT NULL;
UPDATE public."CourtCase" SET "summary" = public.dummy_safe_text() WHERE "summary" IS NOT NULL;
UPDATE public."CourtCase" SET "metadataJson" = pg_catalog.jsonb_build_object() WHERE "metadataJson" IS NOT NULL;
UPDATE public."CourtCaseParty" SET "partyKey" = pg_catalog.concat('court-party-', md5("id"::text)) WHERE "partyKey" IS NOT NULL;
UPDATE public."CourtCaseParty" SET "displayNameSnapshot" = pg_catalog.concat(anon.fake_first_name(), ' ', anon.fake_last_name()) WHERE "displayNameSnapshot" IS NOT NULL;
UPDATE public."CourtCaseParty" SET "standingTheory" = public.dummy_safe_text() WHERE "standingTheory" IS NOT NULL;
UPDATE public."CourtCaseParty" SET "metadataJson" = pg_catalog.jsonb_build_object() WHERE "metadataJson" IS NOT NULL;
UPDATE public."CourtCaseClaim" SET "title" = public.dummy_safe_text() WHERE "title" IS NOT NULL;
UPDATE public."CourtCaseClaim" SET "claimType" = public.dummy_safe_text() WHERE "claimType" IS NOT NULL;
UPDATE public."CourtCaseClaim" SET "argumentMarkdown" = public.dummy_safe_text() WHERE "argumentMarkdown" IS NOT NULL;
UPDATE public."CourtCaseClaim" SET "requestedFinding" = public.dummy_safe_text() WHERE "requestedFinding" IS NOT NULL;
UPDATE public."CourtCaseClaim" SET "metadataJson" = pg_catalog.jsonb_build_object() WHERE "metadataJson" IS NOT NULL;
UPDATE public."CourtCaseHarm" SET "harmType" = public.dummy_safe_text() WHERE "harmType" IS NOT NULL;
UPDATE public."CourtCaseHarm" SET "title" = public.dummy_safe_text() WHERE "title" IS NOT NULL;
UPDATE public."CourtCaseHarm" SET "bodyMarkdown" = public.dummy_safe_text() WHERE "bodyMarkdown" IS NOT NULL;
UPDATE public."CourtCaseHarm" SET "unit" = NULL WHERE "unit" IS NOT NULL;
UPDATE public."CourtCaseHarm" SET "metadataJson" = pg_catalog.jsonb_build_object() WHERE "metadataJson" IS NOT NULL;
UPDATE public."CourtCaseEvidence" SET "evidenceKey" = pg_catalog.concat('court-evidence-', md5("id"::text)) WHERE "evidenceKey" IS NOT NULL;
UPDATE public."CourtCaseEvidence" SET "evidenceType" = public.dummy_safe_text() WHERE "evidenceType" IS NOT NULL;
UPDATE public."CourtCaseEvidence" SET "title" = public.dummy_safe_text() WHERE "title" IS NOT NULL;
UPDATE public."CourtCaseEvidence" SET "bodyMarkdown" = public.dummy_safe_text() WHERE "bodyMarkdown" IS NOT NULL;
UPDATE public."CourtCaseEvidence" SET "sourceUrl" = NULL WHERE "sourceUrl" IS NOT NULL;
UPDATE public."CourtCaseEvidence" SET "contentHash" = NULL WHERE "contentHash" IS NOT NULL;
UPDATE public."CourtCaseEvidence" SET "metadataJson" = pg_catalog.jsonb_build_object() WHERE "metadataJson" IS NOT NULL;
UPDATE public."CourtCaseRemedy" SET "remedyKey" = pg_catalog.concat('court-remedy-', md5("id"::text)) WHERE "remedyKey" IS NOT NULL;
UPDATE public."CourtCaseRemedy" SET "remedyType" = public.dummy_safe_text() WHERE "remedyType" IS NOT NULL;
UPDATE public."CourtCaseRemedy" SET "title" = public.dummy_safe_text() WHERE "title" IS NOT NULL;
UPDATE public."CourtCaseRemedy" SET "bodyMarkdown" = public.dummy_safe_text() WHERE "bodyMarkdown" IS NOT NULL;
UPDATE public."CourtCaseRemedy" SET "metadataJson" = pg_catalog.jsonb_build_object() WHERE "metadataJson" IS NOT NULL;
UPDATE public."Task" SET "title" = public.dummy_safe_text() WHERE "title" IS NOT NULL;
UPDATE public."Task" SET "description" = public.dummy_safe_text() WHERE "description" IS NOT NULL;
UPDATE public."Task" SET "impactStatement" = public.dummy_safe_text() WHERE "impactStatement" IS NOT NULL;
UPDATE public."Task" SET "roleTitle" = public.dummy_safe_text() WHERE "roleTitle" IS NOT NULL;
UPDATE public."Task" SET "assigneeAffiliationSnapshot" = public.dummy_safe_text() WHERE "assigneeAffiliationSnapshot" IS NOT NULL;
UPDATE public."Task" SET "skillTags" = ARRAY[]::text[] WHERE "skillTags" IS NOT NULL;
UPDATE public."Task" SET "interestTags" = ARRAY[]::text[] WHERE "interestTags" IS NOT NULL;
UPDATE public."Task" SET "contextJson" = pg_catalog.jsonb_build_object() WHERE "contextJson" IS NOT NULL;
UPDATE public."Task" SET "completionEvidence" = public.dummy_safe_text() WHERE "completionEvidence" IS NOT NULL;
UPDATE public."TaskClaim" SET "completionEvidence" = public.dummy_safe_text() WHERE "completionEvidence" IS NOT NULL;
UPDATE public."TaskClaim" SET "verificationNote" = public.dummy_safe_text() WHERE "verificationNote" IS NOT NULL;
UPDATE public."TaskExecutionArtifact" SET "externalUrl" = pg_catalog.concat('https://preview.invalid/artifact/', md5("id"::text)) WHERE "externalUrl" IS NOT NULL;
UPDATE public."TaskExecutionArtifact" SET "structuredResultJson" = pg_catalog.jsonb_build_object() WHERE "structuredResultJson" IS NOT NULL;
UPDATE public."TaskExecutionArtifact" SET "label" = public.dummy_safe_text() WHERE "label" IS NOT NULL;
UPDATE public."TaskExecutionArtifact" SET "contentHash" = pg_catalog.concat('artifact-content-', md5("id"::text));
UPDATE public."TaskExecutionArtifact" SET "metadataJson" = pg_catalog.jsonb_build_object() WHERE "metadataJson" IS NOT NULL;
ALTER TABLE public."TaskVerification" DISABLE TRIGGER "TaskVerification_protect_evidence";
UPDATE public."TaskVerification"
SET
  "acceptanceCriteriaSnapshotJson" = pg_catalog.jsonb_build_object(),
  "criterionResultsJson" = CASE WHEN "criterionResultsJson" IS NULL THEN NULL ELSE pg_catalog.jsonb_build_object() END,
  "evidenceJson" = CASE WHEN "evidenceJson" IS NULL THEN NULL ELSE pg_catalog.jsonb_build_object() END,
  "note" = CASE WHEN "note" IS NULL THEN NULL ELSE public.dummy_safe_text() END;
ALTER TABLE public."TaskVerification" ENABLE TRIGGER "TaskVerification_protect_evidence";
ALTER TABLE public."ExternalActionRequest" DISABLE TRIGGER "ExternalActionRequest_immutable_payload";
UPDATE public."ExternalActionRequest"
SET
  "operation" = public.dummy_safe_text(),
  "destination" = public.dummy_safe_text(),
  "payloadJson" = pg_catalog.jsonb_build_object(),
  "payloadHash" = pg_catalog.concat('external-action-payload-', md5("id"::text)),
  "approvedPayloadHash" = CASE WHEN "approvedPayloadHash" IS NULL THEN NULL ELSE pg_catalog.concat('external-action-payload-', md5("id"::text)) END,
  "executionReceiptJson" = CASE WHEN "executionReceiptJson" IS NULL THEN NULL ELSE pg_catalog.jsonb_build_object() END,
  "failureMessage" = CASE WHEN "failureMessage" IS NULL THEN NULL ELSE public.dummy_safe_text() END,
  "idempotencyKey" = pg_catalog.concat('external-action-', md5("id"::text));
ALTER TABLE public."ExternalActionRequest" ENABLE TRIGGER "ExternalActionRequest_immutable_payload";
UPDATE public."SourceArtifact" SET "externalKey" = pg_catalog.concat('artifact-external-', md5("id"::text)) WHERE "externalKey" IS NOT NULL;
UPDATE public."SourceArtifact" SET "versionKey" = pg_catalog.concat('artifact-version-', md5("id"::text)) WHERE "versionKey" IS NOT NULL;
UPDATE public."SourceArtifact" SET "title" = public.dummy_safe_text() WHERE "title" IS NOT NULL;
UPDATE public."SourceArtifact" SET "sourceUrl" = NULL WHERE "sourceUrl" IS NOT NULL;
UPDATE public."SourceArtifact" SET "sourceRef" = pg_catalog.concat('artifact-source-', md5("id"::text)) WHERE "sourceRef" IS NOT NULL;
UPDATE public."SourceArtifact" SET "payloadJson" = pg_catalog.jsonb_build_object() WHERE "payloadJson" IS NOT NULL;
UPDATE public."TaskComment" SET "authorNameSnapshot" = pg_catalog.concat(anon.fake_first_name(), ' ', anon.fake_last_name()) WHERE "authorNameSnapshot" IS NOT NULL;
UPDATE public."TaskComment" SET "message" = public.dummy_safe_text() WHERE "message" IS NOT NULL;
UPDATE public."TaskComment" SET "mediaUrl" = NULL WHERE "mediaUrl" IS NOT NULL;
UPDATE public."TaskComment" SET "mentionedUserIds" = ARRAY[]::text[] WHERE "mentionedUserIds" IS NOT NULL;
UPDATE public."TaskComment" SET "citationsJson" = pg_catalog.jsonb_build_object() WHERE "citationsJson" IS NOT NULL;
UPDATE public."TaskComment" SET "moderationReason" = public.dummy_safe_text() WHERE "moderationReason" IS NOT NULL;
UPDATE public."TaskCommentVote" SET "ipHash" = pg_catalog.concat('ip-', md5("id"::text)) WHERE "ipHash" IS NOT NULL;
UPDATE public."TaskCommentVote" SET "userAgentHash" = pg_catalog.concat('ua-', md5("id"::text)) WHERE "userAgentHash" IS NOT NULL;
UPDATE public."TaskEdge" SET "assumptionsJson" = pg_catalog.jsonb_build_object() WHERE "assumptionsJson" IS NOT NULL;
UPDATE public."TaskEdge" SET "notes" = public.dummy_safe_text() WHERE "notes" IS NOT NULL;
UPDATE public."TaskImpactEstimateSet" SET "assumptionsJson" = pg_catalog.jsonb_build_object() WHERE "assumptionsJson" IS NOT NULL;
UPDATE public."TaskImpactFrameEstimate" SET "customFrameLabel" = public.dummy_safe_text() WHERE "customFrameLabel" IS NOT NULL;
UPDATE public."TaskImpactFrameEstimate" SET "summaryStatsJson" = pg_catalog.jsonb_build_object() WHERE "summaryStatsJson" IS NOT NULL;
UPDATE public."TaskImpactMetric" SET "valueJson" = pg_catalog.jsonb_build_object() WHERE "valueJson" IS NOT NULL;
UPDATE public."TaskImpactMetric" SET "summaryStatsJson" = pg_catalog.jsonb_build_object() WHERE "summaryStatsJson" IS NOT NULL;
UPDATE public."TaskImpactMetric" SET "metadataJson" = pg_catalog.jsonb_build_object() WHERE "metadataJson" IS NOT NULL;
UPDATE public."TaskCommunicationEndpoint" SET "label" = public.dummy_safe_text() WHERE "label" IS NOT NULL;
UPDATE public."TaskCommunicationEndpoint" SET "url" = NULL WHERE "url" IS NOT NULL;
UPDATE public."TaskCommunicationEndpoint" SET "email" = anon.fake_email() WHERE "email" IS NOT NULL;
UPDATE public."TaskCommunicationEndpoint" SET "instructions" = public.dummy_safe_text() WHERE "instructions" IS NOT NULL;
UPDATE public."TaskCommunicationEndpoint" SET "sourceUrl" = NULL WHERE "sourceUrl" IS NOT NULL;
UPDATE public."TaskCommunicationTemplate" SET "label" = public.dummy_safe_text() WHERE "label" IS NOT NULL;
UPDATE public."TaskCommunicationVariant" SET "subject" = public.dummy_safe_text() WHERE "subject" IS NOT NULL;
UPDATE public."TaskCommunicationVariant" SET "htmlBody" = public.dummy_safe_text() WHERE "htmlBody" IS NOT NULL;
UPDATE public."TaskCommunicationVariant" SET "textBody" = public.dummy_safe_text() WHERE "textBody" IS NOT NULL;
UPDATE public."TaskCommunicationVariant" SET "senderIdentity" = public.dummy_safe_text() WHERE "senderIdentity" IS NOT NULL;
UPDATE public."TaskCommunicationVariant" SET "signature" = public.dummy_safe_text() WHERE "signature" IS NOT NULL;
UPDATE public."TaskCommunicationVariant" SET "footer" = public.dummy_safe_text() WHERE "footer" IS NOT NULL;
UPDATE public."TaskCommunication" SET "recipientEmail" = anon.fake_email() WHERE "recipientEmail" IS NOT NULL;
UPDATE public."TaskCommunication" SET "recipientNameSnapshot" = pg_catalog.concat(anon.fake_first_name(), ' ', anon.fake_last_name()) WHERE "recipientNameSnapshot" IS NOT NULL;
UPDATE public."TaskCommunication" SET "senderNameSnapshot" = pg_catalog.concat(anon.fake_first_name(), ' ', anon.fake_last_name()) WHERE "senderNameSnapshot" IS NOT NULL;
UPDATE public."TaskCommunication" SET "unsubscribeToken" = pg_catalog.concat('unsubscribe-', md5("id"::text)) WHERE "unsubscribeToken" IS NOT NULL;
UPDATE public."TaskCommunication" SET "externalUrl" = NULL WHERE "externalUrl" IS NOT NULL;
UPDATE public."TaskCommunication" SET "errorMessage" = public.dummy_safe_text() WHERE "errorMessage" IS NOT NULL;
UPDATE public."TaskCommunication" SET "providerMessageId" = pg_catalog.concat('task-provider-', md5("id"::text)) WHERE "providerMessageId" IS NOT NULL;
UPDATE public."TaskCommunication" SET "metadataJson" = pg_catalog.jsonb_build_object() WHERE "metadataJson" IS NOT NULL;
-- Preserve repository-owned managed trigger blueprints. They are not production
-- PII, and preview runtime paths need them intact after managed-data sync.
UPDATE public."TaskTrigger" SET "eventFilter" = pg_catalog.jsonb_build_object() WHERE "eventFilter" IS NOT NULL AND "triggerKey" NOT IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer');
UPDATE public."TaskTrigger" SET "disabledReason" = public.dummy_safe_text() WHERE "disabledReason" IS NOT NULL AND "triggerKey" NOT IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer');
UPDATE public."TaskTrigger" SET "idempotencyKeyTemplate" = public.dummy_safe_text() WHERE "idempotencyKeyTemplate" IS NOT NULL AND "triggerKey" NOT IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer');
UPDATE public."TaskTrigger" SET "completionGate" = pg_catalog.jsonb_build_object() WHERE "completionGate" IS NOT NULL AND "triggerKey" NOT IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer');
UPDATE public."TaskTrigger" SET "notes" = public.dummy_safe_text() WHERE "notes" IS NOT NULL AND "triggerKey" NOT IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer');
UPDATE public."TaskTrigger" SET "metadata" = pg_catalog.jsonb_build_object() WHERE "metadata" IS NOT NULL AND "triggerKey" NOT IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer');
UPDATE public."TaskSpawnSpec" SET "titleTemplate" = public.dummy_safe_text() WHERE "titleTemplate" IS NOT NULL AND "triggerId" NOT IN (SELECT "id" FROM public."TaskTrigger" WHERE "triggerKey" IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer'));
UPDATE public."TaskSpawnSpec" SET "descriptionTemplate" = public.dummy_safe_text() WHERE "descriptionTemplate" IS NOT NULL AND "triggerId" NOT IN (SELECT "id" FROM public."TaskTrigger" WHERE "triggerKey" IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer'));
UPDATE public."TaskSpawnSpec" SET "impactStatementTemplate" = public.dummy_safe_text() WHERE "impactStatementTemplate" IS NOT NULL AND "triggerId" NOT IN (SELECT "id" FROM public."TaskTrigger" WHERE "triggerKey" IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer'));
UPDATE public."TaskSpawnSpec" SET "roleTitleTemplate" = public.dummy_safe_text() WHERE "roleTitleTemplate" IS NOT NULL AND "triggerId" NOT IN (SELECT "id" FROM public."TaskTrigger" WHERE "triggerKey" IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer'));
UPDATE public."TaskSpawnSpec" SET "skillTagTemplates" = ARRAY[]::text[] WHERE "skillTagTemplates" IS NOT NULL AND "triggerId" NOT IN (SELECT "id" FROM public."TaskTrigger" WHERE "triggerKey" IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer'));
UPDATE public."TaskSpawnSpec" SET "interestTagTemplates" = ARRAY[]::text[] WHERE "interestTagTemplates" IS NOT NULL AND "triggerId" NOT IN (SELECT "id" FROM public."TaskTrigger" WHERE "triggerKey" IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer'));
UPDATE public."TaskSpawnSpec" SET "actionLinkUrlTemplate" = NULL WHERE "actionLinkUrlTemplate" IS NOT NULL AND "triggerId" NOT IN (SELECT "id" FROM public."TaskTrigger" WHERE "triggerKey" IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer'));
UPDATE public."TaskSpawnSpec" SET "actionLinkLabelTemplate" = public.dummy_safe_text() WHERE "actionLinkLabelTemplate" IS NOT NULL AND "triggerId" NOT IN (SELECT "id" FROM public."TaskTrigger" WHERE "triggerKey" IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer'));
UPDATE public."TaskSpawnSpec" SET "actionLinkInstructionsTemplate" = public.dummy_safe_text() WHERE "actionLinkInstructionsTemplate" IS NOT NULL AND "triggerId" NOT IN (SELECT "id" FROM public."TaskTrigger" WHERE "triggerKey" IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer'));
UPDATE public."TaskSpawnSpec" SET "metadata" = pg_catalog.jsonb_build_object() WHERE "metadata" IS NOT NULL AND "triggerId" NOT IN (SELECT "id" FROM public."TaskTrigger" WHERE "triggerKey" IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer'));
UPDATE public."TaskCommunicationSpawnSpec" SET "subjectTemplate" = public.dummy_safe_text() WHERE "subjectTemplate" IS NOT NULL AND "triggerId" NOT IN (SELECT "id" FROM public."TaskTrigger" WHERE "triggerKey" IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer'));
UPDATE public."TaskCommunicationSpawnSpec" SET "bodyTextTemplate" = public.dummy_safe_text() WHERE "bodyTextTemplate" IS NOT NULL AND "triggerId" NOT IN (SELECT "id" FROM public."TaskTrigger" WHERE "triggerKey" IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer'));
UPDATE public."TaskCommunicationSpawnSpec" SET "bodyHtmlTemplate" = public.dummy_safe_text() WHERE "bodyHtmlTemplate" IS NOT NULL AND "triggerId" NOT IN (SELECT "id" FROM public."TaskTrigger" WHERE "triggerKey" IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer'));
UPDATE public."TaskCommunicationSpawnSpec" SET "commentTemplate" = public.dummy_safe_text() WHERE "commentTemplate" IS NOT NULL AND "triggerId" NOT IN (SELECT "id" FROM public."TaskTrigger" WHERE "triggerKey" IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer'));
UPDATE public."TaskCommunicationSpawnSpec" SET "emailScope" = NULL WHERE "emailScope" IS NOT NULL AND "triggerId" NOT IN (SELECT "id" FROM public."TaskTrigger" WHERE "triggerKey" IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer'));
UPDATE public."TaskCommunicationSpawnSpec" SET "dedupeKeyTemplate" = public.dummy_safe_text() WHERE "dedupeKeyTemplate" IS NOT NULL AND "triggerId" NOT IN (SELECT "id" FROM public."TaskTrigger" WHERE "triggerKey" IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer'));
UPDATE public."TaskCommunicationSpawnSpec" SET "metadata" = pg_catalog.jsonb_build_object() WHERE "metadata" IS NOT NULL AND "triggerId" NOT IN (SELECT "id" FROM public."TaskTrigger" WHERE "triggerKey" IN ('user-onboarding:treaty', 'referral:vote-invitation', 'treaty:signer-reminder', 'treaty:ratify', 'user-onboarding:treaty:hmt-gate', 'treaty:signer'));
UPDATE public."TaskTriggerFire" SET "idempotencyKey" = pg_catalog.concat('trigger-fire-', md5("id"::text)) WHERE "idempotencyKey" IS NOT NULL;
UPDATE public."TaskTriggerFire" SET "context" = pg_catalog.jsonb_build_object() WHERE "context" IS NOT NULL;
UPDATE public."TaskTriggerFire" SET "error" = public.dummy_safe_text() WHERE "error" IS NOT NULL;
UPDATE public."TaskTriggerFire" SET "spawnedTaskKeys" = ARRAY[]::text[] WHERE "spawnedTaskKeys" IS NOT NULL;
UPDATE public."TaskTriggerFire" SET "spawnedTaskIds" = ARRAY[]::text[] WHERE "spawnedTaskIds" IS NOT NULL;
UPDATE public."Form" SET "title" = public.dummy_safe_text();
UPDATE public."Form" SET "description" = public.dummy_safe_text() WHERE "description" IS NOT NULL;
UPDATE public."Form" SET "slug" = pg_catalog.concat('preview-form-', md5("id"::text)) WHERE "slug" IS NOT NULL;
UPDATE public."Form" SET "sourceUrl" = NULL WHERE "sourceUrl" IS NOT NULL;
UPDATE public."FormRevision" SET "title" = public.dummy_safe_text();
UPDATE public."FormRevision" SET "description" = public.dummy_safe_text() WHERE "description" IS NOT NULL;
UPDATE public."FormSection" SET "title" = public.dummy_safe_text() WHERE "title" IS NOT NULL;
UPDATE public."FormSection" SET "description" = public.dummy_safe_text() WHERE "description" IS NOT NULL;
UPDATE public."FormField" SET "prompt" = public.dummy_safe_text();
UPDATE public."FormField" SET "description" = public.dummy_safe_text() WHERE "description" IS NOT NULL;
UPDATE public."FormField" SET "optionsJson" = pg_catalog.jsonb_build_object() WHERE "optionsJson" IS NOT NULL;
UPDATE public."FormField" SET "validationJson" = pg_catalog.jsonb_build_object() WHERE "validationJson" IS NOT NULL;
UPDATE public."KnowledgeAnswer" SET "canonicalQuestion" = public.dummy_safe_text();
UPDATE public."KnowledgeAnswer" SET "knowledgeKey" = NULL WHERE "knowledgeKey" IS NOT NULL;
UPDATE public."KnowledgeAnswer" SET "contextTags" = ARRAY[]::text[] WHERE "contextTags" IS NOT NULL;
UPDATE public."FormResponse" SET "valueJson" = NULL WHERE "valueJson" IS NOT NULL;
UPDATE public."AgentTaskLease" SET "agentId" = pg_catalog.concat('agent-', md5("id"::text)) WHERE "agentId" IS NOT NULL;
UPDATE public."OAuthClient" SET "clientName" = public.dummy_safe_text() WHERE "clientName" IS NOT NULL;
UPDATE public."OAuthClient" SET "redirectUris" = ARRAY[]::text[] WHERE "redirectUris" IS NOT NULL;
UPDATE public."OAuthClient" SET "scope" = NULL WHERE "scope" IS NOT NULL;
UPDATE public."OAuthClient" SET "clientUri" = NULL WHERE "clientUri" IS NOT NULL;
UPDATE public."OAuthAuthCode" SET "code" = pg_catalog.concat('oauth-code-', md5("id"::text)) WHERE "code" IS NOT NULL;
-- redirectUri is NOT NULL in schema (required for OAuth flow), so mask with a
-- constant fake URL rather than NULL. Per-row uniqueness is not required —
-- column has no unique constraint.
UPDATE public."OAuthAuthCode" SET "redirectUri" = 'https://preview.invalid/callback' WHERE "redirectUri" IS NOT NULL;
UPDATE public."OAuthAuthCode" SET "codeChallenge" = pg_catalog.concat('oauth-challenge-', md5("id"::text)) WHERE "codeChallenge" IS NOT NULL;
UPDATE public."OAuthGrant" SET "refreshTokenHash" = pg_catalog.concat('oauth-refresh-', md5("id"::text)) WHERE "refreshTokenHash" IS NOT NULL;
UPDATE public."McpToolCallAudit" SET "agentId" = pg_catalog.concat('mcp-agent-', md5("id"::text)) WHERE "agentId" IS NOT NULL;
UPDATE public."McpToolCallAudit" SET "runId" = pg_catalog.concat('mcp-run-', md5("id"::text)) WHERE "runId" IS NOT NULL;
UPDATE public."McpToolCallAudit" SET "inputHash" = NULL WHERE "inputHash" IS NOT NULL;
UPDATE public."McpToolCallAudit" SET "inputSummaryJson" = pg_catalog.jsonb_build_object() WHERE "inputSummaryJson" IS NOT NULL;
UPDATE public."McpToolCallAudit" SET "outputSummaryJson" = pg_catalog.jsonb_build_object() WHERE "outputSummaryJson" IS NOT NULL;
UPDATE public."McpToolCallAudit" SET "errorSummary" = public.dummy_safe_text() WHERE "errorSummary" IS NOT NULL;
UPDATE public."ContentReport" SET "message" = public.dummy_safe_text() WHERE "message" IS NOT NULL;
UPDATE public."ContentReport" SET "correctionJson" = pg_catalog.jsonb_build_object() WHERE "correctionJson" IS NOT NULL;
UPDATE public."ContentReport" SET "sourceUrl" = NULL WHERE "sourceUrl" IS NOT NULL;
UPDATE public."ContentReport" SET "resolutionNote" = public.dummy_safe_text() WHERE "resolutionNote" IS NOT NULL;

COMMIT;
