/**
 * One-shot migration: hand Mike's personal tasks back to Mike.
 *
 * Background: tasks imported from Notion and the per-user onboarding tasks
 * generated by the trigger system were stamped with `wishonia@gmail.com` as
 * the creator because that account ran the import. The schema-rename from
 * `ownerUserId` → `createdByUserId` left those rows attached to the wrong
 * user, so the MCP `getMyQueue` (which filters by creator) can't find them
 * for `m@thinkbynumbers.org`.
 *
 *   pnpm --filter @optimitron/db db:reassign-personal-tasks            # dry-run
 *   pnpm --filter @optimitron/db db:reassign-personal-tasks --execute  # apply
 *
 * Buckets:
 *   1. Wishonia-created Notion imports that are unassigned or already
 *      assigned to Mike                              → set createdByUserId AND
 *                                                       assigneePersonId to Mike.
 *   2. `assigneePersonId = Mike.personId`       → set createdByUserId to Mike
 *      (the trigger-spawned onboarding tasks; assignee already correct).
 *   3. Playwright vote-flow residue titles      → delete (orphaned fixtures
 *                                                 the email-pattern cleanup
 *                                                 missed because the rows
 *                                                 had no `@example.test`
 *                                                 user attached).
 */

import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "./generated/prisma/client.js";
import { loadDatabaseUrl } from "./db-cli.js";

const MIKE_EMAIL = "m@thinkbynumbers.org";
const WISHONIA_EMAIL = "wishonia@gmail.com";
const SAMPLE_LIMIT = 8;

const PLAYWRIGHT_RESIDUE_TITLE_PATTERNS: readonly string[] = [
  "Invite % to vote on the 1% Treaty",
  "First: vote on the 1% Treaty%",
  "Second: vote on the 1% Treaty%",
  "Whats: vote on the 1% Treaty%",
  "Mike: vote on the 1% Treaty",
  "mike: vote on the 1% Treaty",
  "Jake: vote on the 1% Treaty",
];

interface CliOptions {
  execute: boolean;
  json: boolean;
}

export function parseArgs(argv: string[]): CliOptions {
  const normalized = argv[0] === "--" ? argv.slice(1) : argv;
  const options: CliOptions = { execute: false, json: false };
  for (const arg of normalized) {
    if (arg === "--execute") options.execute = true;
    else if (arg === "--json") options.json = true;
    else if (arg === "--help" || arg === "-h") {
      process.stdout.write(usage());
      process.exit(0);
    } else throw new Error(`Unknown argument: ${arg}`);
  }
  return options;
}

function usage(): string {
  return [
    "Usage: pnpm --filter @optimitron/db db:reassign-personal-tasks [--execute] [--json]",
    "",
    "  --execute  Apply the migration (default is dry-run).",
    "  --json     Emit machine-readable JSON instead of a report.",
    "",
  ].join("\n");
}

interface UserIdentity {
  userId: string;
  personId: string;
  displayName: string;
}

async function loadUserIdentity(
  prisma: PrismaClient,
  email: string,
): Promise<UserIdentity> {
  const rows = await prisma.$queryRaw<
    Array<{
      userId: string;
      personId: string | null;
      displayName: string | null;
    }>
  >`SELECT u.id AS "userId", u."personId", p."displayName"
    FROM "User" u
    LEFT JOIN "Person" p ON p.id = u."personId"
    WHERE u.email = ${email}`;
  const row = rows[0];
  if (!row) throw new Error(`User ${email} not found.`);
  if (!row.personId) throw new Error(`User ${email} has no Person record.`);
  return {
    userId: row.userId,
    personId: row.personId,
    displayName: row.displayName ?? email,
  };
}

async function loadMike(prisma: PrismaClient): Promise<UserIdentity> {
  return loadUserIdentity(prisma, MIKE_EMAIL);
}

async function loadWishonia(prisma: PrismaClient): Promise<UserIdentity> {
  return loadUserIdentity(prisma, WISHONIA_EMAIL);
}

interface SurveyCounts {
  notionTasks: number;
  onboardingTasks: number;
  playwrightResidue: number;
}

interface TaskSample {
  id: string;
  title: string;
  taskKey: string | null;
}

interface Survey {
  counts: SurveyCounts;
  samples: {
    notion: TaskSample[];
    onboarding: TaskSample[];
    residue: TaskSample[];
  };
}

async function survey(
  prisma: PrismaClient,
  mike: UserIdentity,
  wishonia: UserIdentity,
): Promise<Survey> {
  const notionClause = notionImportClause(1);
  const residueClause = playwrightResidueClause(1);
  const notionParams = [wishonia.userId, mike.personId];
  const residueParams = [wishonia.userId, ...PLAYWRIGHT_RESIDUE_TITLE_PATTERNS];
  const [
    notion,
    onboarding,
    residue,
    notionSample,
    onboardingSample,
    residueSample,
  ] = await Promise.all([
    countRows(
      prisma,
      `SELECT COUNT(*)::int AS n FROM "Task"
         WHERE ${notionClause}`,
      notionParams,
    ),
    countRows(
      prisma,
      `SELECT COUNT(*)::int AS n FROM "Task"
         WHERE "assigneePersonId" = $1
           AND ("createdByUserId" IS NULL OR "createdByUserId" <> $2)
           AND "deletedAt" IS NULL`,
      [mike.personId, mike.userId],
    ),
    countRows(
      prisma,
      `SELECT COUNT(*)::int AS n FROM "Task" WHERE ${residueClause}`,
      residueParams,
    ),
    sampleRows(
      prisma,
      `SELECT id, title, "taskKey" FROM "Task"
         WHERE ${notionClause}
         ORDER BY "createdAt" DESC LIMIT ${SAMPLE_LIMIT}`,
      notionParams,
    ),
    sampleRows(
      prisma,
      `SELECT id, title, "taskKey" FROM "Task"
         WHERE "assigneePersonId" = $1
           AND ("createdByUserId" IS NULL OR "createdByUserId" <> $2)
           AND "deletedAt" IS NULL
         ORDER BY "createdAt" DESC LIMIT ${SAMPLE_LIMIT}`,
      [mike.personId, mike.userId],
    ),
    sampleRows(
      prisma,
      `SELECT id, title, "taskKey" FROM "Task"
         WHERE ${residueClause}
         ORDER BY "createdAt" DESC LIMIT ${SAMPLE_LIMIT}`,
      residueParams,
    ),
  ]);
  return {
    counts: {
      notionTasks: notion,
      onboardingTasks: onboarding,
      playwrightResidue: residue,
    },
    samples: {
      notion: notionSample,
      onboarding: onboardingSample,
      residue: residueSample,
    },
  };
}

function notionImportClause(startIndex: number): string {
  const createdBy = `$${startIndex}`;
  const assignee = `$${startIndex + 1}`;
  return [
    `"taskKey" LIKE 'notion-import:%'`,
    `"createdByUserId" = ${createdBy}`,
    `("assigneePersonId" IS NULL OR "assigneePersonId" = ${assignee})`,
    `"deletedAt" IS NULL`,
  ].join(" AND ");
}

function playwrightResidueClause(startIndex: number): string {
  const createdBy = `$${startIndex}`;
  const ors = PLAYWRIGHT_RESIDUE_TITLE_PATTERNS.map(
    (_, i) => `title LIKE $${startIndex + i + 1}`,
  ).join(" OR ");
  return [
    `"deletedAt" IS NULL`,
    `"createdByUserId" = ${createdBy}`,
    `"taskKey" IS NULL`,
    `"assigneePersonId" IS NULL`,
    `(${ors})`,
  ].join(" AND ");
}

async function countRows(
  prisma: PrismaClient,
  sql: string,
  params: unknown[] = [],
): Promise<number> {
  const rows = await prisma.$queryRawUnsafe<Array<{ n: number }>>(
    sql,
    ...params,
  );
  return rows[0]?.n ?? 0;
}

async function sampleRows(
  prisma: PrismaClient,
  sql: string,
  params: unknown[] = [],
): Promise<TaskSample[]> {
  return prisma.$queryRawUnsafe<TaskSample[]>(sql, ...params);
}

async function applyMigration(
  prisma: PrismaClient,
  mike: UserIdentity,
  wishonia: UserIdentity,
): Promise<{
  notionUpdated: number;
  onboardingUpdated: number;
  residueDeleted: number;
}> {
  const notionClause = notionImportClause(3);
  const residueClause = playwrightResidueClause(1);
  return prisma.$transaction(async (tx) => {
    const notionUpdated = await tx.$executeRawUnsafe(
      `UPDATE "Task"
         SET "createdByUserId" = $1,
             "assigneePersonId" = $2,
             "updatedAt" = NOW()
       WHERE ${notionClause}`,
      mike.userId,
      mike.personId,
      wishonia.userId,
      mike.personId,
    );
    const onboardingUpdated = await tx.$executeRawUnsafe(
      `UPDATE "Task"
         SET "createdByUserId" = $1,
             "updatedAt" = NOW()
       WHERE "assigneePersonId" = $2
         AND ("createdByUserId" IS NULL OR "createdByUserId" <> $1)
         AND "deletedAt" IS NULL`,
      mike.userId,
      mike.personId,
    );
    const residueDeleted = await tx.$executeRawUnsafe(
      `DELETE FROM "Task" WHERE ${residueClause}`,
      wishonia.userId,
      ...PLAYWRIGHT_RESIDUE_TITLE_PATTERNS,
    );
    return { notionUpdated, onboardingUpdated, residueDeleted };
  });
}

function renderReport(
  s: Survey,
  mike: UserIdentity,
  executed: boolean,
): string {
  const lines: string[] = [];
  lines.push(
    executed
      ? "Personal-task migration — EXECUTED"
      : "Personal-task migration — DRY RUN",
  );
  lines.push(
    `Target: ${mike.displayName} (User ${mike.userId} / Person ${mike.personId})`,
  );
  lines.push("");
  lines.push(
    "Bucket A — Wishonia-created Notion imports assigned to Mike or unassigned",
  );
  lines.push(
    `  Will set createdByUserId AND assigneePersonId to Mike: ${s.counts.notionTasks}`,
  );
  for (const t of s.samples.notion) {
    lines.push(`    ${t.id}  ${truncate(t.title, 60)}`);
  }
  lines.push("");
  lines.push(
    "Bucket B — Tasks already assigned to Mike but with wrong createdByUserId",
  );
  lines.push(`  Will set createdByUserId to Mike: ${s.counts.onboardingTasks}`);
  for (const t of s.samples.onboarding) {
    lines.push(`    ${t.id}  ${truncate(t.title, 60)}`);
  }
  lines.push("");
  lines.push(
    "Bucket C — Playwright vote-flow residue (Wishonia-created orphaned fixtures)",
  );
  lines.push(`  Will be deleted: ${s.counts.playwrightResidue}`);
  for (const t of s.samples.residue) {
    lines.push(`    ${t.id}  ${truncate(t.title, 60)}`);
  }
  lines.push("");
  if (!executed) lines.push("Dry run only. Pass --execute to apply.");
  return `${lines.join("\n")}\n`;
}

function truncate(text: string, max: number): string {
  return text.length > max ? `${text.slice(0, max - 1)}…` : text;
}

export async function runReassign(argv: string[]): Promise<void> {
  const options = parseArgs(argv);
  const prisma = new PrismaClient({
    adapter: new PrismaPg({ connectionString: loadDatabaseUrl() }),
    log: ["error"],
  });
  try {
    const mike = await loadMike(prisma);
    const wishonia = await loadWishonia(prisma);
    const before = await survey(prisma, mike, wishonia);

    if (!options.execute) {
      process.stdout.write(
        options.json
          ? `${JSON.stringify({ executed: false, mike, ...before }, null, 2)}\n`
          : renderReport(before, mike, false),
      );
      return;
    }

    const result = await applyMigration(prisma, mike, wishonia);
    const after = await survey(prisma, mike, wishonia);

    if (options.json) {
      process.stdout.write(
        `${JSON.stringify(
          {
            executed: true,
            mike,
            applied: result,
            before: before.counts,
            after: after.counts,
          },
          null,
          2,
        )}\n`,
      );
    } else {
      const out: string[] = [];
      out.push(renderReport(before, mike, true));
      out.push("Applied");
      out.push(`  Notion tasks reassigned:    ${result.notionUpdated}`);
      out.push(`  Onboarding tasks updated:   ${result.onboardingUpdated}`);
      out.push(`  Residue tasks deleted:      ${result.residueDeleted}`);
      out.push("");
      out.push("Remaining matches");
      out.push(`  Notion (still wrong creator):   ${after.counts.notionTasks}`);
      out.push(
        `  Onboarding (still wrong):       ${after.counts.onboardingTasks}`,
      );
      out.push(
        `  Residue (still present):        ${after.counts.playwrightResidue}`,
      );
      process.stdout.write(`${out.join("\n")}\n`);
    }
  } finally {
    await prisma.$disconnect();
  }
}

const isDirectInvocation =
  typeof process.argv[1] === "string" &&
  process.argv[1].replace(/\\/g, "/").endsWith("/reassign-personal-tasks.ts");

if (isDirectInvocation) {
  runReassign(process.argv.slice(2)).catch((error: unknown) => {
    const message =
      error instanceof Error
        ? error.message
        : "Unknown reassign-personal-tasks error";
    process.stderr.write(`${message}\n`);
    process.exit(1);
  });
}
