/**
 * Pre-compute the median-income hydration map used by `government-report-cards.ts`.
 *
 * The 22,515-record `MEDIAN_INCOME_SERIES` dataset (~16 MB minified) was being
 * bundled into the browser because `government-report-cards.ts` imported the
 * helpers and ran a hydration loop at module-evaluation time. Webpack scope-
 * hoisting captures the constant in the helpers' lexical scope, so it cannot
 * be tree-shaken even when nothing in the client actually reads the raw rows.
 *
 * This script runs the hydration once, snapshots the per-country result into
 * `src/generated/median-income-hydration.ts`, and lets the runtime use that
 * tiny map (~50 entries × <200 bytes ≈ 10 kB) instead of the full dataset.
 *
 * Re-run when the underlying dataset updates:
 *   pnpm --filter @optimitron/data exec tsx scripts/generate-median-income-hydration.ts
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { getGovernmentIso3 } from "../src/datasets/government-code-map";
import {
  getBestAvailableMedianIncomeSeries,
  rankMedianIncomeRecord,
} from "../src/datasets/median-income-series";
import {
  GOVERNMENTS,
  type SourcedValue,
} from "../src/datasets/government-report-cards";

// Mirror the per-capita conversion ratios used by the original in-place
// hydration block. Kept here as the source of truth so the generated file is
// reproducible from this script alone.
const EQUIVALISED_TO_PER_CAPITA_RATIO: Record<string, number> = {
  USA: 0.68, GBR: 0.7, DEU: 0.73, FRA: 0.71, JPN: 0.7, AUS: 0.68, CAN: 0.69,
  KOR: 0.7, ISR: 0.65, TUR: 0.64, RUS: 0.68, CHN: 0.67, IND: 0.64, ITA: 0.7,
  ESP: 0.69, NLD: 0.71, SWE: 0.73, POL: 0.68, BEL: 0.7, AUT: 0.71, CZE: 0.7,
};
const DEFAULT_EQUIV_RATIO = 0.69;

const hydration: Record<string, SourcedValue> = {};

for (const gov of GOVERNMENTS) {
  const iso3 = getGovernmentIso3(gov.code);
  if (!iso3) continue;

  const records = getBestAvailableMedianIncomeSeries({
    jurisdictions: [iso3],
    purchasingPower: "ppp",
  });
  const gdpCap = gov.gdpPerCapita.value;
  const plausible = records.filter((r) => r.value > gdpCap * 0.05);
  const best =
    [...(plausible.length > 0 ? plausible : records)].sort((a, b) => {
      const rankDiff = rankMedianIncomeRecord(b) - rankMedianIncomeRecord(a);
      if (rankDiff !== 0) return rankDiff;
      return b.year - a.year;
    })[0] ?? null;
  if (!best) continue;

  const isEquivalised = best.unit.includes("equivalised");
  const ratio = isEquivalised
    ? EQUIVALISED_TO_PER_CAPITA_RATIO[iso3] ?? DEFAULT_EQUIV_RATIO
    : 1;
  const perCapitaValue = Math.round(best.value * ratio);
  const taxLabel = best.isAfterTax ? " (after-tax)" : "";
  const welfareLabel = best.welfareType === "consumption" ? " (consumption)" : "";

  hydration[iso3] = {
    value: perCapitaValue,
    source: `${best.source} ${best.year}${taxLabel}${welfareLabel} PPP per capita`,
    url: best.sourceUrl,
  };
}

const scriptDir = fileURLToPath(new URL(".", import.meta.url));
const outPath = resolve(scriptDir, "../src/generated/median-income-hydration.ts");

const content = `/**
 * Generated by scripts/generate-median-income-hydration.ts.
 * Do not edit manually.
 *
 * Pre-computed per-country median income, derived once at build time from the
 * full MEDIAN_INCOME_SERIES dataset so the runtime never has to load 22,515
 * raw records into the client bundle. Re-run the generator when the source
 * dataset updates.
 */

import type { SourcedValue } from '../datasets/government-report-cards';

export const MEDIAN_INCOME_HYDRATION: Record<string, SourcedValue> = ${JSON.stringify(hydration, null, 2)};
`;

writeFileSync(outPath, content, "utf8");
console.log(
  `Wrote ${Object.keys(hydration).length} country entries to ${outPath} (${content.length} bytes)`,
);
