"use client";

import { SlideBase } from "../slide-base";
import { AnimatedCounter } from "../../animations/animated-counter";
import { GlitchText } from "../../animations/glitch-text";
import { useEffect, useState } from "react";

export function SlideAIHackers() {
  const [robotCount, setRobotCount] = useState(1);
  const [phase, setPhase] = useState(0);

  useEffect(() => {
    // Exponential doubling
    const interval = setInterval(() => {
      setRobotCount((prev) => {
        if (prev >= 64) return 64;
        return prev * 2;
      });
      setPhase((prev) => prev + 1);
    }, 600);

    return () => clearInterval(interval);
  }, []);

  // Generate robot grid
  const robots = Array.from({ length: Math.min(robotCount, 64) });

  return (
    <SlideBase act={1} className="text-purple-500">
      {/* Title */}
      <div className="text-center mb-6">
        <GlitchText
          text="AI HACKERS ARE COMING"
          className="font-pixel text-lg md:text-2xl text-purple-400"
          intensity="medium"
        />
      </div>

      {/* Robot multiplication visualization */}
      <div className="relative w-full max-w-[1700px] aspect-video bg-black/50 border border-purple-500/30 rounded-lg overflow-hidden">
        {/* Grid of robots */}
        <div className="absolute inset-0 flex flex-wrap items-center justify-center content-center gap-1 p-4">
          {robots.map((_, i) => (
            <div
              key={i}
              className="text-xl md:text-3xl animate-pulse"
              style={{
                animationDelay: `${i * 50}ms`,
                opacity: 0.7 + Math.random() * 0.3,
              }}
            >
              🤖
            </div>
          ))}
        </div>

        {/* Exponential counter */}
        <div className="absolute top-4 right-4 font-pixel text-right">
          <div className="text-xs text-purple-300/60">AI AGENTS</div>
          <div className="text-2xl md:text-4xl text-purple-400">
            {robotCount.toLocaleString()}
          </div>
          <div className="text-xs text-purple-300/60">
            2^{Math.log2(robotCount).toFixed(0)}
          </div>
        </div>

        {/* Doubling indicator */}
        <div className="absolute bottom-4 left-4 right-4">
          <div className="font-pixel text-xs text-purple-300/60 mb-1">
            DOUBLING EVERY 6 MONTHS
          </div>
          <div className="flex gap-1">
            {Array.from({ length: 7 }).map((_, i) => (
              <div
                key={i}
                className={`h-2 flex-1 transition-all duration-300 ${
                  i < phase ? "bg-purple-500" : "bg-purple-900"
                }`}
              />
            ))}
          </div>
        </div>

        {/* Glitch overlay */}
        {phase > 3 && (
          <div className="absolute inset-0 bg-purple-500/10 animate-pulse pointer-events-none" />
        )}
      </div>

      {/* Warning text */}
      <div className="mt-6 space-y-2 text-center">
        <div className="font-pixel text-sm text-purple-400">
          <AnimatedCounter
            start={0}
            end={95}
            duration={4000}
            suffix="%"
          />
          {" "}of code will be AI-generated by 2027
        </div>
        <div className="font-terminal text-sm text-zinc-400">
          AI systems will find and exploit every vulnerability
        </div>
        {/* Recursive loop diagram */}
        <div className="font-pixel text-xs text-purple-400 mt-4 text-center">
          <div className="inline-block border border-purple-500/40 bg-black/50 px-4 py-3">
            <div className="flex items-center justify-center gap-1 flex-wrap">
              <span className="text-red-400">STEAL $$$</span>
              <span className="text-purple-300/60">&rarr;</span>
              <span className="text-amber-400">BUY COMPUTE</span>
              <span className="text-purple-300/60">&rarr;</span>
              <span className="text-purple-400">TRAIN MORE HACKERS</span>
              <span className="text-purple-300/60">&rarr; (loop)</span>
            </div>
            <div className="text-red-500 mt-2 animate-pulse">RECURSIVE EXPONENTIAL THEFT</div>
          </div>
        </div>
      </div>

      {/* Fractal recursion hint */}
      <div className="absolute top-4 left-4 opacity-20">
        <div className="font-pixel text-xs text-purple-400">
          {Array.from({ length: 5 }).map((_, i) => (
            <div key={i} style={{ paddingLeft: i * 8 }}>
              {">"} spawn(self)
            </div>
          ))}
        </div>
      </div>
    </SlideBase>
  );
}
