"use client";

import { SlideBase } from "../slide-base";
import { AnimatedCounter } from "../../animations/animated-counter";
import { GlitchText } from "../../animations/glitch-text";
import { useEffect, useState } from "react";

// Precompute exponential curve columns
const COLS = 36;
const MAX_COL_HEIGHT = 14; // max robots stacked in rightmost column
const ROBOT_SIZE = 32; // px per robot cell

// Each column's max robot count follows an exponential curve
const columnHeights = Array.from({ length: COLS }, (_, i) => {
  const t = i / (COLS - 1); // 0 to 1
  return Math.max(1, Math.round(1 + (MAX_COL_HEIGHT - 1) * (Math.pow(2, t * 4) - 1) / (Math.pow(2, 4) - 1)));
});
const TOTAL_ROBOTS = columnHeights.reduce((a, b) => a + b, 0);

// Build ordered list of positions: left-to-right, bottom-to-top within each column
const robotPositions: { col: number; row: number }[] = [];
for (let col = 0; col < COLS; col++) {
  for (let row = 0; row < columnHeights[col]; row++) {
    robotPositions.push({ col, row });
  }
}

export function SlideAIHackers() {
  const [visibleCount, setVisibleCount] = useState(0);
  const [phase, setPhase] = useState(0);
  const displayCount = Math.min(visibleCount, TOTAL_ROBOTS);
  // Map visible count to a power-of-2 display for the counter
  const robotCountDisplay = Math.min(64, Math.pow(2, Math.min(phase, 6)));

  useEffect(() => {
    // Phase counter (for doubling display and progress bar)
    const phaseInterval = setInterval(() => {
      setPhase((prev) => {
        if (prev >= 7) {
          clearInterval(phaseInterval);
          return 7;
        }
        return prev + 1;
      });
    }, 600);

    // Robots fill in rapidly
    const robotInterval = setInterval(() => {
      setVisibleCount((prev) => {
        if (prev >= TOTAL_ROBOTS) {
          clearInterval(robotInterval);
          return TOTAL_ROBOTS;
        }
        return prev + 4; // 4 robots per tick
      });
    }, 30);

    return () => {
      clearInterval(phaseInterval);
      clearInterval(robotInterval);
    };
  }, []);

  return (
    <SlideBase act={1} className="text-purple-500">
      {/* Title */}
      <div className="text-center mb-6">
        <GlitchText
          text="AI HACKERS ARE COMING"
          className="font-pixel text-2xl md:text-4xl text-purple-400"
          intensity="medium"
        />
      </div>

      {/* Robot multiplication visualization */}
      <div className="relative w-full max-w-[1700px] aspect-video bg-black/50 border border-purple-500/30 rounded-lg overflow-hidden">
        {/* Exponential curve of robots — piling up bottom-to-top, left-to-right */}
        <div className="absolute inset-0">
          {robotPositions.slice(0, displayCount).map((pos, i) => (
            <span
              key={i}
              className="absolute text-xl md:text-2xl"
              style={{
                left: `${(pos.col / COLS) * 100}%`,
                bottom: pos.row * ROBOT_SIZE,
                width: `${100 / COLS}%`,
                textAlign: "center",
                opacity: 0.6 + (pos.row / MAX_COL_HEIGHT) * 0.4,
              }}
            >
              🤖
            </span>
          ))}
        </div>

        {/* Exponential counter */}
        <div className="absolute top-4 right-4 font-pixel text-right">
          <div className="text-2xl text-purple-400">AI AGENTS</div>
          <div className="text-2xl md:text-4xl text-purple-400">
            {robotCountDisplay.toLocaleString()}
          </div>
          <div className="text-2xl text-purple-400">
            2^{Math.log2(robotCountDisplay).toFixed(0)}
          </div>
        </div>

        {/* Doubling indicator */}
        <div className="absolute bottom-4 left-4 right-4">
          <div className="font-pixel text-2xl text-purple-400 mb-1">
            DOUBLING EVERY 6 MONTHS
          </div>
          <div className="flex gap-1">
            {Array.from({ length: 7 }).map((_, i) => (
              <div
                key={i}
                className={`h-2 flex-1 transition-all duration-300 ${
                  i < phase ? "bg-purple-500" : "bg-purple-900"
                }`}
              />
            ))}
          </div>
        </div>

        {/* Glitch overlay */}
        {phase > 3 && (
          <div className="absolute inset-0 bg-purple-500/10 animate-pulse pointer-events-none" />
        )}
      </div>

      {/* Warning text */}
      <div className="mt-6 space-y-2 text-center">
        <div className="font-pixel text-2xl text-purple-400">
          <AnimatedCounter
            start={0}
            end={95}
            duration={4000}
            suffix="%"
          />
          {" "}of code will be AI-generated by 2027
        </div>
        <div className="font-terminal text-2xl text-zinc-200">
          AI systems will find and exploit every vulnerability
        </div>
        {/* Recursive loop diagram */}
        <div className="font-pixel text-xl text-purple-400 mt-4 text-center">
          <div className="inline-block border border-purple-500/40 bg-black/50 px-4 py-3">
            <div className="flex items-center justify-center gap-1 flex-wrap">
              <span className="text-red-400">STEAL $$$</span>
              <span className="text-purple-400">&rarr;</span>
              <span className="text-amber-400">BUY COMPUTE</span>
              <span className="text-purple-400">&rarr;</span>
              <span className="text-purple-400">TRAIN MORE HACKERS</span>
              <span className="text-purple-400">&rarr; (loop)</span>
            </div>
            <div className="text-red-500 mt-2 animate-pulse">RECURSIVE EXPONENTIAL THEFT</div>
          </div>
        </div>
      </div>

      {/* Fractal recursion hint */}
      <div className="absolute top-4 left-4 opacity-20">
        <div className="font-pixel text-xl text-purple-400">
          {Array.from({ length: 5 }).map((_, i) => (
            <div key={i} style={{ paddingLeft: i * 8 }}>
              {">"} spawn(self)
            </div>
          ))}
        </div>
      </div>
    </SlideBase>
  );
}
