import type { CSSProperties } from "react";

export const EMAIL_COLORS = {
  background: "#ffffff",
  foreground: "#111827",
  muted: "#71717a",
  line: "#111827",
  soft: "#f4f4f5",
  buttonText: "#ffffff",
} as const;

export const EMAIL_STYLES = {
  body: {
    margin: 0,
    padding: 0,
    background: EMAIL_COLORS.background,
    color: EMAIL_COLORS.foreground,
    fontFamily: "Arial, sans-serif",
  },
  container: {
    color: EMAIL_COLORS.foreground,
    fontFamily: "Arial, sans-serif",
    margin: "0 auto",
    maxWidth: "640px",
    padding: "32px 16px",
  },
  compactContainer: {
    color: EMAIL_COLORS.foreground,
    fontFamily: "Arial, sans-serif",
    margin: "0 auto",
    maxWidth: "560px",
    padding: "32px 16px",
  },
  eyebrow: {
    color: EMAIL_COLORS.muted,
    fontSize: "13px",
    fontWeight: 700,
    letterSpacing: "0.14em",
    lineHeight: 1.6,
    margin: "0 0 24px",
    textTransform: "uppercase",
  },
  smallEyebrow: {
    color: EMAIL_COLORS.muted,
    fontSize: "12px",
    fontWeight: 700,
    letterSpacing: "0.14em",
    lineHeight: 1.6,
    margin: "0 0 12px",
    textTransform: "uppercase",
  },
  headline: {
    fontSize: "24px",
    fontWeight: 900,
    lineHeight: 1.4,
    margin: "0 0 16px",
  },
  largeHeadline: {
    fontSize: "32px",
    fontWeight: 900,
    lineHeight: 1.1,
    margin: "0 0 16px",
  },
  paragraph: {
    fontSize: "16px",
    fontWeight: 700,
    lineHeight: 1.7,
    margin: "0 0 16px",
  },
  leadParagraph: {
    fontSize: "18px",
    fontWeight: 700,
    lineHeight: 1.7,
    margin: "0 0 24px",
  },
  mutedParagraph: {
    color: EMAIL_COLORS.muted,
    fontSize: "13px",
    lineHeight: 1.6,
    margin: "32px 0 0",
  },
  smallMutedParagraph: {
    color: EMAIL_COLORS.muted,
    fontSize: "14px",
    lineHeight: 1.6,
    margin: 0,
  },
  button: {
    background: EMAIL_COLORS.foreground,
    border: `2px solid ${EMAIL_COLORS.line}`,
    color: EMAIL_COLORS.buttonText,
    display: "inline-block",
    fontSize: "14px",
    fontWeight: 900,
    letterSpacing: "0.08em",
    padding: "16px 32px",
    textDecoration: "none",
    textTransform: "uppercase",
  },
  secondaryButton: {
    background: EMAIL_COLORS.background,
    border: `2px solid ${EMAIL_COLORS.line}`,
    color: EMAIL_COLORS.foreground,
    display: "inline-block",
    fontSize: "14px",
    fontWeight: 900,
    letterSpacing: "0.06em",
    margin: "0 0 8px 0",
    padding: "14px 24px",
    textDecoration: "none",
    textTransform: "uppercase",
  },
  primaryTaskButton: {
    background: EMAIL_COLORS.foreground,
    border: `2px solid ${EMAIL_COLORS.line}`,
    color: EMAIL_COLORS.buttonText,
    display: "inline-block",
    fontSize: "14px",
    fontWeight: 900,
    letterSpacing: "0.06em",
    margin: "0 8px 8px 0",
    padding: "14px 24px",
    textDecoration: "none",
    textTransform: "uppercase",
  },
  parameterLink: {
    color: EMAIL_COLORS.foreground,
    fontWeight: 700,
    textDecoration: "underline",
  },
  plainLink: {
    color: EMAIL_COLORS.foreground,
    fontWeight: 700,
    textDecoration: "underline",
  },
  divider: {
    borderTop: `2px solid ${EMAIL_COLORS.line}`,
    marginTop: "48px",
    paddingTop: "24px",
  },
} satisfies Record<string, CSSProperties>;
