export const WAR_ON_DISEASE_CANONICAL_DOMAIN = "warondisease.org";
export const WAR_ON_DISEASE_CANONICAL_ORIGIN = `https://${WAR_ON_DISEASE_CANONICAL_DOMAIN}`;
export const WAR_ON_DISEASE_UPDATES_DOMAIN = `updates.${WAR_ON_DISEASE_CANONICAL_DOMAIN}`;
export const WAR_ON_DISEASE_REPLY_DOMAIN = `reply.${WAR_ON_DISEASE_CANONICAL_DOMAIN}`;
