/**
 * Stripe Product and Price Configuration
 * Auto-generated by scripts/setup-stripe-products.ts. DO NOT HAND-EDIT:
 * rerun the script instead. All IDs belong to the account below, which the
 * script verified is registered as a nonprofit before writing this file.
 */

export const STRIPE_CONFIG = {
  accountId: "acct_1TPCJFD5epyB9qRx",
  products: {
    oneTime: "prod_V9rxMe7YKiRMwb",
    monthly: "prod_V9rxzfD6QRBmQH",
  },
  prices: {
    oneTime: {
      1: "price_1U9YDED5epyB9qRxLcZkbV0z",
      5: "price_1U9YDED5epyB9qRxRkwHvZt7",
      10: "price_1U9YDFD5epyB9qRxZDVsP5mp",
      25: "price_1U9YDGD5epyB9qRxyD5NDWP1",
      50: "price_1U9YDHD5epyB9qRxNxF7zsTk",
      100: "price_1U9YDID5epyB9qRxGk2LTJgG",
      250: "price_1U9YDJD5epyB9qRxH7cSfvKV",
      500: "price_1U9YDJD5epyB9qRxlIUf35yK",
      1000: "price_1U9YDKD5epyB9qRxagiSqP8P",
    },
    monthly: {
      1: "price_1U9YDMD5epyB9qRxSyHR4OtZ",
      5: "price_1U9YDMD5epyB9qRxEysqCao8",
      10: "price_1U9YDND5epyB9qRxEN3kqd4x",
      25: "price_1U9YDOD5epyB9qRxWdXnTmt9",
      50: "price_1U9YDPD5epyB9qRxHyrjN5zk",
      100: "price_1U9YDQD5epyB9qRxAKz9Fi06",
      250: "price_1U9YDRD5epyB9qRxKSFCYUdZ",
      500: "price_1U9YDSD5epyB9qRx0qZm9vOq",
      1000: "price_1U9YDTD5epyB9qRxlWknLgBs",
    },
  },
} as const

export const PRESET_AMOUNTS = [1, 5, 10, 25, 50, 100, 250, 500, 1000] as const

export type PresetAmount = (typeof PRESET_AMOUNTS)[number]
export type DonationType = "one-time" | "monthly"
