// Stripe Payment Links - Auto-generated by scripts/setup-stripe-products.ts
// These are direct links to Stripe-hosted checkout pages

export const PAYMENT_LINKS = {
  oneTime: {
    1: "https://buy.stripe.com/fZudR86im4Rl3ptffk0gw0d",
    5: "https://buy.stripe.com/3cI3cueOSerV7FJgjo0gw0e",
    10: "https://buy.stripe.com/4gM00i8qufvZ1hl7MS0gw0f",
    25: "https://buy.stripe.com/fZu8wOfSW1F97FJ4AG0gw0g",
    50: "https://buy.stripe.com/eVq6oG0Y2fvZ1hl3wC0gw0h",
    100: "https://buy.stripe.com/eVq6oG0Y2dnR3pt0kq0gw0i",
    250: "https://buy.stripe.com/fZu4gygX02Jd2lpgjo0gw0j",
    500: "https://buy.stripe.com/3cI4gy0Y2fvZbVZd7c0gw0k",
    1000: "https://buy.stripe.com/5kQ4gyayC0B5e47c380gw0l",
  },
  monthly: {
    1: "https://buy.stripe.com/fZu6oGcGK1F9gcfd7c0gw0m",
    5: "https://buy.stripe.com/aFafZgfSWdnR3pt3wC0gw0n",
    10: "https://buy.stripe.com/00w4gyayCerVbVZ9V00gw0o",
    25: "https://buy.stripe.com/3cI14meOS0B54txgjo0gw0p",
    50: "https://buy.stripe.com/fZu3cu2265VpaRVffk0gw0q",
    100: "https://buy.stripe.com/4gM9AS9uyabF7FJaZ40gw0r",
    250: "https://buy.stripe.com/aFa9ASdKOerVf8b9V00gw0s",
    500: "https://buy.stripe.com/eVq6oG5ei6Zt3ptaZ40gw0t",
    1000: "https://buy.stripe.com/4gM9AScGK4Rl5xB2sy0gw0u",
  },
} as const

export type PresetAmount = 1 | 5 | 10 | 25 | 50 | 100 | 250 | 500 | 1000
export type DonationType = "oneTime" | "monthly"

/**
 * Get the Payment Link URL for a preset amount
 */
export function getPaymentLink(
  amount: PresetAmount,
  type: DonationType,
  email?: string,
  name?: string
): string {
  const baseUrl = PAYMENT_LINKS[type][amount]

  if (!baseUrl) {
    throw new Error(`No payment link found for ${type} donation of $${amount}`)
  }

  // Add prefilled email and client reference ID
  const params = new URLSearchParams()
  if (email) {
    params.set("prefilled_email", email)
  }
  if (name) {
    params.set("client_reference_id", name)
  }

  return params.toString() ? `${baseUrl}?${params.toString()}` : baseUrl
}

/**
 * Check if an amount is a preset amount with a Payment Link
 */
export function isPresetAmount(amount: number): amount is PresetAmount {
  return [1, 5, 10, 25, 50, 100, 250, 500, 1000].includes(amount)
}
