/**
 * Stripe Product and Price Configuration
 * Generated by scripts/setup-stripe-products.ts
 */

export const STRIPE_CONFIG = {
  products: {
    oneTime: "prod_TMjc0VUCwfOyCF",
    monthly: "prod_TMjcUWXvJUzSC8",
  },
  prices: {
    oneTime: {
      25: "price_1SQ09DCEnp8SZ7rCaXkLiArN",
      50: "price_1SQ09ECEnp8SZ7rCwI8cxMQg",
      100: "price_1SQ09ECEnp8SZ7rCFsv1n6AN",
      250: "price_1SQ09ECEnp8SZ7rCyiLObgmH",
      500: "price_1SQ09FCEnp8SZ7rC042XOk6u",
      1000: "price_1SQ09FCEnp8SZ7rCPk20bOvz",
    },
    monthly: {
      25: "price_1SQ09FCEnp8SZ7rCunL57USB",
      50: "price_1SQ09GCEnp8SZ7rC3ObjsuAo",
      100: "price_1SQ09GCEnp8SZ7rC0dianDvI",
      250: "price_1SQ09GCEnp8SZ7rCwcTrMwD1",
      500: "price_1SQ09HCEnp8SZ7rCmUZsATnE",
      1000: "price_1SQ09HCEnp8SZ7rCg0ckriKe",
    },
  },
} as const

export const PRESET_AMOUNTS = [25, 50, 100, 250, 500, 1000] as const

export type PresetAmount = (typeof PRESET_AMOUNTS)[number]
export type DonationType = "one-time" | "monthly"
