// Auto-generated by generate-web-data.ts — do not edit manually.
// Regenerate with: pnpm --filter @optimitron/web run generate
import type { BudgetReportJSON } from "@optimitron/obg";

export const usBudgetAnalysis: BudgetReportJSON = {
  "jurisdiction": "United States",
  "totalSpendingNominal": 6707000000000,
  "categories": [
    {
      "id": "military",
      "name": "Military",
      "currentSpending": 886000000000,
      "currentSpendingRealPerCapita": 1995.59,
      "optimalSpendingPerCapita": null,
      "optimalSpendingNominal": null,
      "gap": 0,
      "gapPercent": 0,
      "recommendation": "comparison_only",
      "evidenceSource": "Descriptive national comparison: Military spending, Life Expectancy, 28 countries. No causal effect or federal allocation target estimated.",
      "outcomeMetrics": [
        {
          "name": "Global Peace Index ranking (US)",
          "value": 131,
          "trend": "declining"
        },
        {
          "name": "Military strength index (Global Firepower)",
          "value": 1,
          "trend": "stable"
        },
        {
          "name": "Active duty personnel",
          "value": 1.33,
          "trend": "declining"
        },
        {
          "name": "Military spending as % GDP",
          "value": 3,
          "trend": "stable"
        }
      ],
      "historicalRealPerCapita": [
        {
          "year": 2015,
          "nominalBillions": 596,
          "realPerCapita": 1921.69
        },
        {
          "year": 2016,
          "nominalBillions": 604,
          "realPerCapita": 1909.28
        },
        {
          "year": 2017,
          "nominalBillions": 610,
          "realPerCapita": 1876.07
        },
        {
          "year": 2018,
          "nominalBillions": 654,
          "realPerCapita": 1951.64
        },
        {
          "year": 2019,
          "nominalBillions": 686,
          "realPerCapita": 2002.75
        },
        {
          "year": 2020,
          "nominalBillions": 714,
          "realPerCapita": 2040.14
        },
        {
          "year": 2021,
          "nominalBillions": 742,
          "realPerCapita": 2021.04
        },
        {
          "year": 2022,
          "nominalBillions": 766,
          "realPerCapita": 1924.55
        },
        {
          "year": 2023,
          "nominalBillions": 806,
          "realPerCapita": 1930.21
        },
        {
          "year": 2024,
          "nominalBillions": 849,
          "realPerCapita": 1962.33
        },
        {
          "year": 2025,
          "nominalBillions": 886,
          "realPerCapita": 1995.59
        }
      ],
      "diminishingReturns": null,
      "efficiency": {
        "rank": 27,
        "totalCountries": 28,
        "spendingPerCapita": 2052,
        "outcome": 76.93,
        "outcomeName": "Life Expectancy",
        "bestCountry": {
          "code": "CHE",
          "name": "Switzerland",
          "spendingPerCapita": 389,
          "outcome": 83.37,
          "rank": 1
        },
        "topEfficient": [
          {
            "code": "CHE",
            "name": "Switzerland",
            "spendingPerCapita": 389,
            "outcome": 83.37,
            "rank": 1
          },
          {
            "code": "JPN",
            "name": "Japan",
            "spendingPerCapita": 400,
            "outcome": 84.53,
            "rank": 2
          },
          {
            "code": "SWE",
            "name": "Sweden",
            "spendingPerCapita": 565,
            "outcome": 82.9,
            "rank": 3
          }
        ],
        "floorSpendingPerCapita": 389,
        "floorOutcome": 83.37,
        "overspendRatio": 5.3,
        "potentialSavingsPerCapita": 1663,
        "potentialSavingsTotal": 563870000000
      },
      "oecdBenchmark": {
        "spendingField": "militarySpendingPerCapitaPpp",
        "fieldLabel": "Military spending",
        "scope": "category_specific",
        "lineShareOfField": 0.973,
        "comparisonYears": {
          "target": [
            2020,
            2021,
            2022
          ],
          "peer": [
            2020,
            2021,
            2022
          ]
        }
      }
    },
    {
      "id": "veterans_affairs",
      "name": "Veterans Affairs",
      "currentSpending": 325000000000,
      "currentSpendingRealPerCapita": 732.02,
      "optimalSpendingPerCapita": null,
      "optimalSpendingNominal": null,
      "gap": 0,
      "gapPercent": 0,
      "recommendation": "comparison_only",
      "evidenceSource": "Descriptive national comparison: Total health spending (public and private), Life Expectancy, 28 countries. No causal effect or federal allocation target estimated.",
      "outcomeMetrics": [
        {
          "name": "Veteran suicide rate",
          "value": 33.9,
          "trend": "stable"
        },
        {
          "name": "VA patient satisfaction (inpatient)",
          "value": 71,
          "trend": "improving"
        },
        {
          "name": "Veteran homelessness",
          "value": 35286,
          "trend": "improving"
        },
        {
          "name": "Average wait time for primary care",
          "value": 20.3,
          "trend": "improving"
        }
      ],
      "historicalRealPerCapita": [
        {
          "year": 2015,
          "nominalBillions": 161,
          "realPerCapita": 519.12
        },
        {
          "year": 2016,
          "nominalBillions": 167,
          "realPerCapita": 527.9
        },
        {
          "year": 2017,
          "nominalBillions": 176,
          "realPerCapita": 541.29
        },
        {
          "year": 2018,
          "nominalBillions": 189,
          "realPerCapita": 564.01
        },
        {
          "year": 2019,
          "nominalBillions": 200,
          "realPerCapita": 583.89
        },
        {
          "year": 2020,
          "nominalBillions": 218,
          "realPerCapita": 622.9
        },
        {
          "year": 2021,
          "nominalBillions": 234,
          "realPerCapita": 637.36
        },
        {
          "year": 2022,
          "nominalBillions": 267,
          "realPerCapita": 670.83
        },
        {
          "year": 2023,
          "nominalBillions": 302,
          "realPerCapita": 723.23
        },
        {
          "year": 2024,
          "nominalBillions": 314,
          "realPerCapita": 725.76
        },
        {
          "year": 2025,
          "nominalBillions": 325,
          "realPerCapita": 732.02
        }
      ],
      "diminishingReturns": null,
      "efficiency": {
        "rank": 28,
        "totalCountries": 28,
        "spendingPerCapita": 10333,
        "outcome": 76.93,
        "outcomeName": "Life Expectancy",
        "bestCountry": {
          "code": "KOR",
          "name": "South Korea",
          "spendingPerCapita": 3588,
          "outcome": 83.57,
          "rank": 1
        },
        "topEfficient": [
          {
            "code": "KOR",
            "name": "South Korea",
            "spendingPerCapita": 3588,
            "outcome": 83.57,
            "rank": 1
          },
          {
            "code": "JPN",
            "name": "Japan",
            "spendingPerCapita": 4095,
            "outcome": 84.53,
            "rank": 2
          },
          {
            "code": "AUS",
            "name": "Australia",
            "spendingPerCapita": 4544,
            "outcome": 83.1,
            "rank": 3
          }
        ],
        "floorSpendingPerCapita": 3588,
        "floorOutcome": 83.57,
        "overspendRatio": 2.9,
        "potentialSavingsPerCapita": 6745,
        "potentialSavingsTotal": 2286555000000
      },
      "oecdBenchmark": {
        "spendingField": "healthSpendingPerCapitaPpp",
        "fieldLabel": "Total health spending (public and private)",
        "scope": "national_field_proxy",
        "lineShareOfField": 0.071,
        "comparisonYears": {
          "target": [
            2020,
            2021,
            2022
          ],
          "peer": [
            2020,
            2021,
            2022
          ]
        }
      }
    },
    {
      "id": "transportation",
      "name": "Transportation",
      "currentSpending": 105000000000,
      "currentSpendingRealPerCapita": 236.5,
      "optimalSpendingPerCapita": null,
      "optimalSpendingNominal": null,
      "gap": 0,
      "gapPercent": 0,
      "recommendation": "comparison_only",
      "evidenceSource": "Descriptive national comparison: Public social spending (pensions, health, income support), Measured after-tax median disposable income (OECD real PPP, equivalised household), 16 countries. No causal effect or federal allocation target estimated.",
      "outcomeMetrics": [
        {
          "name": "Infrastructure grade (ASCE)",
          "value": 67,
          "trend": "improving"
        },
        {
          "name": "Traffic fatalities",
          "value": 40990,
          "trend": "declining"
        },
        {
          "name": "Traffic fatality rate",
          "value": 12.1,
          "trend": "declining"
        },
        {
          "name": "Structurally deficient bridges",
          "value": 42966,
          "trend": "improving"
        }
      ],
      "historicalRealPerCapita": [
        {
          "year": 2015,
          "nominalBillions": 86,
          "realPerCapita": 277.29
        },
        {
          "year": 2016,
          "nominalBillions": 89,
          "realPerCapita": 281.33
        },
        {
          "year": 2017,
          "nominalBillions": 87,
          "realPerCapita": 267.57
        },
        {
          "year": 2018,
          "nominalBillions": 88,
          "realPerCapita": 262.61
        },
        {
          "year": 2019,
          "nominalBillions": 92,
          "realPerCapita": 268.59
        },
        {
          "year": 2020,
          "nominalBillions": 100,
          "realPerCapita": 285.73
        },
        {
          "year": 2021,
          "nominalBillions": 95,
          "realPerCapita": 258.76
        },
        {
          "year": 2022,
          "nominalBillions": 97,
          "realPerCapita": 243.71
        },
        {
          "year": 2023,
          "nominalBillions": 101,
          "realPerCapita": 241.88
        },
        {
          "year": 2024,
          "nominalBillions": 103,
          "realPerCapita": 238.07
        },
        {
          "year": 2025,
          "nominalBillions": 105,
          "realPerCapita": 236.5
        }
      ],
      "diminishingReturns": null,
      "efficiency": {
        "rank": 4,
        "totalCountries": 16,
        "spendingPerCapita": 10268,
        "outcome": 37444.1,
        "outcomeName": "Measured after-tax median disposable income (OECD real PPP, equivalised household)",
        "bestCountry": {
          "code": "IRL",
          "name": "Ireland",
          "spendingPerCapita": 9709,
          "outcome": 32668.47,
          "rank": 1
        },
        "topEfficient": [
          {
            "code": "IRL",
            "name": "Ireland",
            "spendingPerCapita": 9709,
            "outcome": 32668.47,
            "rank": 1
          },
          {
            "code": "USA",
            "name": "United States",
            "spendingPerCapita": 10268,
            "outcome": 37444.1,
            "rank": 2
          },
          {
            "code": "NLD",
            "name": "Netherlands",
            "spendingPerCapita": 10605,
            "outcome": 34175.9,
            "rank": 3
          }
        ],
        "floorSpendingPerCapita": 9709,
        "floorOutcome": 32668.47,
        "overspendRatio": 1.1,
        "potentialSavingsPerCapita": 559,
        "potentialSavingsTotal": 189501000000
      },
      "oecdBenchmark": {
        "spendingField": "socialSpendingPerCapitaPpp",
        "fieldLabel": "Public social spending (pensions, health, income support)",
        "scope": "national_field_proxy",
        "lineShareOfField": 0.023,
        "comparisonYears": {
          "target": [
            2018
          ],
          "peer": [
            2020,
            2021,
            2022
          ]
        }
      }
    },
    {
      "id": "education",
      "name": "Education",
      "currentSpending": 102000000000,
      "currentSpendingRealPerCapita": 229.74,
      "optimalSpendingPerCapita": null,
      "optimalSpendingNominal": null,
      "gap": 0,
      "gapPercent": 0,
      "recommendation": "comparison_only",
      "evidenceSource": "Descriptive national comparison: Government education spending (all levels), PISA Math Score, 11 countries. No causal effect or federal allocation target estimated.",
      "outcomeMetrics": [
        {
          "name": "High school graduation rate",
          "value": 87,
          "trend": "stable"
        },
        {
          "name": "College enrollment rate (18-24)",
          "value": 38,
          "trend": "declining"
        },
        {
          "name": "PISA math score (US)",
          "value": 465,
          "trend": "declining"
        },
        {
          "name": "PISA reading score (US)",
          "value": 504,
          "trend": "declining"
        },
        {
          "name": "Student loan debt (total)",
          "value": 1740,
          "trend": "declining"
        }
      ],
      "historicalRealPerCapita": [
        {
          "year": 2015,
          "nominalBillions": 70,
          "realPerCapita": 225.7
        },
        {
          "year": 2016,
          "nominalBillions": 73,
          "realPerCapita": 230.76
        },
        {
          "year": 2017,
          "nominalBillions": 68,
          "realPerCapita": 209.14
        },
        {
          "year": 2018,
          "nominalBillions": 71,
          "realPerCapita": 211.87
        },
        {
          "year": 2019,
          "nominalBillions": 72,
          "realPerCapita": 210.2
        },
        {
          "year": 2020,
          "nominalBillions": 76,
          "realPerCapita": 217.16
        },
        {
          "year": 2021,
          "nominalBillions": 102,
          "realPerCapita": 277.83
        },
        {
          "year": 2022,
          "nominalBillions": 131,
          "realPerCapita": 329.13
        },
        {
          "year": 2023,
          "nominalBillions": 119,
          "realPerCapita": 284.98
        },
        {
          "year": 2024,
          "nominalBillions": 108,
          "realPerCapita": 249.62
        },
        {
          "year": 2025,
          "nominalBillions": 102,
          "realPerCapita": 229.74
        }
      ],
      "diminishingReturns": null,
      "efficiency": {
        "rank": 11,
        "totalCountries": 11,
        "spendingPerCapita": 2996,
        "outcome": 465,
        "outcomeName": "PISA Math Score",
        "bestCountry": {
          "code": "JPN",
          "name": "Japan",
          "spendingPerCapita": 1288,
          "outcome": 536,
          "rank": 1
        },
        "topEfficient": [
          {
            "code": "JPN",
            "name": "Japan",
            "spendingPerCapita": 1288,
            "outcome": 536,
            "rank": 1
          },
          {
            "code": "TWN",
            "name": "Taiwan",
            "spendingPerCapita": 1367,
            "outcome": 544.33,
            "rank": 2
          },
          {
            "code": "SGP",
            "name": "Singapore",
            "spendingPerCapita": 2509,
            "outcome": 569.33,
            "rank": 3
          }
        ],
        "floorSpendingPerCapita": 1288,
        "floorOutcome": 536,
        "overspendRatio": 2.3,
        "potentialSavingsPerCapita": 1708,
        "potentialSavingsTotal": 579012000000
      },
      "oecdBenchmark": {
        "spendingField": "educationSpendingPerCapitaPpp",
        "fieldLabel": "Government education spending (all levels)",
        "scope": "national_field_proxy",
        "lineShareOfField": 0.077,
        "comparisonYears": {
          "target": [
            2022
          ],
          "peer": [
            2022
          ]
        }
      }
    },
    {
      "id": "health_discretionary",
      "name": "Health (non-Medicare/Medicaid)",
      "currentSpending": 94000000000,
      "currentSpendingRealPerCapita": 211.72,
      "optimalSpendingPerCapita": null,
      "optimalSpendingNominal": null,
      "gap": 0,
      "gapPercent": 0,
      "recommendation": "comparison_only",
      "evidenceSource": "Descriptive national comparison: Total health spending (public and private), Life Expectancy, 28 countries. No causal effect or federal allocation target estimated.",
      "outcomeMetrics": [
        {
          "name": "Life expectancy at birth",
          "value": 77.5,
          "trend": "improving"
        },
        {
          "name": "Opioid overdose deaths",
          "value": 81083,
          "trend": "improving"
        },
        {
          "name": "NIH-funded clinical trials",
          "value": 13500,
          "trend": "improving"
        }
      ],
      "historicalRealPerCapita": [
        {
          "year": 2015,
          "nominalBillions": 66,
          "realPerCapita": 212.8
        },
        {
          "year": 2016,
          "nominalBillions": 67,
          "realPerCapita": 211.79
        },
        {
          "year": 2017,
          "nominalBillions": 65,
          "realPerCapita": 199.91
        },
        {
          "year": 2018,
          "nominalBillions": 71,
          "realPerCapita": 211.87
        },
        {
          "year": 2019,
          "nominalBillions": 75,
          "realPerCapita": 218.96
        },
        {
          "year": 2020,
          "nominalBillions": 122,
          "realPerCapita": 348.6
        },
        {
          "year": 2021,
          "nominalBillions": 190,
          "realPerCapita": 517.52
        },
        {
          "year": 2022,
          "nominalBillions": 127,
          "realPerCapita": 319.08
        },
        {
          "year": 2023,
          "nominalBillions": 102,
          "realPerCapita": 244.27
        },
        {
          "year": 2024,
          "nominalBillions": 97,
          "realPerCapita": 224.2
        },
        {
          "year": 2025,
          "nominalBillions": 94,
          "realPerCapita": 211.72
        }
      ],
      "diminishingReturns": null,
      "efficiency": {
        "rank": 28,
        "totalCountries": 28,
        "spendingPerCapita": 10333,
        "outcome": 76.93,
        "outcomeName": "Life Expectancy",
        "bestCountry": {
          "code": "KOR",
          "name": "South Korea",
          "spendingPerCapita": 3588,
          "outcome": 83.57,
          "rank": 1
        },
        "topEfficient": [
          {
            "code": "KOR",
            "name": "South Korea",
            "spendingPerCapita": 3588,
            "outcome": 83.57,
            "rank": 1
          },
          {
            "code": "JPN",
            "name": "Japan",
            "spendingPerCapita": 4095,
            "outcome": 84.53,
            "rank": 2
          },
          {
            "code": "AUS",
            "name": "Australia",
            "spendingPerCapita": 4544,
            "outcome": 83.1,
            "rank": 3
          }
        ],
        "floorSpendingPerCapita": 3588,
        "floorOutcome": 83.57,
        "overspendRatio": 2.9,
        "potentialSavingsPerCapita": 6745,
        "potentialSavingsTotal": 2286555000000
      },
      "oecdBenchmark": {
        "spendingField": "healthSpendingPerCapitaPpp",
        "fieldLabel": "Total health spending (public and private)",
        "scope": "national_field_proxy",
        "lineShareOfField": 0.02,
        "comparisonYears": {
          "target": [
            2020,
            2021,
            2022
          ],
          "peer": [
            2020,
            2021,
            2022
          ]
        }
      }
    },
    {
      "id": "housing",
      "name": "HUD / Housing",
      "currentSpending": 73000000000,
      "currentSpendingRealPerCapita": 164.42,
      "optimalSpendingPerCapita": null,
      "optimalSpendingNominal": null,
      "gap": 0,
      "gapPercent": 0,
      "recommendation": "comparison_only",
      "evidenceSource": "Descriptive national comparison: Public social spending (pensions, health, income support), Measured after-tax median disposable income (OECD real PPP, equivalised household), 16 countries. No causal effect or federal allocation target estimated.",
      "outcomeMetrics": [
        {
          "name": "Total homeless population",
          "value": 653104,
          "trend": "declining"
        },
        {
          "name": "Housing cost burden (>30% income)",
          "value": 30,
          "trend": "declining"
        },
        {
          "name": "Homeownership rate",
          "value": 65.6,
          "trend": "stable"
        }
      ],
      "historicalRealPerCapita": [
        {
          "year": 2015,
          "nominalBillions": 37,
          "realPerCapita": 119.3
        },
        {
          "year": 2016,
          "nominalBillions": 39,
          "realPerCapita": 123.28
        },
        {
          "year": 2017,
          "nominalBillions": 39,
          "realPerCapita": 119.95
        },
        {
          "year": 2018,
          "nominalBillions": 41,
          "realPerCapita": 122.35
        },
        {
          "year": 2019,
          "nominalBillions": 44,
          "realPerCapita": 128.46
        },
        {
          "year": 2020,
          "nominalBillions": 56,
          "realPerCapita": 160.01
        },
        {
          "year": 2021,
          "nominalBillions": 63,
          "realPerCapita": 171.6
        },
        {
          "year": 2022,
          "nominalBillions": 60,
          "realPerCapita": 150.75
        },
        {
          "year": 2023,
          "nominalBillions": 68,
          "realPerCapita": 162.85
        },
        {
          "year": 2024,
          "nominalBillions": 71,
          "realPerCapita": 164.1
        },
        {
          "year": 2025,
          "nominalBillions": 73,
          "realPerCapita": 164.42
        }
      ],
      "diminishingReturns": null,
      "efficiency": {
        "rank": 4,
        "totalCountries": 16,
        "spendingPerCapita": 10268,
        "outcome": 37444.1,
        "outcomeName": "Measured after-tax median disposable income (OECD real PPP, equivalised household)",
        "bestCountry": {
          "code": "IRL",
          "name": "Ireland",
          "spendingPerCapita": 9709,
          "outcome": 32668.47,
          "rank": 1
        },
        "topEfficient": [
          {
            "code": "IRL",
            "name": "Ireland",
            "spendingPerCapita": 9709,
            "outcome": 32668.47,
            "rank": 1
          },
          {
            "code": "USA",
            "name": "United States",
            "spendingPerCapita": 10268,
            "outcome": 37444.1,
            "rank": 2
          },
          {
            "code": "NLD",
            "name": "Netherlands",
            "spendingPerCapita": 10605,
            "outcome": 34175.9,
            "rank": 3
          }
        ],
        "floorSpendingPerCapita": 9709,
        "floorOutcome": 32668.47,
        "overspendRatio": 1.1,
        "potentialSavingsPerCapita": 559,
        "potentialSavingsTotal": 189501000000
      },
      "oecdBenchmark": {
        "spendingField": "socialSpendingPerCapitaPpp",
        "fieldLabel": "Public social spending (pensions, health, income support)",
        "scope": "national_field_proxy",
        "lineShareOfField": 0.016,
        "comparisonYears": {
          "target": [
            2018
          ],
          "peer": [
            2020,
            2021,
            2022
          ]
        }
      }
    },
    {
      "id": "foreign_aid",
      "name": "Foreign Aid / International Affairs",
      "currentSpending": 63000000000,
      "currentSpendingRealPerCapita": 141.9,
      "optimalSpendingPerCapita": null,
      "optimalSpendingNominal": null,
      "gap": 0,
      "gapPercent": 0,
      "recommendation": "comparison_only",
      "evidenceSource": "Descriptive national comparison: Public social spending (pensions, health, income support), Measured after-tax median disposable income (OECD real PPP, equivalised household), 16 countries. No causal effect or federal allocation target estimated.",
      "outcomeMetrics": [
        {
          "name": "Foreign aid as % GNI",
          "value": 0.22,
          "trend": "stable"
        },
        {
          "name": "PEPFAR lives saved (cumulative)",
          "value": 25,
          "trend": "improving"
        },
        {
          "name": "Countries receiving US bilateral aid",
          "value": 140,
          "trend": "stable"
        }
      ],
      "historicalRealPerCapita": [
        {
          "year": 2015,
          "nominalBillions": 46,
          "realPerCapita": 148.32
        },
        {
          "year": 2016,
          "nominalBillions": 46,
          "realPerCapita": 145.41
        },
        {
          "year": 2017,
          "nominalBillions": 47,
          "realPerCapita": 144.55
        },
        {
          "year": 2018,
          "nominalBillions": 49,
          "realPerCapita": 146.22
        },
        {
          "year": 2019,
          "nominalBillions": 52,
          "realPerCapita": 151.81
        },
        {
          "year": 2020,
          "nominalBillions": 51,
          "realPerCapita": 145.72
        },
        {
          "year": 2021,
          "nominalBillions": 55,
          "realPerCapita": 149.81
        },
        {
          "year": 2022,
          "nominalBillions": 66,
          "realPerCapita": 165.82
        },
        {
          "year": 2023,
          "nominalBillions": 73,
          "realPerCapita": 174.82
        },
        {
          "year": 2024,
          "nominalBillions": 67,
          "realPerCapita": 154.86
        },
        {
          "year": 2025,
          "nominalBillions": 63,
          "realPerCapita": 141.9
        }
      ],
      "diminishingReturns": null,
      "efficiency": {
        "rank": 4,
        "totalCountries": 16,
        "spendingPerCapita": 10268,
        "outcome": 37444.1,
        "outcomeName": "Measured after-tax median disposable income (OECD real PPP, equivalised household)",
        "bestCountry": {
          "code": "IRL",
          "name": "Ireland",
          "spendingPerCapita": 9709,
          "outcome": 32668.47,
          "rank": 1
        },
        "topEfficient": [
          {
            "code": "IRL",
            "name": "Ireland",
            "spendingPerCapita": 9709,
            "outcome": 32668.47,
            "rank": 1
          },
          {
            "code": "USA",
            "name": "United States",
            "spendingPerCapita": 10268,
            "outcome": 37444.1,
            "rank": 2
          },
          {
            "code": "NLD",
            "name": "Netherlands",
            "spendingPerCapita": 10605,
            "outcome": 34175.9,
            "rank": 3
          }
        ],
        "floorSpendingPerCapita": 9709,
        "floorOutcome": 32668.47,
        "overspendRatio": 1.1,
        "potentialSavingsPerCapita": 559,
        "potentialSavingsTotal": 189501000000
      },
      "oecdBenchmark": {
        "spendingField": "socialSpendingPerCapitaPpp",
        "fieldLabel": "Public social spending (pensions, health, income support)",
        "scope": "national_field_proxy",
        "lineShareOfField": 0.014,
        "comparisonYears": {
          "target": [
            2018
          ],
          "peer": [
            2020,
            2021,
            2022
          ]
        }
      }
    },
    {
      "id": "homeland_security",
      "name": "Homeland Security",
      "currentSpending": 62000000000,
      "currentSpendingRealPerCapita": 139.65,
      "optimalSpendingPerCapita": null,
      "optimalSpendingNominal": null,
      "gap": 0,
      "gapPercent": 0,
      "recommendation": "comparison_only",
      "evidenceSource": "Descriptive national comparison: Military spending, Life Expectancy, 28 countries. No causal effect or federal allocation target estimated.",
      "outcomeMetrics": [
        {
          "name": "Southwest border encounters",
          "value": 2048000,
          "trend": "declining"
        },
        {
          "name": "Domestic terrorism incidents",
          "value": 38,
          "trend": "improving"
        },
        {
          "name": "Disaster relief obligated (FEMA)",
          "value": 34.2,
          "trend": "declining"
        }
      ],
      "historicalRealPerCapita": [
        {
          "year": 2015,
          "nominalBillions": 39,
          "realPerCapita": 125.75
        },
        {
          "year": 2016,
          "nominalBillions": 41,
          "realPerCapita": 129.6
        },
        {
          "year": 2017,
          "nominalBillions": 42,
          "realPerCapita": 129.17
        },
        {
          "year": 2018,
          "nominalBillions": 46,
          "realPerCapita": 137.27
        },
        {
          "year": 2019,
          "nominalBillions": 51,
          "realPerCapita": 148.89
        },
        {
          "year": 2020,
          "nominalBillions": 52,
          "realPerCapita": 148.58
        },
        {
          "year": 2021,
          "nominalBillions": 55,
          "realPerCapita": 149.81
        },
        {
          "year": 2022,
          "nominalBillions": 54,
          "realPerCapita": 135.67
        },
        {
          "year": 2023,
          "nominalBillions": 57,
          "realPerCapita": 136.5
        },
        {
          "year": 2024,
          "nominalBillions": 60,
          "realPerCapita": 138.68
        },
        {
          "year": 2025,
          "nominalBillions": 62,
          "realPerCapita": 139.65
        }
      ],
      "diminishingReturns": null,
      "efficiency": {
        "rank": 27,
        "totalCountries": 28,
        "spendingPerCapita": 2052,
        "outcome": 76.93,
        "outcomeName": "Life Expectancy",
        "bestCountry": {
          "code": "CHE",
          "name": "Switzerland",
          "spendingPerCapita": 389,
          "outcome": 83.37,
          "rank": 1
        },
        "topEfficient": [
          {
            "code": "CHE",
            "name": "Switzerland",
            "spendingPerCapita": 389,
            "outcome": 83.37,
            "rank": 1
          },
          {
            "code": "JPN",
            "name": "Japan",
            "spendingPerCapita": 400,
            "outcome": 84.53,
            "rank": 2
          },
          {
            "code": "SWE",
            "name": "Sweden",
            "spendingPerCapita": 565,
            "outcome": 82.9,
            "rank": 3
          }
        ],
        "floorSpendingPerCapita": 389,
        "floorOutcome": 83.37,
        "overspendRatio": 5.3,
        "potentialSavingsPerCapita": 1663,
        "potentialSavingsTotal": 563870000000
      },
      "oecdBenchmark": {
        "spendingField": "militarySpendingPerCapitaPpp",
        "fieldLabel": "Military spending",
        "scope": "national_field_proxy",
        "lineShareOfField": 0.068,
        "comparisonYears": {
          "target": [
            2020,
            2021,
            2022
          ],
          "peer": [
            2020,
            2021,
            2022
          ]
        }
      }
    },
    {
      "id": "energy",
      "name": "Energy",
      "currentSpending": 52000000000,
      "currentSpendingRealPerCapita": 117.12,
      "optimalSpendingPerCapita": null,
      "optimalSpendingNominal": null,
      "gap": 0,
      "gapPercent": 0,
      "recommendation": "comparison_only",
      "evidenceSource": "Descriptive national comparison: Total R&D spending (business and government), Measured after-tax median disposable income (OECD real PPP, equivalised household), 16 countries. No causal effect or federal allocation target estimated.",
      "outcomeMetrics": [
        {
          "name": "Renewable energy share of electricity",
          "value": 22.7,
          "trend": "improving"
        },
        {
          "name": "Energy-related CO₂ emissions",
          "value": 4790,
          "trend": "improving"
        },
        {
          "name": "Average retail electricity price",
          "value": 12.7,
          "trend": "declining"
        }
      ],
      "historicalRealPerCapita": [
        {
          "year": 2015,
          "nominalBillions": 29,
          "realPerCapita": 93.51
        },
        {
          "year": 2016,
          "nominalBillions": 32,
          "realPerCapita": 101.15
        },
        {
          "year": 2017,
          "nominalBillions": 30,
          "realPerCapita": 92.27
        },
        {
          "year": 2018,
          "nominalBillions": 31,
          "realPerCapita": 92.51
        },
        {
          "year": 2019,
          "nominalBillions": 35,
          "realPerCapita": 102.18
        },
        {
          "year": 2020,
          "nominalBillions": 38,
          "realPerCapita": 108.58
        },
        {
          "year": 2021,
          "nominalBillions": 42,
          "realPerCapita": 114.4
        },
        {
          "year": 2022,
          "nominalBillions": 44,
          "realPerCapita": 110.55
        },
        {
          "year": 2023,
          "nominalBillions": 47,
          "realPerCapita": 112.56
        },
        {
          "year": 2024,
          "nominalBillions": 50,
          "realPerCapita": 115.57
        },
        {
          "year": 2025,
          "nominalBillions": 52,
          "realPerCapita": 117.12
        }
      ],
      "diminishingReturns": null,
      "efficiency": {
        "rank": 10,
        "totalCountries": 16,
        "spendingPerCapita": 1576,
        "outcome": 37444.1,
        "outcomeName": "Measured after-tax median disposable income (OECD real PPP, equivalised household)",
        "bestCountry": {
          "code": "IRL",
          "name": "Ireland",
          "spendingPerCapita": 859,
          "outcome": 32668.47,
          "rank": 1
        },
        "topEfficient": [
          {
            "code": "IRL",
            "name": "Ireland",
            "spendingPerCapita": 859,
            "outcome": 32668.47,
            "rank": 1
          },
          {
            "code": "NLD",
            "name": "Netherlands",
            "spendingPerCapita": 1064,
            "outcome": 34175.9,
            "rank": 2
          },
          {
            "code": "BEL",
            "name": "Belgium",
            "spendingPerCapita": 1293,
            "outcome": 32250.32,
            "rank": 3
          }
        ],
        "floorSpendingPerCapita": 859,
        "floorOutcome": 32668.47,
        "overspendRatio": 1.8,
        "potentialSavingsPerCapita": 717,
        "potentialSavingsTotal": 243063000000
      },
      "oecdBenchmark": {
        "spendingField": "rdSpendingPerCapitaPpp",
        "fieldLabel": "Total R&D spending (business and government)",
        "scope": "national_field_proxy",
        "lineShareOfField": 0.074,
        "comparisonYears": {
          "target": [
            2018
          ],
          "peer": [
            2020,
            2021,
            2022
          ]
        }
      }
    },
    {
      "id": "science_nasa",
      "name": "Science / NASA",
      "currentSpending": 44000000000,
      "currentSpendingRealPerCapita": 99.1,
      "optimalSpendingPerCapita": null,
      "optimalSpendingNominal": null,
      "gap": 0,
      "gapPercent": 0,
      "recommendation": "comparison_only",
      "evidenceSource": "Descriptive national comparison: Total R&D spending (business and government), Measured after-tax median disposable income (OECD real PPP, equivalised household), 16 countries. No causal effect or federal allocation target estimated.",
      "outcomeMetrics": [
        {
          "name": "R&D as % of GDP (federal)",
          "value": 0.67,
          "trend": "stable"
        },
        {
          "name": "US patents granted",
          "value": 352013,
          "trend": "stable"
        },
        {
          "name": "Nobel Prizes in science (cumulative, US-affiliated)",
          "value": 285,
          "trend": "improving"
        },
        {
          "name": "NASA commercial crew missions",
          "value": 12,
          "trend": "improving"
        }
      ],
      "historicalRealPerCapita": [
        {
          "year": 2015,
          "nominalBillions": 30,
          "realPerCapita": 96.73
        },
        {
          "year": 2016,
          "nominalBillions": 31,
          "realPerCapita": 97.99
        },
        {
          "year": 2017,
          "nominalBillions": 31,
          "realPerCapita": 95.34
        },
        {
          "year": 2018,
          "nominalBillions": 32,
          "realPerCapita": 95.49
        },
        {
          "year": 2019,
          "nominalBillions": 33,
          "realPerCapita": 96.34
        },
        {
          "year": 2020,
          "nominalBillions": 35,
          "realPerCapita": 100.01
        },
        {
          "year": 2021,
          "nominalBillions": 37,
          "realPerCapita": 100.78
        },
        {
          "year": 2022,
          "nominalBillions": 40,
          "realPerCapita": 100.5
        },
        {
          "year": 2023,
          "nominalBillions": 42,
          "realPerCapita": 100.58
        },
        {
          "year": 2024,
          "nominalBillions": 43,
          "realPerCapita": 99.39
        },
        {
          "year": 2025,
          "nominalBillions": 44,
          "realPerCapita": 99.1
        }
      ],
      "diminishingReturns": null,
      "efficiency": {
        "rank": 10,
        "totalCountries": 16,
        "spendingPerCapita": 1576,
        "outcome": 37444.1,
        "outcomeName": "Measured after-tax median disposable income (OECD real PPP, equivalised household)",
        "bestCountry": {
          "code": "IRL",
          "name": "Ireland",
          "spendingPerCapita": 859,
          "outcome": 32668.47,
          "rank": 1
        },
        "topEfficient": [
          {
            "code": "IRL",
            "name": "Ireland",
            "spendingPerCapita": 859,
            "outcome": 32668.47,
            "rank": 1
          },
          {
            "code": "NLD",
            "name": "Netherlands",
            "spendingPerCapita": 1064,
            "outcome": 34175.9,
            "rank": 2
          },
          {
            "code": "BEL",
            "name": "Belgium",
            "spendingPerCapita": 1293,
            "outcome": 32250.32,
            "rank": 3
          }
        ],
        "floorSpendingPerCapita": 859,
        "floorOutcome": 32668.47,
        "overspendRatio": 1.8,
        "potentialSavingsPerCapita": 717,
        "potentialSavingsTotal": 243063000000
      },
      "oecdBenchmark": {
        "spendingField": "rdSpendingPerCapitaPpp",
        "fieldLabel": "Total R&D spending (business and government)",
        "scope": "national_field_proxy",
        "lineShareOfField": 0.063,
        "comparisonYears": {
          "target": [
            2018
          ],
          "peer": [
            2020,
            2021,
            2022
          ]
        }
      }
    },
    {
      "id": "labor",
      "name": "Labor",
      "currentSpending": 42000000000,
      "currentSpendingRealPerCapita": 94.6,
      "optimalSpendingPerCapita": null,
      "optimalSpendingNominal": null,
      "gap": 0,
      "gapPercent": 0,
      "recommendation": "comparison_only",
      "evidenceSource": "Descriptive national comparison: Public social spending (pensions, health, income support), Measured after-tax median disposable income (OECD real PPP, equivalised household), 16 countries. No causal effect or federal allocation target estimated.",
      "outcomeMetrics": [
        {
          "name": "Labor force participation rate",
          "value": 62.5,
          "trend": "stable"
        },
        {
          "name": "Median weekly earnings",
          "value": 1145,
          "trend": "improving"
        },
        {
          "name": "Workplace fatalities",
          "value": 5283,
          "trend": "stable"
        }
      ],
      "historicalRealPerCapita": [
        {
          "year": 2015,
          "nominalBillions": 43,
          "realPerCapita": 138.65
        },
        {
          "year": 2016,
          "nominalBillions": 40,
          "realPerCapita": 126.44
        },
        {
          "year": 2017,
          "nominalBillions": 38,
          "realPerCapita": 116.87
        },
        {
          "year": 2018,
          "nominalBillions": 37,
          "realPerCapita": 110.41
        },
        {
          "year": 2019,
          "nominalBillions": 38,
          "realPerCapita": 110.94
        },
        {
          "year": 2020,
          "nominalBillions": 64,
          "realPerCapita": 182.87
        },
        {
          "year": 2021,
          "nominalBillions": 47,
          "realPerCapita": 128.02
        },
        {
          "year": 2022,
          "nominalBillions": 46,
          "realPerCapita": 115.57
        },
        {
          "year": 2023,
          "nominalBillions": 44,
          "realPerCapita": 105.37
        },
        {
          "year": 2024,
          "nominalBillions": 43,
          "realPerCapita": 99.39
        },
        {
          "year": 2025,
          "nominalBillions": 42,
          "realPerCapita": 94.6
        }
      ],
      "diminishingReturns": null,
      "efficiency": {
        "rank": 4,
        "totalCountries": 16,
        "spendingPerCapita": 10268,
        "outcome": 37444.1,
        "outcomeName": "Measured after-tax median disposable income (OECD real PPP, equivalised household)",
        "bestCountry": {
          "code": "IRL",
          "name": "Ireland",
          "spendingPerCapita": 9709,
          "outcome": 32668.47,
          "rank": 1
        },
        "topEfficient": [
          {
            "code": "IRL",
            "name": "Ireland",
            "spendingPerCapita": 9709,
            "outcome": 32668.47,
            "rank": 1
          },
          {
            "code": "USA",
            "name": "United States",
            "spendingPerCapita": 10268,
            "outcome": 37444.1,
            "rank": 2
          },
          {
            "code": "NLD",
            "name": "Netherlands",
            "spendingPerCapita": 10605,
            "outcome": 34175.9,
            "rank": 3
          }
        ],
        "floorSpendingPerCapita": 9709,
        "floorOutcome": 32668.47,
        "overspendRatio": 1.1,
        "potentialSavingsPerCapita": 559,
        "potentialSavingsTotal": 189501000000
      },
      "oecdBenchmark": {
        "spendingField": "socialSpendingPerCapitaPpp",
        "fieldLabel": "Public social spending (pensions, health, income support)",
        "scope": "national_field_proxy",
        "lineShareOfField": 0.009,
        "comparisonYears": {
          "target": [
            2018
          ],
          "peer": [
            2020,
            2021,
            2022
          ]
        }
      }
    },
    {
      "id": "justice",
      "name": "Justice / Law Enforcement",
      "currentSpending": 40000000000,
      "currentSpendingRealPerCapita": 90.09,
      "optimalSpendingPerCapita": null,
      "optimalSpendingNominal": null,
      "gap": 0,
      "gapPercent": 0,
      "recommendation": "comparison_only",
      "evidenceSource": "Descriptive national comparison: Public social spending (pensions, health, income support), Measured after-tax median disposable income (OECD real PPP, equivalised household), 16 countries. No causal effect or federal allocation target estimated.",
      "outcomeMetrics": [
        {
          "name": "Violent crime rate",
          "value": 363.8,
          "trend": "improving"
        },
        {
          "name": "Incarceration rate",
          "value": 531,
          "trend": "improving"
        },
        {
          "name": "Federal prison population",
          "value": 158169,
          "trend": "stable"
        }
      ],
      "historicalRealPerCapita": [
        {
          "year": 2015,
          "nominalBillions": 33,
          "realPerCapita": 106.4
        },
        {
          "year": 2016,
          "nominalBillions": 33,
          "realPerCapita": 104.31
        },
        {
          "year": 2017,
          "nominalBillions": 35,
          "realPerCapita": 107.64
        },
        {
          "year": 2018,
          "nominalBillions": 34,
          "realPerCapita": 101.46
        },
        {
          "year": 2019,
          "nominalBillions": 34,
          "realPerCapita": 99.26
        },
        {
          "year": 2020,
          "nominalBillions": 37,
          "realPerCapita": 105.72
        },
        {
          "year": 2021,
          "nominalBillions": 39,
          "realPerCapita": 106.23
        },
        {
          "year": 2022,
          "nominalBillions": 38,
          "realPerCapita": 95.47
        },
        {
          "year": 2023,
          "nominalBillions": 39,
          "realPerCapita": 93.4
        },
        {
          "year": 2024,
          "nominalBillions": 40,
          "realPerCapita": 92.45
        },
        {
          "year": 2025,
          "nominalBillions": 40,
          "realPerCapita": 90.09
        }
      ],
      "diminishingReturns": null,
      "efficiency": {
        "rank": 4,
        "totalCountries": 16,
        "spendingPerCapita": 10268,
        "outcome": 37444.1,
        "outcomeName": "Measured after-tax median disposable income (OECD real PPP, equivalised household)",
        "bestCountry": {
          "code": "IRL",
          "name": "Ireland",
          "spendingPerCapita": 9709,
          "outcome": 32668.47,
          "rank": 1
        },
        "topEfficient": [
          {
            "code": "IRL",
            "name": "Ireland",
            "spendingPerCapita": 9709,
            "outcome": 32668.47,
            "rank": 1
          },
          {
            "code": "USA",
            "name": "United States",
            "spendingPerCapita": 10268,
            "outcome": 37444.1,
            "rank": 2
          },
          {
            "code": "NLD",
            "name": "Netherlands",
            "spendingPerCapita": 10605,
            "outcome": 34175.9,
            "rank": 3
          }
        ],
        "floorSpendingPerCapita": 9709,
        "floorOutcome": 32668.47,
        "overspendRatio": 1.1,
        "potentialSavingsPerCapita": 559,
        "potentialSavingsTotal": 189501000000
      },
      "oecdBenchmark": {
        "spendingField": "socialSpendingPerCapitaPpp",
        "fieldLabel": "Public social spending (pensions, health, income support)",
        "scope": "national_field_proxy",
        "lineShareOfField": 0.009,
        "comparisonYears": {
          "target": [
            2018
          ],
          "peer": [
            2020,
            2021,
            2022
          ]
        }
      }
    },
    {
      "id": "agriculture",
      "name": "Agriculture",
      "currentSpending": 38000000000,
      "currentSpendingRealPerCapita": 85.59,
      "optimalSpendingPerCapita": null,
      "optimalSpendingNominal": null,
      "gap": 0,
      "gapPercent": 0,
      "recommendation": "comparison_only",
      "evidenceSource": "Descriptive national comparison: Public social spending (pensions, health, income support), Measured after-tax median disposable income (OECD real PPP, equivalised household), 16 countries. No causal effect or federal allocation target estimated.",
      "outcomeMetrics": [
        {
          "name": "Food insecurity rate",
          "value": 12.8,
          "trend": "declining"
        },
        {
          "name": "Farm income (net)",
          "value": 116.1,
          "trend": "declining"
        },
        {
          "name": "Crop export value",
          "value": 171,
          "trend": "declining"
        }
      ],
      "historicalRealPerCapita": [
        {
          "year": 2015,
          "nominalBillions": 25,
          "realPerCapita": 80.61
        },
        {
          "year": 2016,
          "nominalBillions": 24,
          "realPerCapita": 75.87
        },
        {
          "year": 2017,
          "nominalBillions": 24,
          "realPerCapita": 73.81
        },
        {
          "year": 2018,
          "nominalBillions": 25,
          "realPerCapita": 74.6
        },
        {
          "year": 2019,
          "nominalBillions": 39,
          "realPerCapita": 113.86
        },
        {
          "year": 2020,
          "nominalBillions": 46,
          "realPerCapita": 131.44
        },
        {
          "year": 2021,
          "nominalBillions": 28,
          "realPerCapita": 76.27
        },
        {
          "year": 2022,
          "nominalBillions": 29,
          "realPerCapita": 72.86
        },
        {
          "year": 2023,
          "nominalBillions": 33,
          "realPerCapita": 79.03
        },
        {
          "year": 2024,
          "nominalBillions": 36,
          "realPerCapita": 83.21
        },
        {
          "year": 2025,
          "nominalBillions": 38,
          "realPerCapita": 85.59
        }
      ],
      "diminishingReturns": null,
      "efficiency": {
        "rank": 4,
        "totalCountries": 16,
        "spendingPerCapita": 10268,
        "outcome": 37444.1,
        "outcomeName": "Measured after-tax median disposable income (OECD real PPP, equivalised household)",
        "bestCountry": {
          "code": "IRL",
          "name": "Ireland",
          "spendingPerCapita": 9709,
          "outcome": 32668.47,
          "rank": 1
        },
        "topEfficient": [
          {
            "code": "IRL",
            "name": "Ireland",
            "spendingPerCapita": 9709,
            "outcome": 32668.47,
            "rank": 1
          },
          {
            "code": "USA",
            "name": "United States",
            "spendingPerCapita": 10268,
            "outcome": 37444.1,
            "rank": 2
          },
          {
            "code": "NLD",
            "name": "Netherlands",
            "spendingPerCapita": 10605,
            "outcome": 34175.9,
            "rank": 3
          }
        ],
        "floorSpendingPerCapita": 9709,
        "floorOutcome": 32668.47,
        "overspendRatio": 1.1,
        "potentialSavingsPerCapita": 559,
        "potentialSavingsTotal": 189501000000
      },
      "oecdBenchmark": {
        "spendingField": "socialSpendingPerCapitaPpp",
        "fieldLabel": "Public social spending (pensions, health, income support)",
        "scope": "national_field_proxy",
        "lineShareOfField": 0.008,
        "comparisonYears": {
          "target": [
            2018
          ],
          "peer": [
            2020,
            2021,
            2022
          ]
        }
      }
    },
    {
      "id": "treasury",
      "name": "Treasury / General Government",
      "currentSpending": 30000000000,
      "currentSpendingRealPerCapita": 67.57,
      "optimalSpendingPerCapita": null,
      "optimalSpendingNominal": null,
      "gap": 0,
      "gapPercent": 0,
      "recommendation": "comparison_only",
      "evidenceSource": "Descriptive national comparison: Public social spending (pensions, health, income support), Measured after-tax median disposable income (OECD real PPP, equivalised household), 16 countries. No causal effect or federal allocation target estimated.",
      "outcomeMetrics": [
        {
          "name": "Tax gap (estimated)",
          "value": 688,
          "trend": "declining"
        },
        {
          "name": "IRS voluntary compliance rate",
          "value": 83.6,
          "trend": "stable"
        }
      ],
      "historicalRealPerCapita": [
        {
          "year": 2015,
          "nominalBillions": 23,
          "realPerCapita": 74.16
        },
        {
          "year": 2016,
          "nominalBillions": 23,
          "realPerCapita": 72.7
        },
        {
          "year": 2017,
          "nominalBillions": 22,
          "realPerCapita": 67.66
        },
        {
          "year": 2018,
          "nominalBillions": 24,
          "realPerCapita": 71.62
        },
        {
          "year": 2019,
          "nominalBillions": 25,
          "realPerCapita": 72.99
        },
        {
          "year": 2020,
          "nominalBillions": 25,
          "realPerCapita": 71.43
        },
        {
          "year": 2021,
          "nominalBillions": 27,
          "realPerCapita": 73.54
        },
        {
          "year": 2022,
          "nominalBillions": 28,
          "realPerCapita": 70.35
        },
        {
          "year": 2023,
          "nominalBillions": 29,
          "realPerCapita": 69.45
        },
        {
          "year": 2024,
          "nominalBillions": 29,
          "realPerCapita": 67.03
        },
        {
          "year": 2025,
          "nominalBillions": 30,
          "realPerCapita": 67.57
        }
      ],
      "diminishingReturns": null,
      "efficiency": {
        "rank": 4,
        "totalCountries": 16,
        "spendingPerCapita": 10268,
        "outcome": 37444.1,
        "outcomeName": "Measured after-tax median disposable income (OECD real PPP, equivalised household)",
        "bestCountry": {
          "code": "IRL",
          "name": "Ireland",
          "spendingPerCapita": 9709,
          "outcome": 32668.47,
          "rank": 1
        },
        "topEfficient": [
          {
            "code": "IRL",
            "name": "Ireland",
            "spendingPerCapita": 9709,
            "outcome": 32668.47,
            "rank": 1
          },
          {
            "code": "USA",
            "name": "United States",
            "spendingPerCapita": 10268,
            "outcome": 37444.1,
            "rank": 2
          },
          {
            "code": "NLD",
            "name": "Netherlands",
            "spendingPerCapita": 10605,
            "outcome": 34175.9,
            "rank": 3
          }
        ],
        "floorSpendingPerCapita": 9709,
        "floorOutcome": 32668.47,
        "overspendRatio": 1.1,
        "potentialSavingsPerCapita": 559,
        "potentialSavingsTotal": 189501000000
      },
      "oecdBenchmark": {
        "spendingField": "socialSpendingPerCapitaPpp",
        "fieldLabel": "Public social spending (pensions, health, income support)",
        "scope": "national_field_proxy",
        "lineShareOfField": 0.007,
        "comparisonYears": {
          "target": [
            2018
          ],
          "peer": [
            2020,
            2021,
            2022
          ]
        }
      }
    },
    {
      "id": "state_department",
      "name": "State Department / Diplomacy",
      "currentSpending": 19000000000,
      "currentSpendingRealPerCapita": 42.79,
      "optimalSpendingPerCapita": null,
      "optimalSpendingNominal": null,
      "gap": 0,
      "gapPercent": 0,
      "recommendation": "comparison_only",
      "evidenceSource": "Descriptive national comparison: Public social spending (pensions, health, income support), Measured after-tax median disposable income (OECD real PPP, equivalised household), 16 countries. No causal effect or federal allocation target estimated.",
      "outcomeMetrics": [
        {
          "name": "US passport holders",
          "value": 160,
          "trend": "improving"
        },
        {
          "name": "Bilateral trade agreements active",
          "value": 14,
          "trend": "stable"
        }
      ],
      "historicalRealPerCapita": [
        {
          "year": 2015,
          "nominalBillions": 15,
          "realPerCapita": 48.36
        },
        {
          "year": 2016,
          "nominalBillions": 15.5,
          "realPerCapita": 49
        },
        {
          "year": 2017,
          "nominalBillions": 15.2,
          "realPerCapita": 46.75
        },
        {
          "year": 2018,
          "nominalBillions": 15,
          "realPerCapita": 44.76
        },
        {
          "year": 2019,
          "nominalBillions": 15.7,
          "realPerCapita": 45.84
        },
        {
          "year": 2020,
          "nominalBillions": 16,
          "realPerCapita": 45.72
        },
        {
          "year": 2021,
          "nominalBillions": 16.5,
          "realPerCapita": 44.94
        },
        {
          "year": 2022,
          "nominalBillions": 17.2,
          "realPerCapita": 43.21
        },
        {
          "year": 2023,
          "nominalBillions": 18,
          "realPerCapita": 43.11
        },
        {
          "year": 2024,
          "nominalBillions": 18.5,
          "realPerCapita": 42.76
        },
        {
          "year": 2025,
          "nominalBillions": 19,
          "realPerCapita": 42.79
        }
      ],
      "diminishingReturns": null,
      "efficiency": {
        "rank": 4,
        "totalCountries": 16,
        "spendingPerCapita": 10268,
        "outcome": 37444.1,
        "outcomeName": "Measured after-tax median disposable income (OECD real PPP, equivalised household)",
        "bestCountry": {
          "code": "IRL",
          "name": "Ireland",
          "spendingPerCapita": 9709,
          "outcome": 32668.47,
          "rank": 1
        },
        "topEfficient": [
          {
            "code": "IRL",
            "name": "Ireland",
            "spendingPerCapita": 9709,
            "outcome": 32668.47,
            "rank": 1
          },
          {
            "code": "USA",
            "name": "United States",
            "spendingPerCapita": 10268,
            "outcome": 37444.1,
            "rank": 2
          },
          {
            "code": "NLD",
            "name": "Netherlands",
            "spendingPerCapita": 10605,
            "outcome": 34175.9,
            "rank": 3
          }
        ],
        "floorSpendingPerCapita": 9709,
        "floorOutcome": 32668.47,
        "overspendRatio": 1.1,
        "potentialSavingsPerCapita": 559,
        "potentialSavingsTotal": 189501000000
      },
      "oecdBenchmark": {
        "spendingField": "socialSpendingPerCapitaPpp",
        "fieldLabel": "Public social spending (pensions, health, income support)",
        "scope": "national_field_proxy",
        "lineShareOfField": 0.004,
        "comparisonYears": {
          "target": [
            2018
          ],
          "peer": [
            2020,
            2021,
            2022
          ]
        }
      }
    },
    {
      "id": "commerce",
      "name": "Commerce / Economic Development",
      "currentSpending": 18000000000,
      "currentSpendingRealPerCapita": 40.54,
      "optimalSpendingPerCapita": null,
      "optimalSpendingNominal": null,
      "gap": 0,
      "gapPercent": 0,
      "recommendation": "comparison_only",
      "evidenceSource": "Descriptive national comparison: Total R&D spending (business and government), Measured after-tax median disposable income (OECD real PPP, equivalised household), 16 countries. No causal effect or federal allocation target estimated.",
      "outcomeMetrics": [
        {
          "name": "GDP growth rate (real)",
          "value": 2.5,
          "trend": "stable"
        },
        {
          "name": "New business applications",
          "value": 5500000,
          "trend": "improving"
        }
      ],
      "historicalRealPerCapita": [
        {
          "year": 2015,
          "nominalBillions": 9,
          "realPerCapita": 29.02
        },
        {
          "year": 2016,
          "nominalBillions": 9.5,
          "realPerCapita": 30.03
        },
        {
          "year": 2017,
          "nominalBillions": 9.2,
          "realPerCapita": 28.29
        },
        {
          "year": 2018,
          "nominalBillions": 11.5,
          "realPerCapita": 34.32
        },
        {
          "year": 2019,
          "nominalBillions": 12,
          "realPerCapita": 35.03
        },
        {
          "year": 2020,
          "nominalBillions": 34,
          "realPerCapita": 97.15
        },
        {
          "year": 2021,
          "nominalBillions": 30,
          "realPerCapita": 81.71
        },
        {
          "year": 2022,
          "nominalBillions": 22,
          "realPerCapita": 55.27
        },
        {
          "year": 2023,
          "nominalBillions": 20,
          "realPerCapita": 47.9
        },
        {
          "year": 2024,
          "nominalBillions": 19,
          "realPerCapita": 43.92
        },
        {
          "year": 2025,
          "nominalBillions": 18,
          "realPerCapita": 40.54
        }
      ],
      "diminishingReturns": null,
      "efficiency": {
        "rank": 10,
        "totalCountries": 16,
        "spendingPerCapita": 1576,
        "outcome": 37444.1,
        "outcomeName": "Measured after-tax median disposable income (OECD real PPP, equivalised household)",
        "bestCountry": {
          "code": "IRL",
          "name": "Ireland",
          "spendingPerCapita": 859,
          "outcome": 32668.47,
          "rank": 1
        },
        "topEfficient": [
          {
            "code": "IRL",
            "name": "Ireland",
            "spendingPerCapita": 859,
            "outcome": 32668.47,
            "rank": 1
          },
          {
            "code": "NLD",
            "name": "Netherlands",
            "spendingPerCapita": 1064,
            "outcome": 34175.9,
            "rank": 2
          },
          {
            "code": "BEL",
            "name": "Belgium",
            "spendingPerCapita": 1293,
            "outcome": 32250.32,
            "rank": 3
          }
        ],
        "floorSpendingPerCapita": 859,
        "floorOutcome": 32668.47,
        "overspendRatio": 1.8,
        "potentialSavingsPerCapita": 717,
        "potentialSavingsTotal": 243063000000
      },
      "oecdBenchmark": {
        "spendingField": "rdSpendingPerCapitaPpp",
        "fieldLabel": "Total R&D spending (business and government)",
        "scope": "national_field_proxy",
        "lineShareOfField": 0.026,
        "comparisonYears": {
          "target": [
            2018
          ],
          "peer": [
            2020,
            2021,
            2022
          ]
        }
      }
    },
    {
      "id": "interior",
      "name": "Interior / Natural Resources",
      "currentSpending": 17000000000,
      "currentSpendingRealPerCapita": 38.29,
      "optimalSpendingPerCapita": null,
      "optimalSpendingNominal": null,
      "gap": 0,
      "gapPercent": 0,
      "recommendation": "comparison_only",
      "evidenceSource": "Descriptive national comparison: Public social spending (pensions, health, income support), Measured after-tax median disposable income (OECD real PPP, equivalised household), 16 countries. No causal effect or federal allocation target estimated.",
      "outcomeMetrics": [
        {
          "name": "National park visits",
          "value": 325.5,
          "trend": "improving"
        },
        {
          "name": "Wildfire acres burned",
          "value": 2693910,
          "trend": "declining"
        },
        {
          "name": "Endangered species recovered",
          "value": 54,
          "trend": "improving"
        }
      ],
      "historicalRealPerCapita": [
        {
          "year": 2015,
          "nominalBillions": 12.4,
          "realPerCapita": 39.98
        },
        {
          "year": 2016,
          "nominalBillions": 13.1,
          "realPerCapita": 41.41
        },
        {
          "year": 2017,
          "nominalBillions": 12.6,
          "realPerCapita": 38.75
        },
        {
          "year": 2018,
          "nominalBillions": 12.9,
          "realPerCapita": 38.5
        },
        {
          "year": 2019,
          "nominalBillions": 13.5,
          "realPerCapita": 39.41
        },
        {
          "year": 2020,
          "nominalBillions": 14.1,
          "realPerCapita": 40.29
        },
        {
          "year": 2021,
          "nominalBillions": 14.8,
          "realPerCapita": 40.31
        },
        {
          "year": 2022,
          "nominalBillions": 15.4,
          "realPerCapita": 38.69
        },
        {
          "year": 2023,
          "nominalBillions": 16,
          "realPerCapita": 38.32
        },
        {
          "year": 2024,
          "nominalBillions": 16.5,
          "realPerCapita": 38.14
        },
        {
          "year": 2025,
          "nominalBillions": 17,
          "realPerCapita": 38.29
        }
      ],
      "diminishingReturns": null,
      "efficiency": {
        "rank": 4,
        "totalCountries": 16,
        "spendingPerCapita": 10268,
        "outcome": 37444.1,
        "outcomeName": "Measured after-tax median disposable income (OECD real PPP, equivalised household)",
        "bestCountry": {
          "code": "IRL",
          "name": "Ireland",
          "spendingPerCapita": 9709,
          "outcome": 32668.47,
          "rank": 1
        },
        "topEfficient": [
          {
            "code": "IRL",
            "name": "Ireland",
            "spendingPerCapita": 9709,
            "outcome": 32668.47,
            "rank": 1
          },
          {
            "code": "USA",
            "name": "United States",
            "spendingPerCapita": 10268,
            "outcome": 37444.1,
            "rank": 2
          },
          {
            "code": "NLD",
            "name": "Netherlands",
            "spendingPerCapita": 10605,
            "outcome": 34175.9,
            "rank": 3
          }
        ],
        "floorSpendingPerCapita": 9709,
        "floorOutcome": 32668.47,
        "overspendRatio": 1.1,
        "potentialSavingsPerCapita": 559,
        "potentialSavingsTotal": 189501000000
      },
      "oecdBenchmark": {
        "spendingField": "socialSpendingPerCapitaPpp",
        "fieldLabel": "Public social spending (pensions, health, income support)",
        "scope": "national_field_proxy",
        "lineShareOfField": 0.004,
        "comparisonYears": {
          "target": [
            2018
          ],
          "peer": [
            2020,
            2021,
            2022
          ]
        }
      }
    },
    {
      "id": "environment",
      "name": "EPA / Environment",
      "currentSpending": 12000000000,
      "currentSpendingRealPerCapita": 27.03,
      "optimalSpendingPerCapita": null,
      "optimalSpendingNominal": null,
      "gap": 0,
      "gapPercent": 0,
      "recommendation": "comparison_only",
      "evidenceSource": "Descriptive national comparison: Public social spending (pensions, health, income support), Measured after-tax median disposable income (OECD real PPP, equivalised household), 16 countries. No causal effect or federal allocation target estimated.",
      "outcomeMetrics": [
        {
          "name": "Days exceeding Air Quality Index standards",
          "value": 117,
          "trend": "declining"
        },
        {
          "name": "Greenhouse gas emissions",
          "value": 5060,
          "trend": "improving"
        },
        {
          "name": "Superfund sites cleaned up (cumulative)",
          "value": 459,
          "trend": "improving"
        },
        {
          "name": "Clean Water Act compliance rate",
          "value": 86,
          "trend": "stable"
        }
      ],
      "historicalRealPerCapita": [
        {
          "year": 2015,
          "nominalBillions": 8.1,
          "realPerCapita": 26.12
        },
        {
          "year": 2016,
          "nominalBillions": 8.6,
          "realPerCapita": 27.19
        },
        {
          "year": 2017,
          "nominalBillions": 8.1,
          "realPerCapita": 24.91
        },
        {
          "year": 2018,
          "nominalBillions": 8.8,
          "realPerCapita": 26.26
        },
        {
          "year": 2019,
          "nominalBillions": 9,
          "realPerCapita": 26.28
        },
        {
          "year": 2020,
          "nominalBillions": 9.4,
          "realPerCapita": 26.86
        },
        {
          "year": 2021,
          "nominalBillions": 9.2,
          "realPerCapita": 25.06
        },
        {
          "year": 2022,
          "nominalBillions": 10.5,
          "realPerCapita": 26.38
        },
        {
          "year": 2023,
          "nominalBillions": 11,
          "realPerCapita": 26.34
        },
        {
          "year": 2024,
          "nominalBillions": 11.5,
          "realPerCapita": 26.58
        },
        {
          "year": 2025,
          "nominalBillions": 12,
          "realPerCapita": 27.03
        }
      ],
      "diminishingReturns": null,
      "efficiency": {
        "rank": 4,
        "totalCountries": 16,
        "spendingPerCapita": 10268,
        "outcome": 37444.1,
        "outcomeName": "Measured after-tax median disposable income (OECD real PPP, equivalised household)",
        "bestCountry": {
          "code": "IRL",
          "name": "Ireland",
          "spendingPerCapita": 9709,
          "outcome": 32668.47,
          "rank": 1
        },
        "topEfficient": [
          {
            "code": "IRL",
            "name": "Ireland",
            "spendingPerCapita": 9709,
            "outcome": 32668.47,
            "rank": 1
          },
          {
            "code": "USA",
            "name": "United States",
            "spendingPerCapita": 10268,
            "outcome": 37444.1,
            "rank": 2
          },
          {
            "code": "NLD",
            "name": "Netherlands",
            "spendingPerCapita": 10605,
            "outcome": 34175.9,
            "rank": 3
          }
        ],
        "floorSpendingPerCapita": 9709,
        "floorOutcome": 32668.47,
        "overspendRatio": 1.1,
        "potentialSavingsPerCapita": 559,
        "potentialSavingsTotal": 189501000000
      },
      "oecdBenchmark": {
        "spendingField": "socialSpendingPerCapitaPpp",
        "fieldLabel": "Public social spending (pensions, health, income support)",
        "scope": "national_field_proxy",
        "lineShareOfField": 0.003,
        "comparisonYears": {
          "target": [
            2018
          ],
          "peer": [
            2020,
            2021,
            2022
          ]
        }
      }
    }
  ],
  "topRecommendations": [
    "National comparison, military spending: United States spends $2052/cap with Life Expectancy 76.93. Switzerland spends $389/cap with Life Expectancy 83.37. The 5.3x spending ratio is descriptive; it does not estimate an achievable saving or allocation target.",
    "National comparison, total health spending (public and private): United States spends $10333/cap with Life Expectancy 76.93. South Korea spends $3588/cap with Life Expectancy 83.57. The 2.9x spending ratio is descriptive; it does not estimate an achievable saving or allocation target.",
    "National comparison, public social spending (pensions, health, income support): United States spends $10268/cap with Measured after-tax median disposable income (OECD real PPP, equivalised household) 37444.1. Ireland spends $9709/cap with Measured after-tax median disposable income (OECD real PPP, equivalised household) 32668.47. The 1.1x spending ratio is descriptive; it does not estimate an achievable saving or allocation target.",
    "National comparison, government education spending (all levels): United States spends $2996/cap with PISA Math Score 465. Japan spends $1288/cap with PISA Math Score 536. The 2.3x spending ratio is descriptive; it does not estimate an achievable saving or allocation target.",
    "National comparison, total R&D spending (business and government): United States spends $1576/cap with Measured after-tax median disposable income (OECD real PPP, equivalised household) 37444.1. Ireland spends $859/cap with Measured after-tax median disposable income (OECD real PPP, equivalised household) 32668.47. The 1.8x spending ratio is descriptive; it does not estimate an achievable saving or allocation target."
  ],
  "generatedAt": "2026-09-26T21:10:03.298Z",
  "generatedBy": "@optimitron/obg descriptive peer comparisons",
  "inflationAdjustment": {
    "method": "CPI-U deflator for US federal spending history",
    "baseYear": 2017,
    "perCapita": true,
    "unit": "constant 2017 USD per capita",
    "note": "National spending comparisons use constant 2017 PPP international dollars. Income outcomes retain their OECD published real PPP basis; they are not denominators for spending dividends."
  },
  "methodology": {
    "comparisonMethod": "Average the latest three available observations per country; select the lowest-spending country among those at or above the 75th percentile of the selected outcome.",
    "observationYears": "Exact target and selected-peer years are recorded in each oecdBenchmark.comparisonYears; sparse series may have fewer than three observations and different years.",
    "incomeEligibility": "OECD IDD METH2012/D_CUR observed after-tax median disposable income, real private-consumption PPP per equivalised household. Excludes interpolated values, nominal income, consumption, government-spending proxies, and incompatible source/unit series. Missing values remain null.",
    "allocationTargets": "Not estimated. Peer spending differences do not establish causal effects, transferable savings, or optimal federal allocations. Null targets are unavailable, not zero.",
    "nonDiscretionary": "Social Security, Medicare, Medicaid, Interest on Debt, and Other Mandatory are outside this discretionary comparison table.",
    "lineAttribution": "National fields can cover several federal lines and non-federal spending. Their observations are context only; no national spending difference is assigned to a federal line."
  },
  "note": "Descriptive cross-country spending and outcome comparisons from the bundled panel, primarily 2000–2022. These are not causal policy estimates. No optimized budget or dividend is produced."
};
