// Auto-generated by generate-web-data.ts — do not edit manually.
// Regenerate with: pnpm --filter @optimitron/web run generate
import type { DecisionReport } from "@optimitron/obg";

export const usDecisionAnalysis: DecisionReport = {
  "version": 1,
  "jurisdiction": "United States",
  "fiscalYear": 2025,
  "baselineOutlaysUsd": 6872000000000,
  "generatedAt": "2026-09-27T03:44:00.859Z",
  "seed": 20260926,
  "draws": 5000,
  "gridUsd": 1000000,
  "objective": "Maximize expected net present social benefit across the explicit reference-scale options, subject to the financing ceiling and protected baseline accounts.",
  "valueBasis": "2025 USD present values for one appropriation tranche. Mortality is valued with VSL; clinical health with value per DALY, less delivery costs; preschool uses participant earnings NPV. Monetized health is not income. Housing rent transfers are reported separately.",
  "recommendedScenarioId": "military-1-percent",
  "policies": [
    {
      "id": "right-to-trial-and-fda-upgrade-act",
      "name": "Right to Trial & FDA Upgrade Act",
      "referenceCase": "Ten years of trial-access infrastructure; conditional US health benefits followed for 20 years.",
      "referenceBudgetUsd": 200000000,
      "annualFundingCapUsd": 200000000,
      "allocationEligible": true,
      "benefit": {
        "mean": 303375056764.9976,
        "median": 145001147232.62793,
        "p05": -130412050820.57901,
        "p95": 1252427827481.5325,
        "probabilityPositive": 0.8308
      },
      "netBenefit": {
        "mean": 302612055471.5532,
        "median": 144338243279.23618,
        "p05": -131528944219.32982,
        "p95": 1251848470508.5798,
        "probabilityPositive": 0.828
      },
      "benefitCostRatio": {
        "mean": 1516.8752838249875,
        "median": 725.0057361631395,
        "p05": -652.0602541028951,
        "p95": 6262.139137407663,
        "probabilityPositive": 0.8308
      },
      "metrics": [
        {
          "label": "US healthy years gained over 20 years",
          "unit": "DALYs averted",
          "estimate": {
            "mean": 11283575.331623098,
            "median": 7573345.0718234535,
            "p05": 413494.495711373,
            "p95": 34082462.19909192,
            "probabilityPositive": 0.9784
          }
        },
        {
          "label": "Discounted US healthy years gained",
          "unit": "DALYs averted",
          "estimate": {
            "mean": 6950908.100654459,
            "median": 4550400.549747454,
            "p05": 252661.65190083528,
            "p95": 21268224.93869594,
            "probabilityPositive": 0.9784
          }
        },
        {
          "label": "Added treatment delivery cost (present value)",
          "unit": "2025 USD present value",
          "estimate": {
            "mean": 392324597756.46436,
            "median": 206731312701.95352,
            "p05": 8066158273.486789,
            "p95": 1423353371622.9568,
            "probabilityPositive": 0.9784
          }
        },
        {
          "label": "Global lifetime DALYs: canonical formula, app scenario priors",
          "unit": "global lifetime DALYs",
          "estimate": {
            "mean": 421516612081.879,
            "median": 397984164312.06494,
            "p05": 226728360203.2426,
            "p95": 703019421863.1597,
            "probabilityPositive": 1
          }
        }
      ],
      "assumptions": [
        {
          "id": "STATE_RTT_IMPLEMENTATION_COST_TOTAL",
          "label": "Universal Right to Try with Evidence Implementation Cost",
          "unit": "USD",
          "low": 25000000,
          "mode": 65000000,
          "high": 200000000,
          "evidence": "scenario",
          "rangeKind": "scenario-range",
          "source": "https://manual.WarOnDisease.org/calculations.html#sec-state_rtt_implementation_cost_total",
          "rationale": "Total implementation cost of adopting Universal Right to Try with Evidence in all 50 states: a central $15 million campaign estimate covering legislation or amendment in all 50 states plus $50 million for the shared registry's first ten years. The model bill requires participating centers to fund continued registry operation after year ten. This launch-cost numerator excludes patient or payer spending on treatment delivery, trial-site services, and permitted study costs. The wide interval represents campaign and infrastructure cost uncertainty without separate scenario parameters. Bounds are inherited model ranges, not asserted to be a published sampling interval."
        },
        {
          "id": "STATE_RTT_TREATMENT_DISCOVERY_MULTIPLIER",
          "label": "Universal Right to Try with Evidence Treatment Discovery Multiplier",
          "unit": "x",
          "low": 1.1,
          "mode": 5.48,
          "high": 15,
          "evidence": "scenario",
          "rangeKind": "scenario-range",
          "source": "https://manual.WarOnDisease.org/calculations.html#sec-state_rtt_treatment_discovery_multiplier",
          "rationale": "Conditional multiplier on the worldwide first-treatment discovery rate after all 50 states adopt and a mature pooled pragmatic-trial system operates under applicable federal authorization. The 5.48x central calibration reproduces the prior model's 82.2 versus 15 first treatments per year; it is an assumption, not an observed effect estimate. This single input incorporates patient or payer funding of treatment delivery, trial-site services, and permitted study costs, newly viable post-Phase-1 treatment-condition pairs, evaluable protocol quality, candidate supply, and scientific success. Its range describes productivity of an operating system, not the separate probability that advocacy achieves full adoption and implementation. Bounds are inherited model ranges, not asserted to be a published sampling interval."
        },
        {
          "id": "RARE_DISEASES_COUNT_GLOBAL",
          "label": "Total Number of Rare Diseases Globally",
          "unit": "diseases",
          "low": 6000,
          "mode": 7000,
          "high": 10000,
          "evidence": "scenario",
          "rangeKind": "scenario-range",
          "source": "https://manual.WarOnDisease.org/calculations.html#sec-rare_diseases_count_global",
          "rationale": "Total number of rare diseases globally Bounds are inherited model ranges, not asserted to be a published sampling interval."
        },
        {
          "id": "rare_disease_untreated_share",
          "label": "Rare diseases without treatment",
          "unit": "fraction",
          "low": 0.95,
          "mode": 0.95,
          "high": 0.95,
          "evidence": "scenario",
          "rangeKind": "fixed",
          "source": "https://manual.warondisease.org/knowledge/appendix/state-right-to-trial-impact",
          "rationale": "Canonical queue-model calibration. The rare-disease queue is a proxy for the wider therapeutic frontier, not a measured schedule for curing all diseases."
        },
        {
          "id": "NEW_DISEASE_FIRST_TREATMENTS_PER_YEAR",
          "label": "Diseases Getting First Treatment Per Year",
          "unit": "diseases/year",
          "low": 8,
          "mode": 15,
          "high": 30,
          "evidence": "scenario",
          "rangeKind": "scenario-range",
          "source": "https://manual.WarOnDisease.org/calculations.html#sec-new_disease_first_treatments_per_year",
          "rationale": "Number of diseases that receive their FIRST effective treatment each year under current system. ~9 rare diseases/year (based on 40 years of ODA: 350 with treatment ÷ 40 years), plus ~5-10 common diseases. Note: FDA approves ~50 drugs/year, but most are for diseases that already have treatments. Bounds are inherited model ranges, not asserted to be a published sampling interval."
        },
        {
          "id": "GLOBAL_ANNUAL_DALY_BURDEN",
          "label": "Global Annual DALY Burden",
          "unit": "DALYs/year",
          "low": 2880000000,
          "mode": 2880000000,
          "high": 2880000000,
          "evidence": "empirical",
          "rangeKind": "fixed",
          "source": "https://vizhub.healthdata.org/gbd-results/",
          "rationale": "Canonical GBD annual burden. Holding it constant across future generations is a separate model assumption."
        },
        {
          "id": "EVENTUALLY_AVOIDABLE_DALY_PCT",
          "label": "Eventually Avoidable DALY Percentage",
          "unit": "percentage",
          "low": 0.5,
          "mode": 0.926278079009,
          "high": 0.98,
          "evidence": "scenario",
          "rangeKind": "scenario-range",
          "source": "https://manual.WarOnDisease.org/calculations.html#sec-eventually_avoidable_daly_pct",
          "rationale": "Percentage of DALYs that are eventually avoidable with sufficient biomedical research. Uses same methodology as EVENTUALLY_AVOIDABLE_DEATH_PCT. Most non-fatal chronic conditions (arthritis, depression, chronic pain) are also addressable through research, so the percentage is similar to deaths. Bounds are inherited model ranges, not asserted to be a published sampling interval."
        },
        {
          "id": "discount",
          "label": "Real discount rate",
          "unit": "fraction/year",
          "low": 0.01,
          "mode": 0.03,
          "high": 0.07,
          "rationale": "Explicit time preference; discounts future clinical benefits and delivery costs once.",
          "source": "https://opg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "value_daly",
          "label": "Value of a healthy year",
          "unit": "2025 USD/DALY",
          "low": 50000,
          "mode": 100000,
          "high": 150000,
          "rationale": "Decision valuation range, not a biological effect or a cash payment. DALYs are valued here using the OBG health-year convention.",
          "source": "https://obg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "military_loss",
          "label": "Forgone military benefit",
          "unit": "present welfare USD/reallocated USD",
          "low": 0.25,
          "mode": 1,
          "high": 10,
          "rationale": "Uncalibrated financing opportunity-cost prior for one budget tranche. All model benefits and losses are present values. Catastrophic security tails are not quantified.",
          "source": "https://opg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "us_burden_share",
          "label": "US share of global disease burden",
          "unit": "fraction",
          "low": 0.025,
          "mode": 0.042375,
          "high": 0.07,
          "rationale": "Population-share anchor 339M/8B with a wide analyst burden-share range; replace with a US GBD disease-age breakdown before deployment.",
          "source": "https://opg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "clinical_adoption",
          "label": "Clinical benefit realized within 20 years",
          "unit": "fraction",
          "low": 0,
          "mode": 0.2,
          "high": 0.6,
          "rationale": "Explicit adoption/delivery scenario. Includes a large attenuation from technical availability to population benefit; not an empirical interval.",
          "source": "https://opg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "discovery_translation",
          "label": "Capacity-to-discovery translation",
          "unit": "fraction",
          "low": -0.03,
          "mode": 0.1,
          "high": 0.3,
          "rationale": "Only this share of the assumed capacity multiplier changes discovery hazard. Negative draws allow capacity expansion to reduce useful discovery. Analyst sensitivity, not a causal estimate.",
          "source": "https://opg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "delivery_cost",
          "label": "Added treatment delivery cost",
          "unit": "2025 USD/DALY gained",
          "low": 0,
          "mode": 20000,
          "high": 150000,
          "rationale": "Subtract downstream patient/payer resource costs before ranking. This broad prior is not a clinical ICER; explicit delivery evidence is still needed.",
          "source": "https://opg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "pragmatic_baseline",
          "label": "Existing pragmatic research funding",
          "unit": "2025 USD",
          "low": 250000000,
          "mode": 500000000,
          "high": 1000000000,
          "rationale": "OBG paper approximate baseline, with an analyst factor-of-two range. Additional funding changes capacity relative to this baseline.",
          "source": "https://obg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "baseline_lag",
          "label": "Discovery-to-availability delay",
          "unit": "years",
          "low": 1,
          "mode": 3,
          "high": 6,
          "rationale": "Explicit discovery/delivery timing assumption; not a measured FDA review duration.",
          "source": "https://opg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        }
      ],
      "overlapGroup": "clinical-trial-discovery",
      "method": "20-year US follow-up: a discovery hazard derived from the canonical average wait, uncertain capacity translation, US burden share, adoption and delivery costs. Funding changes discovery for one year; funded access infrastructure for ten years. Baseline discovery resumes afterwards, while discoveries already made remain available. Both reforms modify one shared process. Original global benchmarks remain separate below.",
      "limitations": [
        "This reproduces the canonical state-legislation scenario. It is an analogue for, not a direct estimate of, the broader federal Right to Trial & FDA Upgrade Act.",
        "The 5.48 discovery multiplier is an explicit assumption, not the observed effect of any enacted law; its range is conditional on a mature operating system and does not include the chance of adoption.",
        "The result covers global future generations. It is not annual US QALYs, current-population healthy life expectancy, or median healthy life years.",
        "Launch cost is not total social cost. Do not use it as the full denominator for comparison with treatment programs that include delivery costs.",
        "This and pragmatic-trial reform share discovery, infrastructure, participants and outcomes. Standalone lifetime totals must not be added.",
        "The funding cap is the evaluated reference-program scale, not an estimate of national absorption capacity. Unmodeled expansion is not implicitly assigned zero benefit.",
        "The clinical allocation case is conditional on implementing the funded program, not a measured effect or a probability of passing the proposed law. Funding affects discovery for its financed period; benefits are followed for 20 years.",
        "The shared-process maximum assumes full overlap between trial funding and access capacity during the first year. Complementarity is not estimated; this assumption can favor access over extra funding.",
        "Canonical clinical source amounts have no verified price year. This adapter treats their quoted dollar amounts as 2025 planning allowances, a scenario valuation assumption."
      ]
    },
    {
      "id": "shift-drug-policy-from-criminal-to-health-approach",
      "name": "Shift Drug Policy from Criminal to Health Approach",
      "referenceCase": "10,000 additional person-years retained in methadone treatment; estimates the treatment component of the proposal.",
      "referenceBudgetUsd": 88000000,
      "annualFundingCapUsd": 88000000,
      "allocationEligible": true,
      "benefit": {
        "mean": 1745567814.4541955,
        "median": 1606442804.24743,
        "p05": 470510892.16854215,
        "p95": 3476620895.6855097,
        "probabilityPositive": 1
      },
      "netBenefit": {
        "mean": 1409847245.3382833,
        "median": 1273883538.6777534,
        "p05": 81549789.09619428,
        "p95": 3178061255.60407,
        "probabilityPositive": 0.9608
      },
      "benefitCostRatio": {
        "mean": 19.835997891524944,
        "median": 18.25503186644807,
        "p05": 5.346714683733434,
        "p95": 39.50705563278988,
        "probabilityPositive": 1
      },
      "metrics": [
        {
          "label": "Deaths averted in one treatment year",
          "unit": "deaths",
          "estimate": {
            "mean": 126.06624373637051,
            "median": 121.07117445136521,
            "p05": 36.96796657346339,
            "p95": 232.58394139689497,
            "probabilityPositive": 1
          }
        }
      ],
      "assumptions": [
        {
          "id": "additional_treatment_years",
          "label": "Additional retained treatment-years",
          "unit": "person-years",
          "low": 10000,
          "mode": 10000,
          "high": 10000,
          "evidence": "scenario",
          "rangeKind": "fixed",
          "source": "https://opg.warondisease.org",
          "rationale": "A service-delivery target, not a claim that decriminalization causes this enrollment. Count time retained, not people who briefly enroll."
        },
        {
          "id": "methadone_cost_2016",
          "label": "Annual methadone program cost",
          "unit": "2016 USD/person-year",
          "low": 6552,
          "mode": 6552,
          "high": 6552,
          "evidence": "empirical",
          "rangeKind": "fixed",
          "source": "https://nida.nih.gov/sites/default/files/21349-medications-to-treat-opioid-use-disorder_0.pdf",
          "rationale": "NIDA quotes a preliminary Department of Defense estimate of $126/week including medication, psychosocial and medical support. Local procurement and present capacity can differ."
        },
        {
          "id": "cpi_2024",
          "label": "2024 annual CPI-U",
          "unit": "index",
          "low": 313.689,
          "mode": 313.689,
          "high": 313.689,
          "evidence": "empirical",
          "rangeKind": "fixed",
          "source": "https://www.bls.gov/cpi/tables/supplemental-files/historical-cpi-u-202412.pdf",
          "rationale": "Annual all-items US city average CPI-U."
        },
        {
          "id": "cpi_2016",
          "label": "2016 annual CPI-U",
          "unit": "index",
          "low": 240.007,
          "mode": 240.007,
          "high": 240.007,
          "evidence": "empirical",
          "rangeKind": "fixed",
          "source": "https://www.bls.gov/cpi/tables/supplemental-files/historical-cpi-u-202412.pdf",
          "rationale": "Deflates the preliminary treatment-cost estimate."
        },
        {
          "id": "methadone_deaths_averted_per_1000_years",
          "label": "Mortality difference during treatment",
          "unit": "deaths/1,000 person-years",
          "low": 14,
          "mode": 25,
          "high": 36,
          "evidence": "empirical",
          "rangeKind": "published-interval",
          "confidenceLevel": 0.95,
          "source": "https://www.bmj.com/content/357/bmj.j1550",
          "rationale": "Sordo et al. BMJ 2017 meta-analysis reports an average difference of 25 deaths/1,000 person-years (95% CI 14–36). Cohort evidence, not randomized assignment or the causal effect of a decriminalization law."
        },
        {
          "id": "treatment_transport",
          "label": "Mortality effect retained in the target setting",
          "unit": "fraction",
          "low": 0,
          "mode": 0.5,
          "high": 1,
          "evidence": "scenario",
          "rangeKind": "scenario-range",
          "source": "https://opg.warondisease.org",
          "rationale": "Explicit zero/half/full transport sensitivity, not a published interval. Allows for selection bias, a different opioid supply, baseline care and implementation."
        },
        {
          "id": "vsl",
          "label": "Value of a statistical life",
          "unit": "2025 USD/death averted",
          "low": 6300000,
          "mode": 14200000,
          "high": 20700000,
          "rationale": "DOT central 2025 valuation (https://www.transportation.gov/office-policy/transportation-policy/revised-departmental-guidance-on-valuation-of-a-statistical-life-in-economic-analysis); HHS low/high valuation sensitivity. Valuation uncertainty is distinct from mortality-effect uncertainty.",
          "source": "https://aspe.hhs.gov/sites/default/files/documents/639756a60fbe7e51786bcec176ad52f1/Standard-RIA-Values-2025.pdf",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "military_loss",
          "label": "Forgone military benefit",
          "unit": "present welfare USD/reallocated USD",
          "low": 0.25,
          "mode": 1,
          "high": 10,
          "rationale": "Uncalibrated financing opportunity-cost prior for one budget tranche. All model benefits and losses are present values. Catastrophic security tails are not quantified.",
          "source": "https://opg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "cpi_2025_ratio",
          "label": "2024-to-2025 price conversion",
          "unit": "ratio",
          "low": 1.0263126854942315,
          "mode": 1.0263126854942315,
          "high": 1.0263126854942315,
          "rationale": "CPI-U 321.943/313.689; applied symmetrically to 2024 program costs and earnings/rent benefits.",
          "source": "https://www.govinfo.gov/content/pkg/ECONI-2026-03/pdf/ECONI-2026-03.pdf",
          "evidence": "scenario",
          "rangeKind": "fixed"
        }
      ],
      "method": "10,000 additional person-years retained in methadone treatment; estimates the treatment component of the proposal. cost = added retained person-years × annual treatment cost × CPI2024/CPI2016; deaths averted = added retained person-years × mortality difference/1,000 × transport share 2024 USD; NIDA preliminary 2016 treatment cost converted using CPI-U. Includes medication and support services; excludes separate law-reform costs.",
      "limitations": [
        "Decriminalization, treatment expansion and harm reduction are different interventions. This estimate does not attribute the treatment effect to changing the criminal law.",
        "Mortality varies during induction and after cessation. Do not apply a full treatment-year benefit to a short enrollment, or add overdose deaths separately to all-cause mortality.",
        "Deaths averted are not QALYs. An age-specific survival and quality-of-life model is needed before estimating healthy years; enforcement savings and wage effects are not estimated.",
        "The funding cap is the evaluated reference-program scale, not an estimate of national absorption capacity. Unmodeled expansion is not implicitly assigned zero benefit."
      ]
    },
    {
      "id": "pragmatic-clinical-trial-funding-reform",
      "name": "Pragmatic Clinical Trial Funding Reform",
      "referenceCase": "One year of extra pragmatic-trial funding; US health benefits followed for 20 years.",
      "referenceBudgetUsd": 20000000,
      "annualFundingCapUsd": 20000000,
      "allocationEligible": true,
      "benefit": {
        "mean": 273408461.9526323,
        "median": 159012586.39060947,
        "p05": -121970853.99498951,
        "p95": 1081792907.4824326,
        "probabilityPositive": 0.8308
      },
      "netBenefit": {
        "mean": 197108332.60810605,
        "median": 88418737.4532587,
        "p05": -214684708.89154848,
        "p95": 1000524557.7422285,
        "probabilityPositive": 0.6486
      },
      "benefitCostRatio": {
        "mean": 13.670423097631618,
        "median": 7.950629319530473,
        "p05": -6.098542699749476,
        "p95": 54.08964537412163,
        "probabilityPositive": 0.8308
      },
      "metrics": [
        {
          "label": "US healthy years gained over 20 years",
          "unit": "DALYs averted",
          "estimate": {
            "mean": 9731.671316025799,
            "median": 7074.516180868434,
            "p05": 574.2211844083527,
            "p95": 27821.4858152722,
            "probabilityPositive": 0.9784
          }
        },
        {
          "label": "Discounted US healthy years gained",
          "unit": "DALYs averted",
          "estimate": {
            "mean": 6408.973023131961,
            "median": 4592.96972152263,
            "p05": 348.52287587789664,
            "p95": 18577.045777478404,
            "probabilityPositive": 0.9784
          }
        },
        {
          "label": "Added treatment delivery cost (present value)",
          "unit": "2025 USD present value",
          "estimate": {
            "mean": 365185839.9673352,
            "median": 205556534.34825116,
            "p05": 11164123.630546493,
            "p95": 1256286547.0931175,
            "probabilityPositive": 0.9784
          }
        },
        {
          "label": "Conditional RECOVERY-scale global QALYs (separate benchmark)",
          "unit": "global QALYs",
          "estimate": {
            "mean": 3521689.8759067827,
            "median": 3159329.1928361165,
            "p05": 885124.5669577986,
            "p95": 7236857.4922259925,
            "probabilityPositive": 1
          }
        }
      ],
      "assumptions": [
        {
          "id": "RECOVERY_TRIAL_TOTAL_COST",
          "label": "RECOVERY Trial Total Cost",
          "unit": "USD",
          "low": 15000000,
          "mode": 20000000,
          "high": 25000000,
          "evidence": "scenario",
          "rangeKind": "scenario-range",
          "source": "https://manual.WarOnDisease.org/calculations.html#sec-recovery_trial_total_cost",
          "rationale": "Total cost of UK RECOVERY trial. Enrolled tens of thousands of patients across multiple treatment arms. Discovered dexamethasone reduces COVID mortality by ~1/3 in severe cases. Bounds are inherited model ranges, not asserted to be a published sampling interval."
        },
        {
          "id": "RECOVERY_TRIAL_GLOBAL_LIVES_SAVED",
          "label": "RECOVERY Trial Global Lives Saved",
          "unit": "lives",
          "low": 500000,
          "mode": 1000000,
          "high": 2000000,
          "evidence": "scenario",
          "rangeKind": "scenario-range",
          "source": "https://manual.WarOnDisease.org/calculations.html#sec-recovery_trial_global_lives_saved",
          "rationale": "Estimated lives saved globally by RECOVERY trial's dexamethasone discovery. NHS England estimate (March 2021). Based on Águas et al. Nature Communications 2021 methodology applying RECOVERY trial mortality reductions (36% ventilated, 18% oxygen) to global COVID hospitalizations. Wide uncertainty range reflects extrapolation assumptions. Bounds are inherited model ranges, not asserted to be a published sampling interval."
        },
        {
          "id": "QALYS_PER_COVID_DEATH_AVERTED",
          "label": "QALYs per COVID Death Averted",
          "unit": "QALYs/death",
          "low": 3,
          "mode": 5,
          "high": 10,
          "evidence": "scenario",
          "rangeKind": "scenario-range",
          "source": "https://manual.WarOnDisease.org/calculations.html#sec-qalys_per_covid_death_averted",
          "rationale": "Average QALYs gained per COVID death averted. Conservative estimate reflecting older age distribution of COVID mortality. See confidence_interval for range. Bounds are inherited model ranges, not asserted to be a published sampling interval."
        },
        {
          "id": "DFDA_PRAGMATIC_TRIAL_COST_PER_PATIENT",
          "label": "Pragmatic Trial Cost per Patient",
          "unit": "USD/patient",
          "low": 97,
          "mode": 929,
          "high": 3000,
          "evidence": "scenario",
          "rangeKind": "scenario-range",
          "source": "https://manual.WarOnDisease.org/calculations.html#sec-dfda_pragmatic_trial_cost_per_patient",
          "rationale": "Embedded pragmatic trial cost per patient. Uses ADAPTABLE trial ($929) as DELIBERATELY CONSERVATIVE central estimate. Ramsberg & Platt (2018) reviewed 108 embedded pragmatic trials; 64 with cost data had median of only $97/patient - this estimate may overstate costs by 10x. Confidence interval spans meta-analysis median to complex chronic disease trials. Bounds are inherited model ranges, not asserted to be a published sampling interval."
        },
        {
          "id": "recovery_transport",
          "label": "Share of RECOVERY-like downstream benefit",
          "unit": "fraction",
          "low": 0,
          "mode": 0.5,
          "high": 1,
          "evidence": "scenario",
          "rangeKind": "scenario-range",
          "source": "https://opg.warondisease.org",
          "rationale": "Explicit sensitivity scenario, not an empirical expected yield for an unselected research portfolio. Zero allows no adopted effective discovery; one reproduces the historical benchmark model. This aggregate factor includes candidate success, attributable discovery and downstream adoption."
        },
        {
          "id": "discount",
          "label": "Real discount rate",
          "unit": "fraction/year",
          "low": 0.01,
          "mode": 0.03,
          "high": 0.07,
          "rationale": "Explicit time preference; discounts future clinical benefits and delivery costs once.",
          "source": "https://opg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "value_daly",
          "label": "Value of a healthy year",
          "unit": "2025 USD/DALY",
          "low": 50000,
          "mode": 100000,
          "high": 150000,
          "rationale": "Decision valuation range, not a biological effect or a cash payment. DALYs are valued here using the OBG health-year convention.",
          "source": "https://obg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "military_loss",
          "label": "Forgone military benefit",
          "unit": "present welfare USD/reallocated USD",
          "low": 0.25,
          "mode": 1,
          "high": 10,
          "rationale": "Uncalibrated financing opportunity-cost prior for one budget tranche. All model benefits and losses are present values. Catastrophic security tails are not quantified.",
          "source": "https://opg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "us_burden_share",
          "label": "US share of global disease burden",
          "unit": "fraction",
          "low": 0.025,
          "mode": 0.042375,
          "high": 0.07,
          "rationale": "Population-share anchor 339M/8B with a wide analyst burden-share range; replace with a US GBD disease-age breakdown before deployment.",
          "source": "https://opg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "clinical_adoption",
          "label": "Clinical benefit realized within 20 years",
          "unit": "fraction",
          "low": 0,
          "mode": 0.2,
          "high": 0.6,
          "rationale": "Explicit adoption/delivery scenario. Includes a large attenuation from technical availability to population benefit; not an empirical interval.",
          "source": "https://opg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "discovery_translation",
          "label": "Capacity-to-discovery translation",
          "unit": "fraction",
          "low": -0.03,
          "mode": 0.1,
          "high": 0.3,
          "rationale": "Only this share of the assumed capacity multiplier changes discovery hazard. Negative draws allow capacity expansion to reduce useful discovery. Analyst sensitivity, not a causal estimate.",
          "source": "https://opg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "delivery_cost",
          "label": "Added treatment delivery cost",
          "unit": "2025 USD/DALY gained",
          "low": 0,
          "mode": 20000,
          "high": 150000,
          "rationale": "Subtract downstream patient/payer resource costs before ranking. This broad prior is not a clinical ICER; explicit delivery evidence is still needed.",
          "source": "https://opg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "pragmatic_baseline",
          "label": "Existing pragmatic research funding",
          "unit": "2025 USD",
          "low": 250000000,
          "mode": 500000000,
          "high": 1000000000,
          "rationale": "OBG paper approximate baseline, with an analyst factor-of-two range. Additional funding changes capacity relative to this baseline.",
          "source": "https://obg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "baseline_lag",
          "label": "Discovery-to-availability delay",
          "unit": "years",
          "low": 1,
          "mode": 3,
          "high": 6,
          "rationale": "Explicit discovery/delivery timing assumption; not a measured FDA review duration.",
          "source": "https://opg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        }
      ],
      "overlapGroup": "clinical-trial-discovery",
      "method": "20-year US follow-up: a discovery hazard derived from the canonical average wait, uncertain capacity translation, US burden share, adoption and delivery costs. Funding changes discovery for one year; funded access infrastructure for ten years. Baseline discovery resumes afterwards, while discoveries already made remain available. Both reforms modify one shared process. Original global benchmarks remain separate below.",
      "limitations": [
        "RECOVERY is a successful pandemic platform, not an unbiased draw from all possible trials. The canonical $4/QALY is retrospective discovery value including downstream adoption, not a demonstrated prospective portfolio yield.",
        "The million-lives figure is a modeled global adoption estimate, and QALYs per death is a model assumption. Their inherited ranges are not published confidence intervals.",
        "No finite common cohort horizon or US-only benefit is supplied. A prospective portfolio model needs trial success, attributable acceleration, adoption and delivery costs before comparison with domestic annual programs.",
        "Pragmatic-trial and Right-to-Trial benefits overlap. Evaluate one shared discovery counterfactual; do not sum these standalone outputs.",
        "The funding cap is the evaluated reference-program scale, not an estimate of national absorption capacity. Unmodeled expansion is not implicitly assigned zero benefit.",
        "The clinical allocation case is conditional on implementing the funded program, not a measured effect or a probability of passing the proposed law. Funding affects discovery for its financed period; benefits are followed for 20 years.",
        "The shared-process maximum assumes full overlap between trial funding and access capacity during the first year. Complementarity is not estimated; this assumption can favor access over extra funding.",
        "Canonical clinical source amounts have no verified price year. This adapter treats their quoted dollar amounts as 2025 planning allowances, a scenario valuation assumption."
      ]
    },
    {
      "id": "universal-pre-k-ages-3-4",
      "name": "Universal Pre-K (Ages 3-4)",
      "referenceCase": "One annual cohort of 100,000 additional children receiving a Perry-like two-year program.",
      "referenceBudgetUsd": 2837000000,
      "annualFundingCapUsd": 2837000000,
      "allocationEligible": true,
      "benefit": {
        "mean": 5697487373.4428215,
        "median": 5726343398.41963,
        "p05": 1846722406.9180639,
        "p95": 9466151185.17691,
        "probabilityPositive": 1
      },
      "netBenefit": {
        "mean": -5125685974.078207,
        "median": -4083592013.863246,
        "p05": -17529870349.012955,
        "p95": 4456185924.019906,
        "probabilityPositive": 0.2648
      },
      "benefitCostRatio": {
        "mean": 2.00827894728334,
        "median": 2.0184502638067077,
        "p05": 0.6509419834043229,
        "p95": 3.3366764840242897,
        "probabilityPositive": 1
      },
      "metrics": [
        {
          "label": "Participant lifetime earnings (present value)",
          "unit": "2025 USD present value",
          "estimate": {
            "mean": 5697487373.4428215,
            "median": 5726343398.41963,
            "p05": 1846722406.9180639,
            "p95": 9466151185.17691,
            "probabilityPositive": 1
          }
        }
      ],
      "assumptions": [
        {
          "id": "prek_children",
          "label": "Additional children",
          "unit": "children",
          "low": 100000,
          "mode": 100000,
          "high": 100000,
          "evidence": "scenario",
          "rangeKind": "fixed",
          "source": "https://opg.warondisease.org",
          "rationale": "Reference enrollment choice, not the US eligible population. Existing preschool enrollees are not counted as additional beneficiaries."
        },
        {
          "id": "perry_cost_2006",
          "label": "Perry program cost per child",
          "unit": "2006 USD/child",
          "low": 17759,
          "mode": 17759,
          "high": 17759,
          "evidence": "empirical",
          "rangeKind": "fixed",
          "source": "https://www.nber.org/papers/w15471",
          "rationale": "Published total program cost, not an annual cost. The intensive program included home visits; universal provision may differ."
        },
        {
          "id": "perry_earnings_npv_2006",
          "label": "Participant lifetime earnings gain",
          "unit": "2006 USD/child",
          "low": 70535,
          "mode": 70535,
          "high": 70535,
          "evidence": "empirical",
          "rangeKind": "fixed",
          "source": "https://opportunityinsights.org/wp-content/uploads/2019/07/Welfare-Appendix.pdf",
          "rationale": "Hendren and Sprung-Keyser extrapolate Perry earnings to age 65. This is a modeled lifetime earnings NPV, not a national median or an annual benefit. No sampling interval is supplied here."
        },
        {
          "id": "cpi_2024",
          "label": "2024 annual CPI-U",
          "unit": "index",
          "low": 313.689,
          "mode": 313.689,
          "high": 313.689,
          "evidence": "empirical",
          "rangeKind": "fixed",
          "source": "https://www.bls.gov/cpi/tables/supplemental-files/historical-cpi-u-202412.pdf",
          "rationale": "Annual all-items US city average CPI-U."
        },
        {
          "id": "cpi_2006",
          "label": "2006 annual CPI-U",
          "unit": "index",
          "low": 201.6,
          "mode": 201.6,
          "high": 201.6,
          "evidence": "empirical",
          "rangeKind": "fixed",
          "source": "https://www.bls.gov/cpi/tables/supplemental-files/historical-cpi-u-202412.pdf",
          "rationale": "Common deflator for program costs and benefits."
        },
        {
          "id": "prek_transport",
          "label": "Share of Perry earnings effect achieved",
          "unit": "fraction",
          "low": 0,
          "mode": 0.5,
          "high": 1,
          "evidence": "scenario",
          "rangeKind": "scenario-range",
          "source": "https://opg.warondisease.org",
          "rationale": "Explicit sensitivity prior: zero to full Perry effect, midpoint one-half. Not estimated from a meta-analysis or elicited from experts. Captures implementation quality and the counterfactual preschool option."
        },
        {
          "id": "military_loss",
          "label": "Forgone military benefit",
          "unit": "present welfare USD/reallocated USD",
          "low": 0.25,
          "mode": 1,
          "high": 10,
          "rationale": "Uncalibrated financing opportunity-cost prior for one budget tranche. All model benefits and losses are present values. Catastrophic security tails are not quantified.",
          "source": "https://opg.warondisease.org",
          "evidence": "scenario",
          "rangeKind": "scenario-range"
        },
        {
          "id": "cpi_2025_ratio",
          "label": "2024-to-2025 price conversion",
          "unit": "ratio",
          "low": 1.0263126854942315,
          "mode": 1.0263126854942315,
          "high": 1.0263126854942315,
          "rationale": "CPI-U 321.943/313.689; applied symmetrically to 2024 program costs and earnings/rent benefits.",
          "source": "https://www.govinfo.gov/content/pkg/ECONI-2026-03/pdf/ECONI-2026-03.pdf",
          "evidence": "scenario",
          "rangeKind": "fixed"
        }
      ],
      "method": "One annual cohort of 100,000 additional children receiving a Perry-like two-year program. cost = additional children × Perry total cost × CPI2024/CPI2006; earnings NPV = additional children × Perry lifetime earnings NPV × CPI2024/CPI2006 × transport share 2024 USD; both cost and earnings converted from 2006 USD using CPI-U. Cost covers the whole preschool program for one entering cohort.",
      "limitations": [
        "Perry studied disadvantaged children in one 1960s setting. Scaling to universal pre-K requires separate estimates for children with existing childcare and different baseline resources.",
        "The earnings amount is already a present value: do not discount it again or multiply it by the 62-year horizon. No additional crime, fiscal or health benefit is added.",
        "The 0/0.5/1 transport range is an explicit analyst scenario. It is not a published confidence interval, and the model does not estimate national median income or health.",
        "The funding cap is the evaluated reference-program scale, not an estimate of national absorption capacity. Unmodeled expansion is not implicitly assigned zero benefit."
      ]
    },
    {
      "id": "housing-supply-deregulation",
      "name": "Housing Supply Deregulation",
      "referenceCase": "One local reform affecting a reference group of 100,000 renter households over ten years.",
      "referenceBudgetUsd": 103000000,
      "annualFundingCapUsd": 103000000,
      "allocationEligible": false,
      "benefit": {
        "mean": 796444168.3378668,
        "median": 770773905.5010768,
        "p05": 236519371.2835198,
        "p95": 1427101436.3989966,
        "probabilityPositive": 1
      },
      "netBenefit": null,
      "benefitCostRatio": null,
      "metrics": [
        {
          "label": "Renter savings over 10 years (present value)",
          "unit": "2025 USD present value",
          "estimate": {
            "mean": 796444168.3378668,
            "median": 770773905.5010768,
            "p05": 236519371.2835198,
            "p95": 1427101436.3989966,
            "probabilityPositive": 1
          }
        }
      ],
      "assumptions": [
        {
          "id": "housing_renter_households",
          "label": "Affected renter households",
          "unit": "households",
          "low": 100000,
          "mode": 100000,
          "high": 100000,
          "evidence": "scenario",
          "rangeKind": "fixed",
          "source": "https://opg.warondisease.org",
          "rationale": "Reference local population; replace with jurisdiction-specific renter households. Do not apply a local effect to every US resident."
        },
        {
          "id": "housing_implementation_cost",
          "label": "Local implementation budget",
          "unit": "2024 USD",
          "low": 50000000,
          "mode": 100000000,
          "high": 200000000,
          "evidence": "scenario",
          "rangeKind": "scenario-range",
          "source": "https://opg.warondisease.org",
          "rationale": "Explicit planning sensitivity, not observed Auckland expenditure or an empirical cost interval. Does not claim to fund private construction."
        },
        {
          "id": "housing_annual_rent",
          "label": "Baseline annual household rent",
          "unit": "2024 USD/household/year",
          "low": 18000,
          "mode": 18000,
          "high": 18000,
          "evidence": "scenario",
          "rangeKind": "fixed",
          "source": "https://opg.warondisease.org",
          "rationale": "Illustrative $1,500/month local baseline, not a national rental statistic; replace with target-jurisdiction data."
        },
        {
          "id": "auckland_rent_reduction",
          "label": "Auckland rent effect after eight years",
          "unit": "fraction",
          "low": 0.23,
          "mode": 0.23,
          "high": 0.23,
          "evidence": "empirical",
          "rangeKind": "fixed",
          "source": "https://doi.org/10.1111/ecin.70075",
          "rationale": "Greenaway-McGrevy and So (2026), preferred synthetic control: quality-adjusted rents for new tenancies 23% below no-reform counterfactual in 2024, eight years after the 2016 reform. Point estimate, not a confidence interval."
        },
        {
          "id": "housing_transport",
          "label": "Share of Auckland effect achieved",
          "unit": "fraction",
          "low": 0,
          "mode": 0.5,
          "high": 1,
          "evidence": "scenario",
          "rangeKind": "scenario-range",
          "source": "https://opg.warondisease.org",
          "rationale": "Explicit zero/half/full scenario for comparability, land constraints, construction capacity and adoption; not published transport uncertainty."
        },
        {
          "id": "housing_discount_rate",
          "label": "Real annual discount rate",
          "unit": "fraction/year",
          "low": 0.03,
          "mode": 0.03,
          "high": 0.03,
          "evidence": "scenario",
          "rangeKind": "fixed",
          "source": "https://opg.warondisease.org",
          "rationale": "Decision-model discount-rate assumption, not a measured outcome."
        },
        {
          "id": "cpi_2025_ratio",
          "label": "2024-to-2025 price conversion",
          "unit": "ratio",
          "low": 1.0263126854942315,
          "mode": 1.0263126854942315,
          "high": 1.0263126854942315,
          "rationale": "CPI-U 321.943/313.689; applied symmetrically to 2024 program costs and earnings/rent benefits.",
          "source": "https://www.govinfo.gov/content/pkg/ECONI-2026-03/pdf/ECONI-2026-03.pdf",
          "evidence": "scenario",
          "rangeKind": "fixed"
        }
      ],
      "method": "One local reform affecting a reference group of 100,000 renter households over ten years. annual renter savings = households × baseline annual rent × 23% × transport share × ramp; ramp is zero through year 2, linear to full effect at year 8; NPV sums years 1–10 at 3% 2024 USD reference implementation budget, an explicit scenario rather than a sourced estimate of the cost of zoning reform. Private construction is not included.",
      "limitations": [
        "The study concerns a large citywide reform and new-tenancy rents. Smaller spot upzonings and existing leases need not have the same effect.",
        "The two-year delay and linear ramp are scenario assumptions; the eight-year endpoint comes from the study. Adoption may fail and construction may remain constrained.",
        "Renter savings are a distributional household benefit, partly offset by landlord income changes. They are not net economic surplus, wage income, national median income or public-budget savings.",
        "Excluded from aggregate social-benefit allocation: a landlord/tenant incidence model and net resource-cost estimate are required. A renter-benefit objective may evaluate this scenario separately.",
        "The old national GDP claim is not used to calibrate this local effect. Greaney's published correction identifies substantial model and code problems: https://www.aeaweb.org/articles?id=10.1257/mac.20230141",
        "The funding cap is the evaluated reference-program scale, not an estimate of national absorption capacity. Unmodeled expansion is not implicitly assigned zero benefit.",
        "Gross renter savings are retained but excluded from the net-social-benefit allocation objective because landlord losses and construction costs are not yet estimated."
      ]
    }
  ],
  "scenarios": [
    {
      "selectedOptionIds": [],
      "annualCostUsd": 0,
      "budgetCeilingUsd": 0,
      "unspentUsd": 0,
      "benefit": {
        "mean": 0,
        "median": 0,
        "p05": 0,
        "p95": 0,
        "probabilityPositive": 0
      },
      "financingLoss": {
        "mean": 0,
        "median": 0,
        "p05": 0,
        "p95": 0,
        "probabilityPositive": 0
      },
      "netBenefit": {
        "mean": 0,
        "median": 0,
        "p05": 0,
        "p95": 0,
        "probabilityPositive": 0
      },
      "draws": 5000,
      "id": "military-0-percent",
      "name": "0% maximum military reallocation",
      "fundingFraction": 0,
      "allocations": [],
      "metrics": [],
      "ledger": [
        {
          "id": "social_security",
          "name": "Social Security",
          "baselineUsd": 1461000000000,
          "proposedUsd": 1461000000000
        },
        {
          "id": "interest_debt",
          "name": "Interest on Debt",
          "baselineUsd": 892000000000,
          "proposedUsd": 892000000000
        },
        {
          "id": "military",
          "name": "Military",
          "baselineUsd": 886000000000,
          "proposedUsd": 886000000000
        },
        {
          "id": "medicare",
          "name": "Medicare",
          "baselineUsd": 874000000000,
          "proposedUsd": 874000000000
        },
        {
          "id": "medicaid",
          "name": "Medicaid",
          "baselineUsd": 616000000000,
          "proposedUsd": 616000000000
        },
        {
          "id": "veterans_affairs",
          "name": "Veterans Affairs",
          "baselineUsd": 325000000000,
          "proposedUsd": 325000000000
        },
        {
          "id": "other_mandatory",
          "name": "Other Mandatory Programs",
          "baselineUsd": 842000000000,
          "proposedUsd": 842000000000
        },
        {
          "id": "transportation",
          "name": "Transportation",
          "baselineUsd": 105000000000,
          "proposedUsd": 105000000000
        },
        {
          "id": "education",
          "name": "Education",
          "baselineUsd": 102000000000,
          "proposedUsd": 102000000000
        },
        {
          "id": "housing",
          "name": "HUD / Housing",
          "baselineUsd": 73000000000,
          "proposedUsd": 73000000000
        },
        {
          "id": "foreign_aid",
          "name": "Foreign Aid / International Affairs",
          "baselineUsd": 63000000000,
          "proposedUsd": 63000000000
        },
        {
          "id": "energy",
          "name": "Energy",
          "baselineUsd": 52000000000,
          "proposedUsd": 52000000000
        },
        {
          "id": "science_nasa",
          "name": "Science / NASA",
          "baselineUsd": 44000000000,
          "proposedUsd": 44000000000
        },
        {
          "id": "justice",
          "name": "Justice / Law Enforcement",
          "baselineUsd": 40000000000,
          "proposedUsd": 40000000000
        },
        {
          "id": "agriculture",
          "name": "Agriculture",
          "baselineUsd": 38000000000,
          "proposedUsd": 38000000000
        },
        {
          "id": "environment",
          "name": "EPA / Environment",
          "baselineUsd": 12000000000,
          "proposedUsd": 12000000000
        },
        {
          "id": "health_discretionary",
          "name": "Health (non-Medicare/Medicaid)",
          "baselineUsd": 94000000000,
          "proposedUsd": 94000000000
        },
        {
          "id": "homeland_security",
          "name": "Homeland Security",
          "baselineUsd": 62000000000,
          "proposedUsd": 62000000000
        },
        {
          "id": "labor",
          "name": "Labor",
          "baselineUsd": 42000000000,
          "proposedUsd": 42000000000
        },
        {
          "id": "commerce",
          "name": "Commerce / Economic Development",
          "baselineUsd": 18000000000,
          "proposedUsd": 18000000000
        },
        {
          "id": "interior",
          "name": "Interior / Natural Resources",
          "baselineUsd": 17000000000,
          "proposedUsd": 17000000000
        },
        {
          "id": "treasury",
          "name": "Treasury / General Government",
          "baselineUsd": 30000000000,
          "proposedUsd": 30000000000
        },
        {
          "id": "state_department",
          "name": "State Department / Diplomacy",
          "baselineUsd": 19000000000,
          "proposedUsd": 19000000000
        },
        {
          "id": "unreconciled_other_outlays",
          "name": "Unreconciled baseline / other outlays",
          "baselineUsd": 165000000000,
          "proposedUsd": 165000000000
        }
      ]
    },
    {
      "selectedOptionIds": [
        "shift-drug-policy-from-criminal-to-health-approach:88000000",
        "right-to-trial-and-fda-upgrade-act:200000000"
      ],
      "annualCostUsd": 288000000,
      "budgetCeilingUsd": 8860000000,
      "unspentUsd": 8572000000,
      "benefit": {
        "mean": 305120624579.4526,
        "median": 146485669146.18872,
        "p05": -129110790947.39891,
        "p95": 1254964260010.8887,
        "probabilityPositive": 0.8358
      },
      "financingLoss": {
        "mean": 1098721862.5611727,
        "median": 996299835.6682328,
        "p05": 246716428.93591627,
        "p95": 2298650547.5407767,
        "probabilityPositive": 1
      },
      "netBenefit": {
        "mean": 304021902716.8909,
        "median": 145760683286.8357,
        "p05": -129787356187.88708,
        "p95": 1253459860932.897,
        "probabilityPositive": 0.8324
      },
      "draws": 5000,
      "id": "military-1-percent",
      "name": "1% maximum military reallocation",
      "fundingFraction": 0.01,
      "allocations": [
        {
          "policyId": "shift-drug-policy-from-criminal-to-health-approach",
          "name": "Shift Drug Policy from Criminal to Health Approach",
          "amountUsd": 88000000
        },
        {
          "policyId": "right-to-trial-and-fda-upgrade-act",
          "name": "Right to Trial & FDA Upgrade Act",
          "amountUsd": 200000000
        }
      ],
      "metrics": [
        {
          "label": "Deaths averted in one treatment year",
          "unit": "deaths",
          "estimate": {
            "mean": 126.06624373637051,
            "median": 121.07117445136521,
            "p05": 36.96796657346339,
            "p95": 232.58394139689497,
            "probabilityPositive": 1
          }
        },
        {
          "label": "US healthy years gained over 20 years",
          "unit": "DALYs averted",
          "estimate": {
            "mean": 11283575.331623098,
            "median": 7573345.0718234535,
            "p05": 413494.495711373,
            "p95": 34082462.19909192,
            "probabilityPositive": 0.9784
          }
        },
        {
          "label": "Discounted US healthy years gained",
          "unit": "DALYs averted",
          "estimate": {
            "mean": 6950908.100654459,
            "median": 4550400.549747454,
            "p05": 252661.65190083528,
            "p95": 21268224.93869594,
            "probabilityPositive": 0.9784
          }
        },
        {
          "label": "Added treatment delivery cost (present value)",
          "unit": "2025 USD present value",
          "estimate": {
            "mean": 392324597756.46436,
            "median": 206731312701.95352,
            "p05": 8066158273.486789,
            "p95": 1423353371622.9568,
            "probabilityPositive": 0.9784
          }
        }
      ],
      "ledger": [
        {
          "id": "social_security",
          "name": "Social Security",
          "baselineUsd": 1461000000000,
          "proposedUsd": 1461000000000
        },
        {
          "id": "interest_debt",
          "name": "Interest on Debt",
          "baselineUsd": 892000000000,
          "proposedUsd": 892000000000
        },
        {
          "id": "military",
          "name": "Military",
          "baselineUsd": 886000000000,
          "proposedUsd": 885712000000
        },
        {
          "id": "medicare",
          "name": "Medicare",
          "baselineUsd": 874000000000,
          "proposedUsd": 874000000000
        },
        {
          "id": "medicaid",
          "name": "Medicaid",
          "baselineUsd": 616000000000,
          "proposedUsd": 616000000000
        },
        {
          "id": "veterans_affairs",
          "name": "Veterans Affairs",
          "baselineUsd": 325000000000,
          "proposedUsd": 325000000000
        },
        {
          "id": "other_mandatory",
          "name": "Other Mandatory Programs",
          "baselineUsd": 842000000000,
          "proposedUsd": 842000000000
        },
        {
          "id": "transportation",
          "name": "Transportation",
          "baselineUsd": 105000000000,
          "proposedUsd": 105000000000
        },
        {
          "id": "education",
          "name": "Education",
          "baselineUsd": 102000000000,
          "proposedUsd": 102000000000
        },
        {
          "id": "housing",
          "name": "HUD / Housing",
          "baselineUsd": 73000000000,
          "proposedUsd": 73000000000
        },
        {
          "id": "foreign_aid",
          "name": "Foreign Aid / International Affairs",
          "baselineUsd": 63000000000,
          "proposedUsd": 63000000000
        },
        {
          "id": "energy",
          "name": "Energy",
          "baselineUsd": 52000000000,
          "proposedUsd": 52000000000
        },
        {
          "id": "science_nasa",
          "name": "Science / NASA",
          "baselineUsd": 44000000000,
          "proposedUsd": 44000000000
        },
        {
          "id": "justice",
          "name": "Justice / Law Enforcement",
          "baselineUsd": 40000000000,
          "proposedUsd": 40000000000
        },
        {
          "id": "agriculture",
          "name": "Agriculture",
          "baselineUsd": 38000000000,
          "proposedUsd": 38000000000
        },
        {
          "id": "environment",
          "name": "EPA / Environment",
          "baselineUsd": 12000000000,
          "proposedUsd": 12000000000
        },
        {
          "id": "health_discretionary",
          "name": "Health (non-Medicare/Medicaid)",
          "baselineUsd": 94000000000,
          "proposedUsd": 94288000000
        },
        {
          "id": "homeland_security",
          "name": "Homeland Security",
          "baselineUsd": 62000000000,
          "proposedUsd": 62000000000
        },
        {
          "id": "labor",
          "name": "Labor",
          "baselineUsd": 42000000000,
          "proposedUsd": 42000000000
        },
        {
          "id": "commerce",
          "name": "Commerce / Economic Development",
          "baselineUsd": 18000000000,
          "proposedUsd": 18000000000
        },
        {
          "id": "interior",
          "name": "Interior / Natural Resources",
          "baselineUsd": 17000000000,
          "proposedUsd": 17000000000
        },
        {
          "id": "treasury",
          "name": "Treasury / General Government",
          "baselineUsd": 30000000000,
          "proposedUsd": 30000000000
        },
        {
          "id": "state_department",
          "name": "State Department / Diplomacy",
          "baselineUsd": 19000000000,
          "proposedUsd": 19000000000
        },
        {
          "id": "unreconciled_other_outlays",
          "name": "Unreconciled baseline / other outlays",
          "baselineUsd": 165000000000,
          "proposedUsd": 165000000000
        }
      ]
    },
    {
      "selectedOptionIds": [
        "shift-drug-policy-from-criminal-to-health-approach:88000000",
        "right-to-trial-and-fda-upgrade-act:200000000"
      ],
      "annualCostUsd": 288000000,
      "budgetCeilingUsd": 44300000000,
      "unspentUsd": 44012000000,
      "benefit": {
        "mean": 305120624579.4526,
        "median": 146485669146.18872,
        "p05": -129110790947.39891,
        "p95": 1254964260010.8887,
        "probabilityPositive": 0.8358
      },
      "financingLoss": {
        "mean": 1098721862.5611727,
        "median": 996299835.6682328,
        "p05": 246716428.93591627,
        "p95": 2298650547.5407767,
        "probabilityPositive": 1
      },
      "netBenefit": {
        "mean": 304021902716.8909,
        "median": 145760683286.8357,
        "p05": -129787356187.88708,
        "p95": 1253459860932.897,
        "probabilityPositive": 0.8324
      },
      "draws": 5000,
      "id": "military-5-percent",
      "name": "5% maximum military reallocation",
      "fundingFraction": 0.05,
      "allocations": [
        {
          "policyId": "shift-drug-policy-from-criminal-to-health-approach",
          "name": "Shift Drug Policy from Criminal to Health Approach",
          "amountUsd": 88000000
        },
        {
          "policyId": "right-to-trial-and-fda-upgrade-act",
          "name": "Right to Trial & FDA Upgrade Act",
          "amountUsd": 200000000
        }
      ],
      "metrics": [
        {
          "label": "Deaths averted in one treatment year",
          "unit": "deaths",
          "estimate": {
            "mean": 126.06624373637051,
            "median": 121.07117445136521,
            "p05": 36.96796657346339,
            "p95": 232.58394139689497,
            "probabilityPositive": 1
          }
        },
        {
          "label": "US healthy years gained over 20 years",
          "unit": "DALYs averted",
          "estimate": {
            "mean": 11283575.331623098,
            "median": 7573345.0718234535,
            "p05": 413494.495711373,
            "p95": 34082462.19909192,
            "probabilityPositive": 0.9784
          }
        },
        {
          "label": "Discounted US healthy years gained",
          "unit": "DALYs averted",
          "estimate": {
            "mean": 6950908.100654459,
            "median": 4550400.549747454,
            "p05": 252661.65190083528,
            "p95": 21268224.93869594,
            "probabilityPositive": 0.9784
          }
        },
        {
          "label": "Added treatment delivery cost (present value)",
          "unit": "2025 USD present value",
          "estimate": {
            "mean": 392324597756.46436,
            "median": 206731312701.95352,
            "p05": 8066158273.486789,
            "p95": 1423353371622.9568,
            "probabilityPositive": 0.9784
          }
        }
      ],
      "ledger": [
        {
          "id": "social_security",
          "name": "Social Security",
          "baselineUsd": 1461000000000,
          "proposedUsd": 1461000000000
        },
        {
          "id": "interest_debt",
          "name": "Interest on Debt",
          "baselineUsd": 892000000000,
          "proposedUsd": 892000000000
        },
        {
          "id": "military",
          "name": "Military",
          "baselineUsd": 886000000000,
          "proposedUsd": 885712000000
        },
        {
          "id": "medicare",
          "name": "Medicare",
          "baselineUsd": 874000000000,
          "proposedUsd": 874000000000
        },
        {
          "id": "medicaid",
          "name": "Medicaid",
          "baselineUsd": 616000000000,
          "proposedUsd": 616000000000
        },
        {
          "id": "veterans_affairs",
          "name": "Veterans Affairs",
          "baselineUsd": 325000000000,
          "proposedUsd": 325000000000
        },
        {
          "id": "other_mandatory",
          "name": "Other Mandatory Programs",
          "baselineUsd": 842000000000,
          "proposedUsd": 842000000000
        },
        {
          "id": "transportation",
          "name": "Transportation",
          "baselineUsd": 105000000000,
          "proposedUsd": 105000000000
        },
        {
          "id": "education",
          "name": "Education",
          "baselineUsd": 102000000000,
          "proposedUsd": 102000000000
        },
        {
          "id": "housing",
          "name": "HUD / Housing",
          "baselineUsd": 73000000000,
          "proposedUsd": 73000000000
        },
        {
          "id": "foreign_aid",
          "name": "Foreign Aid / International Affairs",
          "baselineUsd": 63000000000,
          "proposedUsd": 63000000000
        },
        {
          "id": "energy",
          "name": "Energy",
          "baselineUsd": 52000000000,
          "proposedUsd": 52000000000
        },
        {
          "id": "science_nasa",
          "name": "Science / NASA",
          "baselineUsd": 44000000000,
          "proposedUsd": 44000000000
        },
        {
          "id": "justice",
          "name": "Justice / Law Enforcement",
          "baselineUsd": 40000000000,
          "proposedUsd": 40000000000
        },
        {
          "id": "agriculture",
          "name": "Agriculture",
          "baselineUsd": 38000000000,
          "proposedUsd": 38000000000
        },
        {
          "id": "environment",
          "name": "EPA / Environment",
          "baselineUsd": 12000000000,
          "proposedUsd": 12000000000
        },
        {
          "id": "health_discretionary",
          "name": "Health (non-Medicare/Medicaid)",
          "baselineUsd": 94000000000,
          "proposedUsd": 94288000000
        },
        {
          "id": "homeland_security",
          "name": "Homeland Security",
          "baselineUsd": 62000000000,
          "proposedUsd": 62000000000
        },
        {
          "id": "labor",
          "name": "Labor",
          "baselineUsd": 42000000000,
          "proposedUsd": 42000000000
        },
        {
          "id": "commerce",
          "name": "Commerce / Economic Development",
          "baselineUsd": 18000000000,
          "proposedUsd": 18000000000
        },
        {
          "id": "interior",
          "name": "Interior / Natural Resources",
          "baselineUsd": 17000000000,
          "proposedUsd": 17000000000
        },
        {
          "id": "treasury",
          "name": "Treasury / General Government",
          "baselineUsd": 30000000000,
          "proposedUsd": 30000000000
        },
        {
          "id": "state_department",
          "name": "State Department / Diplomacy",
          "baselineUsd": 19000000000,
          "proposedUsd": 19000000000
        },
        {
          "id": "unreconciled_other_outlays",
          "name": "Unreconciled baseline / other outlays",
          "baselineUsd": 165000000000,
          "proposedUsd": 165000000000
        }
      ]
    },
    {
      "selectedOptionIds": [
        "shift-drug-policy-from-criminal-to-health-approach:88000000",
        "right-to-trial-and-fda-upgrade-act:200000000"
      ],
      "annualCostUsd": 288000000,
      "budgetCeilingUsd": 88600000000,
      "unspentUsd": 88312000000,
      "benefit": {
        "mean": 305120624579.4526,
        "median": 146485669146.18872,
        "p05": -129110790947.39891,
        "p95": 1254964260010.8887,
        "probabilityPositive": 0.8358
      },
      "financingLoss": {
        "mean": 1098721862.5611727,
        "median": 996299835.6682328,
        "p05": 246716428.93591627,
        "p95": 2298650547.5407767,
        "probabilityPositive": 1
      },
      "netBenefit": {
        "mean": 304021902716.8909,
        "median": 145760683286.8357,
        "p05": -129787356187.88708,
        "p95": 1253459860932.897,
        "probabilityPositive": 0.8324
      },
      "draws": 5000,
      "id": "military-10-percent",
      "name": "10% maximum military reallocation",
      "fundingFraction": 0.1,
      "allocations": [
        {
          "policyId": "shift-drug-policy-from-criminal-to-health-approach",
          "name": "Shift Drug Policy from Criminal to Health Approach",
          "amountUsd": 88000000
        },
        {
          "policyId": "right-to-trial-and-fda-upgrade-act",
          "name": "Right to Trial & FDA Upgrade Act",
          "amountUsd": 200000000
        }
      ],
      "metrics": [
        {
          "label": "Deaths averted in one treatment year",
          "unit": "deaths",
          "estimate": {
            "mean": 126.06624373637051,
            "median": 121.07117445136521,
            "p05": 36.96796657346339,
            "p95": 232.58394139689497,
            "probabilityPositive": 1
          }
        },
        {
          "label": "US healthy years gained over 20 years",
          "unit": "DALYs averted",
          "estimate": {
            "mean": 11283575.331623098,
            "median": 7573345.0718234535,
            "p05": 413494.495711373,
            "p95": 34082462.19909192,
            "probabilityPositive": 0.9784
          }
        },
        {
          "label": "Discounted US healthy years gained",
          "unit": "DALYs averted",
          "estimate": {
            "mean": 6950908.100654459,
            "median": 4550400.549747454,
            "p05": 252661.65190083528,
            "p95": 21268224.93869594,
            "probabilityPositive": 0.9784
          }
        },
        {
          "label": "Added treatment delivery cost (present value)",
          "unit": "2025 USD present value",
          "estimate": {
            "mean": 392324597756.46436,
            "median": 206731312701.95352,
            "p05": 8066158273.486789,
            "p95": 1423353371622.9568,
            "probabilityPositive": 0.9784
          }
        }
      ],
      "ledger": [
        {
          "id": "social_security",
          "name": "Social Security",
          "baselineUsd": 1461000000000,
          "proposedUsd": 1461000000000
        },
        {
          "id": "interest_debt",
          "name": "Interest on Debt",
          "baselineUsd": 892000000000,
          "proposedUsd": 892000000000
        },
        {
          "id": "military",
          "name": "Military",
          "baselineUsd": 886000000000,
          "proposedUsd": 885712000000
        },
        {
          "id": "medicare",
          "name": "Medicare",
          "baselineUsd": 874000000000,
          "proposedUsd": 874000000000
        },
        {
          "id": "medicaid",
          "name": "Medicaid",
          "baselineUsd": 616000000000,
          "proposedUsd": 616000000000
        },
        {
          "id": "veterans_affairs",
          "name": "Veterans Affairs",
          "baselineUsd": 325000000000,
          "proposedUsd": 325000000000
        },
        {
          "id": "other_mandatory",
          "name": "Other Mandatory Programs",
          "baselineUsd": 842000000000,
          "proposedUsd": 842000000000
        },
        {
          "id": "transportation",
          "name": "Transportation",
          "baselineUsd": 105000000000,
          "proposedUsd": 105000000000
        },
        {
          "id": "education",
          "name": "Education",
          "baselineUsd": 102000000000,
          "proposedUsd": 102000000000
        },
        {
          "id": "housing",
          "name": "HUD / Housing",
          "baselineUsd": 73000000000,
          "proposedUsd": 73000000000
        },
        {
          "id": "foreign_aid",
          "name": "Foreign Aid / International Affairs",
          "baselineUsd": 63000000000,
          "proposedUsd": 63000000000
        },
        {
          "id": "energy",
          "name": "Energy",
          "baselineUsd": 52000000000,
          "proposedUsd": 52000000000
        },
        {
          "id": "science_nasa",
          "name": "Science / NASA",
          "baselineUsd": 44000000000,
          "proposedUsd": 44000000000
        },
        {
          "id": "justice",
          "name": "Justice / Law Enforcement",
          "baselineUsd": 40000000000,
          "proposedUsd": 40000000000
        },
        {
          "id": "agriculture",
          "name": "Agriculture",
          "baselineUsd": 38000000000,
          "proposedUsd": 38000000000
        },
        {
          "id": "environment",
          "name": "EPA / Environment",
          "baselineUsd": 12000000000,
          "proposedUsd": 12000000000
        },
        {
          "id": "health_discretionary",
          "name": "Health (non-Medicare/Medicaid)",
          "baselineUsd": 94000000000,
          "proposedUsd": 94288000000
        },
        {
          "id": "homeland_security",
          "name": "Homeland Security",
          "baselineUsd": 62000000000,
          "proposedUsd": 62000000000
        },
        {
          "id": "labor",
          "name": "Labor",
          "baselineUsd": 42000000000,
          "proposedUsd": 42000000000
        },
        {
          "id": "commerce",
          "name": "Commerce / Economic Development",
          "baselineUsd": 18000000000,
          "proposedUsd": 18000000000
        },
        {
          "id": "interior",
          "name": "Interior / Natural Resources",
          "baselineUsd": 17000000000,
          "proposedUsd": 17000000000
        },
        {
          "id": "treasury",
          "name": "Treasury / General Government",
          "baselineUsd": 30000000000,
          "proposedUsd": 30000000000
        },
        {
          "id": "state_department",
          "name": "State Department / Diplomacy",
          "baselineUsd": 19000000000,
          "proposedUsd": 19000000000
        },
        {
          "id": "unreconciled_other_outlays",
          "name": "Unreconciled baseline / other outlays",
          "baselineUsd": 165000000000,
          "proposedUsd": 165000000000
        }
      ]
    }
  ],
  "sensitivity": [
    {
      "name": "High military opportunity cost ($10 per dollar)",
      "selectedOptionIds": [
        "shift-drug-policy-from-criminal-to-health-approach:88000000",
        "right-to-trial-and-fda-upgrade-act:200000000"
      ],
      "annualCostUsd": 288000000,
      "budgetCeilingUsd": 8860000000,
      "unspentUsd": 8572000000,
      "benefit": {
        "mean": 305120624579.4526,
        "median": 146485669146.18872,
        "p05": -129110790947.39891,
        "p95": 1254964260010.8887,
        "probabilityPositive": 0.8358
      },
      "financingLoss": {
        "mean": 2880000000,
        "median": 2880000000,
        "p05": 2880000000,
        "p95": 2880000000,
        "probabilityPositive": 1
      },
      "netBenefit": {
        "mean": 302240624579.4526,
        "median": 143605669146.18872,
        "p05": -131990790947.39891,
        "p95": 1252084260010.8887,
        "probabilityPositive": 0.826
      },
      "draws": 5000
    },
    {
      "name": "No clinical discovery or access benefit",
      "selectedOptionIds": [
        "shift-drug-policy-from-criminal-to-health-approach:88000000"
      ],
      "annualCostUsd": 88000000,
      "budgetCeilingUsd": 8860000000,
      "unspentUsd": 8772000000,
      "benefit": {
        "mean": 1745567814.4541955,
        "median": 1606442804.24743,
        "p05": 470510892.16854215,
        "p95": 3476620895.6855097,
        "probabilityPositive": 1
      },
      "financingLoss": {
        "mean": 335720569.1159157,
        "median": 304424949.7875155,
        "p05": 75385575.50819664,
        "p95": 702365445.0819039,
        "probabilityPositive": 1
      },
      "netBenefit": {
        "mean": 1409847245.3382833,
        "median": 1273883538.6777534,
        "p05": 81549789.09619428,
        "p95": 3178061255.60407,
        "probabilityPositive": 0.9608
      },
      "draws": 5000
    },
    {
      "name": "Low military opportunity cost ($0.25 per dollar)",
      "selectedOptionIds": [
        "universal-pre-k-ages-3-4:2837000000",
        "shift-drug-policy-from-criminal-to-health-approach:88000000",
        "right-to-trial-and-fda-upgrade-act:200000000"
      ],
      "annualCostUsd": 3125000000,
      "budgetCeilingUsd": 8860000000,
      "unspentUsd": 5735000000,
      "benefit": {
        "mean": 310818111952.89545,
        "median": 152591083307.59683,
        "p05": -124208840826.75084,
        "p95": 1260726925535.643,
        "probabilityPositive": 0.8526
      },
      "financingLoss": {
        "mean": 781250000,
        "median": 781250000,
        "p05": 781250000,
        "p95": 781250000,
        "probabilityPositive": 1
      },
      "netBenefit": {
        "mean": 310036861952.89545,
        "median": 151809833307.59683,
        "p05": -124990090826.75084,
        "p95": 1259945675535.643,
        "probabilityPositive": 0.8506
      },
      "draws": 5000
    }
  ],
  "assumptions": [
    {
      "id": "discount",
      "label": "Real discount rate",
      "unit": "fraction/year",
      "low": 0.01,
      "mode": 0.03,
      "high": 0.07,
      "rationale": "Explicit time preference; discounts future clinical benefits and delivery costs once.",
      "source": "https://opg.warondisease.org",
      "evidence": "scenario",
      "rangeKind": "scenario-range"
    },
    {
      "id": "value_daly",
      "label": "Value of a healthy year",
      "unit": "2025 USD/DALY",
      "low": 50000,
      "mode": 100000,
      "high": 150000,
      "rationale": "Decision valuation range, not a biological effect or a cash payment. DALYs are valued here using the OBG health-year convention.",
      "source": "https://obg.warondisease.org",
      "evidence": "scenario",
      "rangeKind": "scenario-range"
    },
    {
      "id": "vsl",
      "label": "Value of a statistical life",
      "unit": "2025 USD/death averted",
      "low": 6300000,
      "mode": 14200000,
      "high": 20700000,
      "rationale": "DOT central 2025 valuation (https://www.transportation.gov/office-policy/transportation-policy/revised-departmental-guidance-on-valuation-of-a-statistical-life-in-economic-analysis); HHS low/high valuation sensitivity. Valuation uncertainty is distinct from mortality-effect uncertainty.",
      "source": "https://aspe.hhs.gov/sites/default/files/documents/639756a60fbe7e51786bcec176ad52f1/Standard-RIA-Values-2025.pdf",
      "evidence": "scenario",
      "rangeKind": "scenario-range"
    },
    {
      "id": "military_loss",
      "label": "Forgone military benefit",
      "unit": "present welfare USD/reallocated USD",
      "low": 0.25,
      "mode": 1,
      "high": 10,
      "rationale": "Uncalibrated financing opportunity-cost prior for one budget tranche. All model benefits and losses are present values. Catastrophic security tails are not quantified.",
      "source": "https://opg.warondisease.org",
      "evidence": "scenario",
      "rangeKind": "scenario-range"
    },
    {
      "id": "us_burden_share",
      "label": "US share of global disease burden",
      "unit": "fraction",
      "low": 0.025,
      "mode": 0.042375,
      "high": 0.07,
      "rationale": "Population-share anchor 339M/8B with a wide analyst burden-share range; replace with a US GBD disease-age breakdown before deployment.",
      "source": "https://opg.warondisease.org",
      "evidence": "scenario",
      "rangeKind": "scenario-range"
    },
    {
      "id": "clinical_adoption",
      "label": "Clinical benefit realized within 20 years",
      "unit": "fraction",
      "low": 0,
      "mode": 0.2,
      "high": 0.6,
      "rationale": "Explicit adoption/delivery scenario. Includes a large attenuation from technical availability to population benefit; not an empirical interval.",
      "source": "https://opg.warondisease.org",
      "evidence": "scenario",
      "rangeKind": "scenario-range"
    },
    {
      "id": "discovery_translation",
      "label": "Capacity-to-discovery translation",
      "unit": "fraction",
      "low": -0.03,
      "mode": 0.1,
      "high": 0.3,
      "rationale": "Only this share of the assumed capacity multiplier changes discovery hazard. Negative draws allow capacity expansion to reduce useful discovery. Analyst sensitivity, not a causal estimate.",
      "source": "https://opg.warondisease.org",
      "evidence": "scenario",
      "rangeKind": "scenario-range"
    },
    {
      "id": "delivery_cost",
      "label": "Added treatment delivery cost",
      "unit": "2025 USD/DALY gained",
      "low": 0,
      "mode": 20000,
      "high": 150000,
      "rationale": "Subtract downstream patient/payer resource costs before ranking. This broad prior is not a clinical ICER; explicit delivery evidence is still needed.",
      "source": "https://opg.warondisease.org",
      "evidence": "scenario",
      "rangeKind": "scenario-range"
    },
    {
      "id": "pragmatic_baseline",
      "label": "Existing pragmatic research funding",
      "unit": "2025 USD",
      "low": 250000000,
      "mode": 500000000,
      "high": 1000000000,
      "rationale": "OBG paper approximate baseline, with an analyst factor-of-two range. Additional funding changes capacity relative to this baseline.",
      "source": "https://obg.warondisease.org",
      "evidence": "scenario",
      "rangeKind": "scenario-range"
    },
    {
      "id": "baseline_lag",
      "label": "Discovery-to-availability delay",
      "unit": "years",
      "low": 1,
      "mode": 3,
      "high": 6,
      "rationale": "Explicit discovery/delivery timing assumption; not a measured FDA review duration.",
      "source": "https://opg.warondisease.org",
      "evidence": "scenario",
      "rangeKind": "scenario-range"
    },
    {
      "id": "cpi_2025_ratio",
      "label": "2024-to-2025 price conversion",
      "unit": "ratio",
      "low": 1.0263126854942315,
      "mode": 1.0263126854942315,
      "high": 1.0263126854942315,
      "rationale": "CPI-U 321.943/313.689; applied symmetrically to 2024 program costs and earnings/rent benefits.",
      "source": "https://www.govinfo.gov/content/pkg/ECONI-2026-03/pdf/ECONI-2026-03.pdf",
      "evidence": "scenario",
      "rangeKind": "fixed"
    }
  ],
  "limitations": [
    "The $165B residual balances the displayed estimates; it does not identify a spendable account or prove that the category crosswalk is complete.",
    "Veterans Affairs includes mandatory and discretionary activities. International Affairs may overlap State; agriculture and cross-agency defense activities also need an account crosswalk.",
    "Existing lines remain fixed except for an explicit military reduction and the cost of selected incremental programs. No peer spending gap funds this model.",
    "A modeled one-year appropriation is treated as a same-year outlay equivalent. Actual obligation and outlay timing, contracts, and legislative authority require implementation planning.",
    "This is a constrained reference-program decision, not a demonstrated globally optimal US budget. Most baseline programs are held fixed because their marginal causal effects and statutory constraints are not calibrated.",
    "The grid optimum is exact within the supplied menu and Monte Carlo expected values. Monte Carlo propagates specified uncertainty; it does not establish causality or account for omitted risks.",
    "Clinical discovery assumptions dominate some results. The zero-clinical-benefit sensitivity shows the recommendation when those effects do not materialize.",
    "Ranges marked scenario are analyst or canonical-model priors, not expert-elicited probabilities or empirical confidence intervals. The reported probability of benefit is conditional on this model.",
    "Distinct input parameters are sampled independently. Shared inputs reuse the same draw across alternatives; other correlations are not estimated.",
    "No sum is labeled median after-tax income or median healthy life expectancy. Those require incidence, taxes, survival and distributional data not present here.",
    "Policy benefit horizons differ and remain explicit: existing lifetime earnings NPV, one treatment year, twenty-year clinical flows, and ten-year renter savings. Annual spending does not imply annual realization of lifetime benefits.",
    "National peer-spending differences are descriptive context. They do not enter this optimization as free savings or causal response curves."
  ]
};
