// Auto-generated by generate-web-data.ts — do not edit manually.
// Regenerate with: pnpm --filter @optimitron/web run generate
import type { PolicyReportJSON } from "@optimitron/opg";

export const usPolicyAnalysis: PolicyReportJSON = {
  "jurisdiction": "United States",
  "policies": [
    {
      "name": "Universal Pre-K (Ages 3-4)",
      "type": "budget_allocation",
      "category": "education",
      "description": "Federally funded universal pre-K. Perry Preschool RCT shows $7-12 ROI per dollar over 40 years.",
      "recommendationType": "evaluate",
      "evidenceKind": "assumption",
      "evidenceGrade": null,
      "causalConfidenceScore": null,
      "policyImpactScore": null,
      "welfareScore": null,
      "bradfordHillScores": {},
      "incomeEffect": 0.15,
      "healthEffect": 0.1,
      "rationale": "Perry Preschool RCT: 40-year follow-up shows $7-12 ROI per dollar. Participants had 15% higher income, 20% less likely to be arrested, healthier outcomes. France, Denmark, Finland all have universal pre-K with better PISA scores.",
      "currentStatus": "Only 34% of US 3-year-olds enrolled; varies wildly by state",
      "recommendedTarget": "Federal funding for universal enrollment by age 3",
      "blockingFactors": [
        "budget_constraint"
      ]
    },
    {
      "name": "Shift Drug Policy from Criminal to Health Approach",
      "type": "regulation",
      "category": "health",
      "description": "Decriminalize personal drug use, redirect enforcement budget to treatment. Based on Portugal (2001).",
      "recommendationType": "evaluate",
      "evidenceKind": "assumption",
      "evidenceGrade": null,
      "causalConfidenceScore": null,
      "policyImpactScore": null,
      "welfareScore": null,
      "bradfordHillScores": {},
      "incomeEffect": 0.05,
      "healthEffect": 0.35,
      "rationale": "Portugal decriminalized in 2001: drug deaths dropped 80%, HIV among users dropped 90%, treatment uptake tripled. US spends $40B/yr on drug enforcement with zero measurable reduction in drug deaths (r=0.026). Czech Republic, Switzerland, Netherlands show similar results.",
      "currentStatus": "US spends $40B/yr on enforcement; 1.5M arrests/yr; overdose deaths at record highs",
      "recommendedTarget": "Decriminalize personal use, redirect enforcement budget to treatment",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Pragmatic Clinical Trial Funding Reform",
      "type": "regulation",
      "category": "health_research",
      "description": "Redirect research funding to pragmatic real-world trials. UK NIHR produces actionable evidence at 1/10th the cost.",
      "recommendationType": "evaluate",
      "evidenceKind": "assumption",
      "evidenceGrade": null,
      "causalConfidenceScore": null,
      "policyImpactScore": null,
      "welfareScore": null,
      "bradfordHillScores": {},
      "incomeEffect": 0.05,
      "healthEffect": 0.3,
      "rationale": "NIH spends $48B/yr but 70%+ goes to indirect costs. 85% of findings fail to replicate. UK NIHR model: pragmatic trials embedded in NHS produce actionable evidence at 1/10th the cost. PCORI pragmatic trials show 3x faster clinical adoption.",
      "currentStatus": "NIH: $48B/yr, <10% on pragmatic trials, 85% of findings fail to replicate",
      "recommendedTarget": "Mandate 30%+ of research budget for pragmatic trials with open data requirements",
      "blockingFactors": [
        "institutional_resistance",
        "industry_resistance"
      ]
    },
    {
      "name": "Right to Trial & FDA Upgrade Act",
      "type": "regulation",
      "category": "health_research",
      "description": "Guarantee every patient the right to join a pragmatic trial of any treatment that passed safety testing, and upgrade the FDA to publish real-time outcome labels from all treatment data.",
      "recommendationType": "evaluate",
      "evidenceKind": "assumption",
      "evidenceGrade": null,
      "causalConfidenceScore": null,
      "policyImpactScore": null,
      "welfareScore": null,
      "bradfordHillScores": {},
      "incomeEffect": 0.05,
      "healthEffect": 0.35,
      "rationale": "Oxford RECOVERY enrolled 49,000+ patients through routine hospital care and found four life-saving COVID treatments in months at roughly $500/patient versus ~$41,000 in conventional trials. Most patients are ineligible for conventional trials, and 6,650 diseases have zero approved treatments. The act applies the RECOVERY model to every disease: universal trial-access rights plus automated real-time outcome labels. US Right to Try (2018) and Japan conditional approval are narrow enacted precedents; no country has implemented the full model.",
      "currentStatus": "Draft legislation; most patients ineligible for conventional trials; 6,650 diseases with zero FDA-approved treatments",
      "recommendedTarget": "Enact patient trial-access rights plus a real-time FDA outcome-label platform (dFDA)",
      "blockingFactors": [
        "industry_resistance",
        "institutional_resistance"
      ]
    },
    {
      "name": "Housing Supply Deregulation",
      "type": "regulation",
      "category": "housing",
      "description": "Remove restrictive zoning that constrains housing supply. Tokyo, Minneapolis, Oregon show reduced housing cost growth.",
      "recommendationType": "evaluate",
      "evidenceKind": "assumption",
      "evidenceGrade": null,
      "causalConfidenceScore": null,
      "policyImpactScore": null,
      "welfareScore": null,
      "bradfordHillScores": {},
      "incomeEffect": 0.05,
      "healthEffect": 0.03,
      "rationale": "Tokyo has no housing crisis because they allow building. Minneapolis eliminated single-family zoning: rents stabilized. Oregon statewide upzoning reduced housing cost growth. Hsieh & Moretti (2019) estimate $1.6T/yr GDP cost from restrictive zoning.",
      "currentStatus": "75% of US residential land zoned single-family only",
      "recommendedTarget": "Condition federal grants on local zoning reform",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Military: Adopt Switzerland's Approach",
      "type": "budget_allocation",
      "category": "military",
      "description": "Compare military spending: Switzerland has Life Expectancy 83.37 at $389/cap; United States has 76.93 at $2052/cap.",
      "recommendationType": "compare",
      "evidenceKind": "comparison",
      "evidenceGrade": null,
      "causalConfidenceScore": null,
      "policyImpactScore": null,
      "welfareScore": null,
      "bradfordHillScores": {},
      "incomeEffect": null,
      "healthEffect": null,
      "rationale": "Descriptive spending comparison across 28 countries. The peer has a top-quartile outcome at lower spending; the 5.3x spending ratio does not identify transferable savings or income and health effects. Related federal lines: Military, Homeland Security.",
      "currentStatus": "United States spends $2052/cap on military spending; the selected peer spends $389/cap.",
      "recommendedTarget": "No spending target estimated.",
      "blockingFactors": [
        "causal_effect_not_estimated"
      ],
      "oecdSpendingField": "militarySpendingPerCapitaPpp"
    },
    {
      "name": "National Health Spending: Adopt South Korea's Approach",
      "type": "budget_allocation",
      "category": "health",
      "description": "Compare total health spending (public and private): South Korea has Life Expectancy 83.57 at $3588/cap; United States has 76.93 at $10333/cap.",
      "recommendationType": "compare",
      "evidenceKind": "comparison",
      "evidenceGrade": null,
      "causalConfidenceScore": null,
      "policyImpactScore": null,
      "welfareScore": null,
      "bradfordHillScores": {},
      "incomeEffect": null,
      "healthEffect": null,
      "rationale": "Descriptive spending comparison across 28 countries. The peer has a top-quartile outcome at lower spending; the 2.9x spending ratio does not identify transferable savings or income and health effects. Related federal lines: Veterans Affairs, Health (non-Medicare/Medicaid).",
      "currentStatus": "United States spends $10333/cap on total health spending (public and private); the selected peer spends $3588/cap.",
      "recommendedTarget": "No spending target estimated.",
      "blockingFactors": [
        "causal_effect_not_estimated"
      ],
      "oecdSpendingField": "healthSpendingPerCapitaPpp"
    },
    {
      "name": "Public Education Spending: Adopt Japan's Approach",
      "type": "budget_allocation",
      "category": "education",
      "description": "Compare government education spending (all levels): Japan has PISA Math Score 536 at $1288/cap; United States has 465 at $2996/cap.",
      "recommendationType": "compare",
      "evidenceKind": "comparison",
      "evidenceGrade": null,
      "causalConfidenceScore": null,
      "policyImpactScore": null,
      "welfareScore": null,
      "bradfordHillScores": {},
      "incomeEffect": null,
      "healthEffect": null,
      "rationale": "Descriptive spending comparison across 11 countries. The peer has a top-quartile outcome at lower spending; the 2.3x spending ratio does not identify transferable savings or income and health effects. Related federal lines: Education.",
      "currentStatus": "United States spends $2996/cap on government education spending (all levels); the selected peer spends $1288/cap.",
      "recommendedTarget": "No spending target estimated.",
      "blockingFactors": [
        "causal_effect_not_estimated"
      ],
      "oecdSpendingField": "educationSpendingPerCapitaPpp"
    },
    {
      "name": "National R&D Spending: Adopt Ireland's Approach",
      "type": "budget_allocation",
      "category": "research_and_development",
      "description": "Compare total R&D spending (business and government): Ireland has Measured after-tax median disposable income (OECD real PPP, equivalised household) 32668.47 at $859/cap; United States has 37444.1 at $1576/cap.",
      "recommendationType": "compare",
      "evidenceKind": "comparison",
      "evidenceGrade": null,
      "causalConfidenceScore": null,
      "policyImpactScore": null,
      "welfareScore": null,
      "bradfordHillScores": {},
      "incomeEffect": null,
      "healthEffect": null,
      "rationale": "Descriptive spending comparison across 16 countries. The peer has a top-quartile outcome at lower spending; the 1.8x spending ratio does not identify transferable savings or income and health effects. Related federal lines: Energy, Science / NASA, Commerce / Economic Development.",
      "currentStatus": "United States spends $1576/cap on total R&D spending (business and government); the selected peer spends $859/cap.",
      "recommendedTarget": "No spending target estimated.",
      "blockingFactors": [
        "causal_effect_not_estimated"
      ],
      "oecdSpendingField": "rdSpendingPerCapitaPpp"
    }
  ],
  "generatedAt": "2026-09-26T22:05:34.370Z",
  "generatedBy": "@optimitron/opg evidence inventory",
  "note": "Curated fractional effect assumptions and descriptive national spending comparisons. Effects are not calibrated causal estimates, and no causal grade, welfare ranking, time horizon, or uncertainty interval is inferred."
};
