// Auto-generated by generate-web-data.ts — do not edit manually.
// Regenerate with: pnpm --filter @optimitron/web run generate
import type { PolicyReportJSON } from "@optimitron/opg";

export const usPolicyAnalysis: PolicyReportJSON = {
  "jurisdiction": "United States",
  "policies": [
    {
      "name": "Universal Pre-K (Ages 3-4)",
      "type": "budget_allocation",
      "category": "education",
      "description": "Federally funded universal pre-K. Perry Preschool RCT shows $7-12 ROI per dollar over 40 years.",
      "recommendationType": "reallocate",
      "evidenceGrade": "A",
      "causalConfidenceScore": 0.884,
      "policyImpactScore": 0.683,
      "welfareScore": 38,
      "incomeEffect": 0.15,
      "healthEffect": 0.1,
      "bradfordHillScores": {
        "strength": 0.931,
        "consistency": 0.918,
        "temporality": 1,
        "gradient": 0.662,
        "experiment": 1,
        "plausibility": 1,
        "coherence": 0.993,
        "analogy": 0.85,
        "specificity": 0.358
      },
      "rationale": "Perry Preschool RCT: 40-year follow-up shows $7-12 ROI per dollar. Participants had 15% higher income, 20% less likely to be arrested, healthier outcomes. France, Denmark, Finland all have universal pre-K with better PISA scores.",
      "currentStatus": "Only 34% of US 3-year-olds enrolled; varies wildly by state",
      "recommendedTarget": "Federal funding for universal enrollment by age 3",
      "blockingFactors": [
        "budget_constraint"
      ]
    },
    {
      "name": "Pragmatic Clinical Trial Funding Reform",
      "type": "regulation",
      "category": "health_research",
      "description": "Redirect research funding to pragmatic real-world trials. UK NIHR produces actionable evidence at 1/10th the cost.",
      "recommendationType": "implement",
      "evidenceGrade": "A",
      "causalConfidenceScore": 0.801,
      "policyImpactScore": 0.637,
      "welfareScore": 39,
      "incomeEffect": 0.05,
      "healthEffect": 0.3,
      "bradfordHillScores": {
        "strength": 0.95,
        "consistency": 0.551,
        "temporality": 1,
        "gradient": 0.662,
        "experiment": 1,
        "plausibility": 1,
        "coherence": 0.798,
        "analogy": 0.85,
        "specificity": 0.419
      },
      "rationale": "NIH spends $48B/yr but 70%+ goes to indirect costs. 85% of findings fail to replicate. UK NIHR model: pragmatic trials embedded in NHS produce actionable evidence at 1/10th the cost. PCORI pragmatic trials show 3x faster clinical adoption.",
      "currentStatus": "NIH: $48B/yr, <10% on pragmatic trials, 85% of findings fail to replicate",
      "recommendedTarget": "Mandate 30%+ of research budget for pragmatic trials with open data requirements",
      "blockingFactors": [
        "institutional_resistance",
        "industry_resistance"
      ]
    },
    {
      "name": "Military: Adopt Switzerland's Approach",
      "type": "budget_allocation",
      "category": "military",
      "description": "Reduce military spending to the cheapest high-performer floor. Switzerland achieves Life Expectancy 83.37 at $389/cap; United States gets 76.93 at $2052/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.739,
      "policyImpactScore": 0.596,
      "welfareScore": 38,
      "incomeEffect": 0.408,
      "healthEffect": 0.049,
      "bradfordHillScores": {
        "strength": 0.971,
        "consistency": 0.939,
        "temporality": 1,
        "gradient": 0.662,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.996,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis of military spending: Switzerland achieves Life Expectancy 83.37 at $389/cap. United States at $2052/cap (5.3x overspend). Top 3: Switzerland ($389), Japan ($400), Sweden ($565). Savings: $564B/yr → $4,240/household/yr as Optimization Dividend. Federal budget lines benchmarked against this field: Military, Homeland Security.",
      "currentStatus": "United States spends $2052/cap on military spending, ranks 27/28. 5.3x overspend.",
      "recommendedTarget": "Switzerland model ($389/cap floor). $564B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ],
      "oecdSpendingField": "militarySpendingPerCapitaPpp"
    },
    {
      "name": "National Health Spending: Adopt South Korea's Approach",
      "type": "budget_allocation",
      "category": "health",
      "description": "Reduce total health spending (public and private) to the cheapest high-performer floor. South Korea achieves Life Expectancy 83.57 at $3588/cap; United States gets 76.93 at $10333/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.722,
      "policyImpactScore": 0.591,
      "welfareScore": 39,
      "incomeEffect": 1.656,
      "healthEffect": 0.05,
      "bradfordHillScores": {
        "strength": 0.855,
        "consistency": 0.939,
        "temporality": 1,
        "gradient": 0.662,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.996,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis of total health spending (public and private): South Korea achieves Life Expectancy 83.57 at $3588/cap. United States at $10333/cap (2.9x overspend). Top 3: South Korea ($3588), Japan ($4095), Australia ($4544). Savings: $2287B/yr → $17,192/household/yr as Optimization Dividend. Federal budget lines benchmarked against this field: Veterans Affairs, Health (non-Medicare/Medicaid).",
      "currentStatus": "United States spends $10333/cap on total health spending (public and private), ranks 28/28. 2.9x overspend.",
      "recommendedTarget": "South Korea model ($3588/cap floor). $2287B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ],
      "oecdSpendingField": "healthSpendingPerCapitaPpp"
    },
    {
      "name": "Shift Drug Policy from Criminal to Health Approach",
      "type": "regulation",
      "category": "health",
      "description": "Decriminalize personal drug use, redirect enforcement budget to treatment. Based on Portugal (2001).",
      "recommendationType": "implement",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.695,
      "policyImpactScore": 0.574,
      "welfareScore": 39,
      "incomeEffect": 0.05,
      "healthEffect": 0.35,
      "bradfordHillScores": {
        "strength": 0.982,
        "consistency": 0.777,
        "temporality": 1,
        "gradient": 0.662,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.95,
        "analogy": 0.85,
        "specificity": 0.419
      },
      "rationale": "Portugal decriminalized in 2001: drug deaths dropped 80%, HIV among users dropped 90%, treatment uptake tripled. US spends $40B/yr on drug enforcement with zero measurable reduction in drug deaths (r=0.026). Czech Republic, Switzerland, Netherlands show similar results.",
      "currentStatus": "US spends $40B/yr on enforcement; 1.5M arrests/yr; overdose deaths at record highs",
      "recommendedTarget": "Decriminalize personal use, redirect enforcement budget to treatment",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "Housing Supply Deregulation",
      "type": "regulation",
      "category": "housing",
      "description": "Remove restrictive zoning that constrains housing supply. Tokyo, Minneapolis, Oregon show reduced housing cost growth.",
      "recommendationType": "implement",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.683,
      "policyImpactScore": 0.561,
      "welfareScore": 38,
      "incomeEffect": 0.05,
      "healthEffect": 0.03,
      "bradfordHillScores": {
        "strength": 0.903,
        "consistency": 0.777,
        "temporality": 1,
        "gradient": 0.662,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.95,
        "analogy": 0.85,
        "specificity": 0.419
      },
      "rationale": "Tokyo has no housing crisis because they allow building. Minneapolis eliminated single-family zoning: rents stabilized. Oregon statewide upzoning reduced housing cost growth. Hsieh & Moretti (2019) estimate $1.6T/yr GDP cost from restrictive zoning.",
      "currentStatus": "75% of US residential land zoned single-family only",
      "recommendedTarget": "Condition federal grants on local zoning reform",
      "blockingFactors": [
        "political_opposition"
      ]
    },
    {
      "name": "National R&D Spending: Adopt Netherlands's Approach",
      "type": "budget_allocation",
      "category": "research_and_development",
      "description": "Reduce total R&D spending (business and government) to the cheapest high-performer floor. Netherlands achieves After-Tax Median Income (PPP) 31221.39 at $1064/cap; United States gets 16287.22 at $1991/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.652,
      "policyImpactScore": 0.542,
      "welfareScore": 38,
      "incomeEffect": 0.228,
      "healthEffect": 0,
      "bradfordHillScores": {
        "strength": 0.718,
        "consistency": 0.939,
        "temporality": 1,
        "gradient": 0.265,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.996,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis of total R&D spending (business and government): Netherlands achieves After-Tax Median Income (PPP) 31221.39 at $1064/cap. United States at $1991/cap (1.9x overspend). Top 3: Netherlands ($1064), Norway ($1214), Denmark ($1317). Savings: $314B/yr → $2,363/household/yr as Optimization Dividend. Federal budget lines benchmarked against this field: Energy, Science / NASA, Commerce / Economic Development.",
      "currentStatus": "United States spends $1991/cap on total R&D spending (business and government), ranks 25/28. 1.9x overspend.",
      "recommendedTarget": "Netherlands model ($1064/cap floor). $314B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ],
      "oecdSpendingField": "rdSpendingPerCapitaPpp"
    },
    {
      "name": "Public Education Spending: Adopt Japan's Approach",
      "type": "budget_allocation",
      "category": "education",
      "description": "Reduce government education spending (all levels) to the cheapest high-performer floor. Japan achieves PISA Math Score 536 at $1288/cap; United States gets 465 at $2996/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.649,
      "policyImpactScore": 0.541,
      "welfareScore": 38,
      "incomeEffect": 0.419,
      "healthEffect": 0,
      "bradfordHillScores": {
        "strength": 0.784,
        "consistency": 0.667,
        "temporality": 1,
        "gradient": 0.662,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.889,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis of government education spending (all levels): Japan achieves PISA Math Score 536 at $1288/cap. United States at $2996/cap (2.3x overspend). Top 3: Japan ($1288), Taiwan ($1367), Singapore ($2509). Savings: $579B/yr → $4,353/household/yr as Optimization Dividend. Federal budget lines benchmarked against this field: Education.",
      "currentStatus": "United States spends $2996/cap on government education spending (all levels), ranks 11/11. 2.3x overspend.",
      "recommendedTarget": "Japan model ($1288/cap floor). $579B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ],
      "oecdSpendingField": "educationSpendingPerCapitaPpp"
    },
    {
      "name": "Public Social Spending: Adopt Singapore's Approach",
      "type": "budget_allocation",
      "category": "social_spending",
      "description": "Reduce public social spending (pensions, health, income support) to the cheapest high-performer floor. Singapore achieves After-Tax Median Income (PPP) 36844.31 at $7868/cap; United States gets 16287.22 at $12848/cap.",
      "recommendationType": "reallocate",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.639,
      "policyImpactScore": 0.539,
      "welfareScore": 39,
      "incomeEffect": 1.223,
      "healthEffect": 0,
      "bradfordHillScores": {
        "strength": 0.656,
        "consistency": 0.926,
        "temporality": 1,
        "gradient": 0.265,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.994,
        "analogy": 0.85,
        "specificity": 0.591
      },
      "rationale": "Cheapest-high-performer analysis of public social spending (pensions, health, income support): Singapore achieves After-Tax Median Income (PPP) 36844.31 at $7868/cap. United States at $12848/cap (1.6x overspend). Top 3: Singapore ($7868), Netherlands ($10605), Switzerland ($10699). Savings: $1688B/yr → $12,694/household/yr as Optimization Dividend. Federal budget lines benchmarked against this field: Transportation, HUD / Housing, Foreign Aid / International Affairs, Justice / Law Enforcement, Agriculture, EPA / Environment, Labor, Interior / Natural Resources, Treasury / General Government, State Department / Diplomacy.",
      "currentStatus": "United States spends $12848/cap on public social spending (pensions, health, income support), ranks 23/26. 1.6x overspend.",
      "recommendedTarget": "Singapore model ($7868/cap floor). $1688B/yr savings → Optimization Dividend.",
      "blockingFactors": [
        "political_opposition"
      ],
      "oecdSpendingField": "socialSpendingPerCapitaPpp"
    },
    {
      "name": "Right to Trial & FDA Upgrade Act",
      "type": "regulation",
      "category": "health_research",
      "description": "Guarantee every patient the right to join a pragmatic trial of any treatment that passed safety testing, and upgrade the FDA to publish real-time outcome labels from all treatment data.",
      "recommendationType": "implement",
      "evidenceGrade": "B",
      "causalConfidenceScore": 0.554,
      "policyImpactScore": 0.49,
      "welfareScore": 39,
      "incomeEffect": 0.05,
      "healthEffect": 0.35,
      "bradfordHillScores": {
        "strength": 0.931,
        "consistency": 0.451,
        "temporality": 1,
        "gradient": 0.265,
        "experiment": 0.25,
        "plausibility": 1,
        "coherence": 0.699,
        "analogy": 0.85,
        "specificity": 0.477
      },
      "rationale": "Oxford RECOVERY enrolled 49,000+ patients through routine hospital care and found four life-saving COVID treatments in months at roughly $500/patient versus ~$41,000 in conventional trials. Most patients are ineligible for conventional trials, and 6,650 diseases have zero approved treatments. The act applies the RECOVERY model to every disease: universal trial-access rights plus automated real-time outcome labels. US Right to Try (2018) and Japan conditional approval are narrow enacted precedents; no country has implemented the full model.",
      "currentStatus": "Draft legislation; most patients ineligible for conventional trials; 6,650 diseases with zero FDA-approved treatments",
      "recommendedTarget": "Enact patient trial-access rights plus a real-time FDA outcome-label platform (dFDA)",
      "blockingFactors": [
        "industry_resistance",
        "institutional_resistance"
      ]
    }
  ],
  "generatedAt": "2026-09-25T17:18:15.916Z",
  "generatedBy": "@optimitron/opg",
  "note": "Generated using Bradford Hill scoring and welfare calculation from real cross-country evidence."
};
