"use client"

import { useState } from "react"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { Building2, ExternalLink, CheckCircle2, Clock, XCircle, TrendingUp, Copy, Check, Wrench } from "lucide-react"
import { ROUTES } from '@/lib/routes'
import { getSiteConfig } from '@/lib/site-config'
import { cn } from "@/lib/utils"

interface Organization {
  id: string
  name: string
  slug: string | null
  status: string
  voteCount: number
  createdAt: Date
}

interface OrganizationsCardProps {
  organizations: {
    created: Organization[]
  }
  frameless?: boolean
  className?: string
}

export function OrganizationsCard({ organizations, frameless = false, className }: OrganizationsCardProps) {
  const { created } = organizations
  const [copiedId, setCopiedId] = useState<string | null>(null)

  if (created.length === 0) {
    return null
  }

  const statusColors = {
    PENDING: "bg-brutal-yellow",
    REJECTED: "bg-brutal-pink",
  } as const

  const statusIcons = {
    PENDING: <Clock className="w-3 h-3" />,
    APPROVED: <CheckCircle2 className="w-3 h-3" />,
    REJECTED: <XCircle className="w-3 h-3" />,
  }

  const totalVotes = created.reduce((sum, org) => sum + org.voteCount, 0)

  const handleCopy = async (url: string, id: string) => {
    try {
      await navigator.clipboard.writeText(url)
      setCopiedId(id)
      setTimeout(() => setCopiedId(null), 2000)
    } catch {
      // clipboard blocked — silently ignore
    }
  }

  const content = (
    <>
      <div className="flex flex-wrap items-center justify-end gap-3 mb-6">
        <Link href={ROUTES.institutes}>
          <Button
            variant="outline"
            size="sm"
            className="border-4 border-primary font-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-none transition-all uppercase"
          >
            + CREATE NEW
          </Button>
        </Link>
      </div>

      {/* Total Impact Summary */}
      {totalVotes > 0 && (
        <div className="bg-brutal-yellow border-4 border-primary p-4 mb-6 flex items-center gap-4">
          <TrendingUp className="w-6 h-6" />
          <div>
            <div className="text-2xl font-black">{totalVotes} VOTES</div>
            <div className="text-sm font-bold">Generated by your organizations</div>
          </div>
        </div>
      )}

      {/* Organizations List */}
      <div className="space-y-4">
        {created.map((org) => (
          <div
            key={org.id}
            className="border-4 border-primary p-4 bg-background hover:bg-brutal-yellow/10 transition-colors"
          >
            <div className="flex flex-col gap-3">
              <div className="min-w-0">
                <div className="flex flex-wrap items-center gap-2 mb-2">
                  <h3 className="text-xl font-black uppercase">{org.name}</h3>
                  {org.status === "APPROVED" ? (
                    <span className="inline-flex items-center gap-1 text-[10px] font-bold uppercase text-muted-foreground tracking-wide">
                      {statusIcons.APPROVED}
                      Approved
                    </span>
                  ) : (
                    <div
                      className={`${statusColors[org.status as keyof typeof statusColors] || "bg-background"} border-2 border-primary px-2 py-0.5 text-[10px] font-black uppercase flex items-center gap-1`}
                    >
                      {statusIcons[org.status as keyof typeof statusIcons]}
                      {org.status}
                    </div>
                  )}
                </div>

                <div className="text-sm font-bold">
                  <span className="text-muted-foreground">Votes: </span>
                  <span className="text-brutal-pink text-lg font-black">{org.voteCount}</span>
                </div>
              </div>

              {org.slug && org.status === "APPROVED" && (() => {
                const url = `${getSiteConfig().domain}/survey/${org.slug}`
                const copied = copiedId === org.id
                return (
                  <div className="flex items-stretch border-2 border-primary bg-background min-w-0">
                    <div className="flex-1 min-w-0 px-3 py-2 font-mono text-xs font-bold break-all flex items-center">
                      {url}
                    </div>
                    <button
                      type="button"
                      onClick={() => handleCopy(url, org.id)}
                      className={`shrink-0 border-l-2 border-primary px-3 font-black text-xs uppercase flex items-center gap-1 transition-colors ${
                        copied ? "bg-brutal-cyan" : "bg-brutal-yellow hover:bg-brutal-cyan"
                      }`}
                      aria-label={copied ? "Copied" : "Copy link"}
                    >
                      {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                      <span className="hidden sm:inline">{copied ? "Copied" : "Copy"}</span>
                    </button>
                  </div>
                )
              })()}

              <div className="flex items-center gap-2 flex-wrap">
                {/* slug is generated at org creation (lib/organizations.ts), so always present in practice. */}
                <Link href={`/organizations/${org.slug ?? ""}`}>
                  <Button
                    variant="outline"
                    size="sm"
                    className="border-4 border-primary font-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-none transition-all uppercase"
                  >
                    VIEW DASHBOARD
                  </Button>
                </Link>
                {org.status === "APPROVED" && org.slug && (
                  <Link href={`/organizations/${org.slug}#setup`}>
                    <Button
                      variant="outline"
                      size="sm"
                      className="border-4 border-primary font-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-none transition-all uppercase flex items-center gap-2"
                    >
                      <Wrench className="w-4 h-4" />
                      SET UP SURVEY
                    </Button>
                  </Link>
                )}
                {org.status === "APPROVED" && org.slug && (
                  <Link href={`/survey/${org.slug}`} target="_blank">
                    <Button
                      variant="outline"
                      size="icon"
                      className="border-4 border-primary font-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-none transition-all"
                      title="View Survey Page"
                    >
                      <ExternalLink className="w-4 h-4" />
                    </Button>
                  </Link>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>
    </>
  )

  if (frameless) {
    return <div className={cn("space-y-0", className)}>{content}</div>
  }

  return (
    <Card className={cn("bg-background border-4 border-primary p-6 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]", className)}>
      <div className="flex flex-wrap items-center justify-between gap-3 mb-6">
        <div className="flex items-center gap-3 min-w-0">
          <Building2 className="w-8 h-8 stroke-[3px]" />
          <h2 className="text-2xl font-black uppercase">Your Organizations</h2>
        </div>
        <Link href={ROUTES.institutes}>
          <Button
            variant="outline"
            size="sm"
            className="border-4 border-primary font-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] hover:shadow-none transition-all uppercase"
          >
            + CREATE NEW
          </Button>
        </Link>
      </div>
      {content}
    </Card>
  )
}
