/**
 * Sitemap Route Handler
 *
 * Serves the pre-generated static sitemap XML file for the current variant.
 * The sitemaps are generated by `pnpm generate:sitemaps` and committed to repo.
 *
 * This replaces the dynamic sitemap.ts with static file serving for:
 * - Better performance (no runtime generation)
 * - Version control (see sitemap changes in git)
 * - Predictability (what you commit is what you serve)
 */

import { NextResponse } from 'next/server'
import { readFileSync, existsSync } from 'fs'
import { join } from 'path'
import { getSiteVariant } from '@/lib/site-config'

export async function GET(): Promise<NextResponse> {
  const variant = getSiteVariant()

  // Path to the pre-generated sitemap for this variant
  const sitemapPath = join(process.cwd(), 'public', 'sitemaps', `${variant}.xml`)

  // Check if sitemap exists
  if (!existsSync(sitemapPath)) {
    // Fallback: try to generate on-the-fly or return error
    return new NextResponse(
      `<!-- Sitemap not found for variant: ${variant}. Run: pnpm generate:sitemaps -->`,
      {
        status: 404,
        headers: {
          'Content-Type': 'application/xml',
        },
      }
    )
  }

  // Read and serve the static sitemap
  const sitemapContent = readFileSync(sitemapPath, 'utf-8')

  return new NextResponse(sitemapContent, {
    headers: {
      'Content-Type': 'application/xml',
      'Cache-Control': 'public, max-age=3600, s-maxage=86400', // Cache for 1 hour client, 1 day CDN
    },
  })
}
